// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coffins.sql

package store

import (
	"context"
	"time"
)

const getCoffin = `-- name: GetCoffin :one
SELECT id, problem_id, released_at, solution_tex_source, solution_pdf_object_key, solution_link, created_at, updated_at
FROM math_center_coffins
WHERE id = $1
`

func (q *Queries) GetCoffin(ctx context.Context, id int64) (MathCenterCoffin, error) {
	row := q.db.QueryRow(ctx, getCoffin, id)
	var i MathCenterCoffin
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.ReleasedAt,
		&i.SolutionTexSource,
		&i.SolutionPdfObjectKey,
		&i.SolutionLink,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoffinByProblem = `-- name: GetCoffinByProblem :one
SELECT id, problem_id, released_at, solution_tex_source, solution_pdf_object_key, solution_link, created_at, updated_at
FROM math_center_coffins
WHERE problem_id = $1
`

func (q *Queries) GetCoffinByProblem(ctx context.Context, problemID int64) (MathCenterCoffin, error) {
	row := q.db.QueryRow(ctx, getCoffinByProblem, problemID)
	var i MathCenterCoffin
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.ReleasedAt,
		&i.SolutionTexSource,
		&i.SolutionPdfObjectKey,
		&i.SolutionLink,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoffinCenter = `-- name: GetCoffinCenter :one
SELECT c.id             AS coffin_id,
       c.problem_id     AS problem_id,
       s.math_center_id AS math_center_id
FROM math_center_coffins c
         JOIN math_center_problems p ON p.id = c.problem_id
         JOIN math_center_series s ON s.id = p.series_id
WHERE c.id = $1
`

type GetCoffinCenterRow struct {
	CoffinID     int64 `json:"coffin_id"`
	ProblemID    int64 `json:"problem_id"`
	MathCenterID int64 `json:"math_center_id"`
}

// Resolve a coffin to its problem + center, for authorizing release/solution.
func (q *Queries) GetCoffinCenter(ctx context.Context, id int64) (GetCoffinCenterRow, error) {
	row := q.db.QueryRow(ctx, getCoffinCenter, id)
	var i GetCoffinCenterRow
	err := row.Scan(&i.CoffinID, &i.ProblemID, &i.MathCenterID)
	return i, err
}

const listCenterCoffins = `-- name: ListCenterCoffins :many
SELECT c.id                      AS id,
       c.problem_id              AS problem_id,
       c.released_at             AS released_at,
       c.solution_tex_source     AS solution_tex_source,
       c.solution_pdf_object_key AS solution_pdf_object_key,
       c.solution_link           AS solution_link,
       c.created_at              AS created_at,
       p.number                  AS problem_number,
       s.id                      AS series_id,
       s.number                  AS series_number,
       s.name                    AS series_name,
       s.math_center_id          AS math_center_id
FROM math_center_coffins c
         JOIN math_center_problems p ON p.id = c.problem_id
         JOIN math_center_series s ON s.id = p.series_id
WHERE s.math_center_id = $1
ORDER BY s.number DESC, p.number ASC
`

type ListCenterCoffinsRow struct {
	ID                   int64      `json:"id"`
	ProblemID            int64      `json:"problem_id"`
	ReleasedAt           *time.Time `json:"released_at"`
	SolutionTexSource    *string    `json:"solution_tex_source"`
	SolutionPdfObjectKey *string    `json:"solution_pdf_object_key"`
	SolutionLink         *string    `json:"solution_link"`
	CreatedAt            time.Time  `json:"created_at"`
	ProblemNumber        int32      `json:"problem_number"`
	SeriesID             int64      `json:"series_id"`
	SeriesNumber         int32      `json:"series_number"`
	SeriesName           string     `json:"series_name"`
	MathCenterID         int64      `json:"math_center_id"`
}

// Every coffin in a center with the labels the UI needs (series + problem),
// newest series first. Used by the center-wide "Гробы" tab.
func (q *Queries) ListCenterCoffins(ctx context.Context, mathCenterID int64) ([]ListCenterCoffinsRow, error) {
	rows, err := q.db.Query(ctx, listCenterCoffins, mathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCenterCoffinsRow{}
	for rows.Next() {
		var i ListCenterCoffinsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.ReleasedAt,
			&i.SolutionTexSource,
			&i.SolutionPdfObjectKey,
			&i.SolutionLink,
			&i.CreatedAt,
			&i.ProblemNumber,
			&i.SeriesID,
			&i.SeriesNumber,
			&i.SeriesName,
			&i.MathCenterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoffinSubproblemsForStudent = `-- name: ListCoffinSubproblemsForStudent :many
SELECT c.id            AS coffin_id,
       sp.id           AS subproblem_id,
       sp.label        AS subproblem_label,
       COALESCE(t.id, 0)::bigint              AS thread_id,
       COALESCE(t.current_status, 'ungraded') AS current_status,
       (t.claim_holder_user_id IS NOT NULL
            AND t.claim_expires_at > now())::boolean AS being_graded
FROM math_center_coffins c
         JOIN math_center_problems p ON p.id = c.problem_id
         JOIN math_center_series s ON s.id = p.series_id
         JOIN math_center_subproblems sp ON sp.problem_id = p.id
         LEFT JOIN homework_thread t
                   ON t.subproblem_id = sp.id
                  AND t.student_user_id = $2::bigint
WHERE s.math_center_id = $1
ORDER BY p.number ASC, sp.label ASC
`

type ListCoffinSubproblemsForStudentParams struct {
	MathCenterID  int64 `json:"math_center_id"`
	StudentUserID int64 `json:"student_user_id"`
}

type ListCoffinSubproblemsForStudentRow struct {
	CoffinID        int64  `json:"coffin_id"`
	SubproblemID    int64  `json:"subproblem_id"`
	SubproblemLabel string `json:"subproblem_label"`
	ThreadID        int64  `json:"thread_id"`
	CurrentStatus   string `json:"current_status"`
	BeingGraded     bool   `json:"being_graded"`
}

// For every coffin in a center, the problem's subproblems with the calling
// student's thread status — so the Гробы tab can show tiles + a "Сдать" link.
func (q *Queries) ListCoffinSubproblemsForStudent(ctx context.Context, arg ListCoffinSubproblemsForStudentParams) ([]ListCoffinSubproblemsForStudentRow, error) {
	rows, err := q.db.Query(ctx, listCoffinSubproblemsForStudent, arg.MathCenterID, arg.StudentUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoffinSubproblemsForStudentRow{}
	for rows.Next() {
		var i ListCoffinSubproblemsForStudentRow
		if err := rows.Scan(
			&i.CoffinID,
			&i.SubproblemID,
			&i.SubproblemLabel,
			&i.ThreadID,
			&i.CurrentStatus,
			&i.BeingGraded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCoffin = `-- name: MarkCoffin :one

INSERT INTO math_center_coffins (problem_id)
VALUES ($1)
ON CONFLICT (problem_id) DO UPDATE SET updated_at = NOW()
RETURNING id, problem_id, released_at, solution_tex_source, solution_pdf_object_key, solution_link, created_at, updated_at
`

// Coffins ("гробы"): hard problems kept open for submission past the series
// deadline until their own разбор is released. A problem is a coffin iff a row
// exists. See migration 000010.
// Idempotent mark: re-marking an existing coffin is a no-op touch.
func (q *Queries) MarkCoffin(ctx context.Context, problemID int64) (MathCenterCoffin, error) {
	row := q.db.QueryRow(ctx, markCoffin, problemID)
	var i MathCenterCoffin
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.ReleasedAt,
		&i.SolutionTexSource,
		&i.SolutionPdfObjectKey,
		&i.SolutionLink,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseCoffin = `-- name: ReleaseCoffin :one
UPDATE math_center_coffins
SET released_at = COALESCE(released_at, NOW()),
    updated_at  = NOW()
WHERE id = $1
RETURNING id, problem_id, released_at, solution_tex_source, solution_pdf_object_key, solution_link, created_at, updated_at
`

// Stamps released_at (first release wins) — closes submission + makes the
// coffin's solution available.
func (q *Queries) ReleaseCoffin(ctx context.Context, id int64) (MathCenterCoffin, error) {
	row := q.db.QueryRow(ctx, releaseCoffin, id)
	var i MathCenterCoffin
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.ReleasedAt,
		&i.SolutionTexSource,
		&i.SolutionPdfObjectKey,
		&i.SolutionLink,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCoffinSolutionLink = `-- name: SetCoffinSolutionLink :one
UPDATE math_center_coffins
SET solution_link = $2,
    updated_at    = NOW()
WHERE id = $1
RETURNING id, problem_id, released_at, solution_tex_source, solution_pdf_object_key, solution_link, created_at, updated_at
`

type SetCoffinSolutionLinkParams struct {
	ID           int64   `json:"id"`
	SolutionLink *string `json:"solution_link"`
}

func (q *Queries) SetCoffinSolutionLink(ctx context.Context, arg SetCoffinSolutionLinkParams) (MathCenterCoffin, error) {
	row := q.db.QueryRow(ctx, setCoffinSolutionLink, arg.ID, arg.SolutionLink)
	var i MathCenterCoffin
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.ReleasedAt,
		&i.SolutionTexSource,
		&i.SolutionPdfObjectKey,
		&i.SolutionLink,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCoffinSolutionPdf = `-- name: SetCoffinSolutionPdf :one
UPDATE math_center_coffins
SET solution_pdf_object_key = $2,
    updated_at              = NOW()
WHERE id = $1
RETURNING id, problem_id, released_at, solution_tex_source, solution_pdf_object_key, solution_link, created_at, updated_at
`

type SetCoffinSolutionPdfParams struct {
	ID                   int64   `json:"id"`
	SolutionPdfObjectKey *string `json:"solution_pdf_object_key"`
}

func (q *Queries) SetCoffinSolutionPdf(ctx context.Context, arg SetCoffinSolutionPdfParams) (MathCenterCoffin, error) {
	row := q.db.QueryRow(ctx, setCoffinSolutionPdf, arg.ID, arg.SolutionPdfObjectKey)
	var i MathCenterCoffin
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.ReleasedAt,
		&i.SolutionTexSource,
		&i.SolutionPdfObjectKey,
		&i.SolutionLink,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCoffinSolutionTex = `-- name: SetCoffinSolutionTex :one
UPDATE math_center_coffins
SET solution_tex_source = $2,
    updated_at          = NOW()
WHERE id = $1
RETURNING id, problem_id, released_at, solution_tex_source, solution_pdf_object_key, solution_link, created_at, updated_at
`

type SetCoffinSolutionTexParams struct {
	ID                int64   `json:"id"`
	SolutionTexSource *string `json:"solution_tex_source"`
}

func (q *Queries) SetCoffinSolutionTex(ctx context.Context, arg SetCoffinSolutionTexParams) (MathCenterCoffin, error) {
	row := q.db.QueryRow(ctx, setCoffinSolutionTex, arg.ID, arg.SolutionTexSource)
	var i MathCenterCoffin
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.ReleasedAt,
		&i.SolutionTexSource,
		&i.SolutionPdfObjectKey,
		&i.SolutionLink,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unmarkCoffin = `-- name: UnmarkCoffin :execrows
DELETE
FROM math_center_coffins
WHERE problem_id = $1
`

func (q *Queries) UnmarkCoffin(ctx context.Context, problemID int64) (int64, error) {
	result, err := q.db.Exec(ctx, unmarkCoffin, problemID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
