// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package store

import (
	"context"
	"time"
)

const createStudentNote = `-- name: CreateStudentNote :one
INSERT INTO math_center_student_note (student_user_id, math_center_id, author_user_id, body)
VALUES ($1, $2, $3, $4)
RETURNING id, student_user_id, math_center_id, author_user_id, body, created_at, updated_at
`

type CreateStudentNoteParams struct {
	StudentUserID int64  `json:"student_user_id"`
	MathCenterID  int64  `json:"math_center_id"`
	AuthorUserID  int64  `json:"author_user_id"`
	Body          string `json:"body"`
}

func (q *Queries) CreateStudentNote(ctx context.Context, arg CreateStudentNoteParams) (MathCenterStudentNote, error) {
	row := q.db.QueryRow(ctx, createStudentNote,
		arg.StudentUserID,
		arg.MathCenterID,
		arg.AuthorUserID,
		arg.Body,
	)
	var i MathCenterStudentNote
	err := row.Scan(
		&i.ID,
		&i.StudentUserID,
		&i.MathCenterID,
		&i.AuthorUserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createThreadNote = `-- name: CreateThreadNote :one

INSERT INTO homework_thread_note (thread_id, author_user_id, body)
VALUES ($1, $2, $3)
RETURNING id, thread_id, author_user_id, body, created_at, updated_at
`

type CreateThreadNoteParams struct {
	ThreadID     int64  `json:"thread_id"`
	AuthorUserID int64  `json:"author_user_id"`
	Body         string `json:"body"`
}

// Internal teacher-only comments. Two analogous resources: thread notes
// (anchored to a homework_thread) and student notes (anchored to a student in a
// center). The *Authored variants join users so the handler can return the
// author's display name without an extra lookup.
func (q *Queries) CreateThreadNote(ctx context.Context, arg CreateThreadNoteParams) (HomeworkThreadNote, error) {
	row := q.db.QueryRow(ctx, createThreadNote, arg.ThreadID, arg.AuthorUserID, arg.Body)
	var i HomeworkThreadNote
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.AuthorUserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStudentNote = `-- name: DeleteStudentNote :execrows
DELETE FROM math_center_student_note WHERE id = $1
`

func (q *Queries) DeleteStudentNote(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStudentNote, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteThreadNote = `-- name: DeleteThreadNote :execrows
DELETE FROM homework_thread_note WHERE id = $1
`

func (q *Queries) DeleteThreadNote(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteThreadNote, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStudentNote = `-- name: GetStudentNote :one
SELECT id, student_user_id, math_center_id, author_user_id, body, created_at, updated_at FROM math_center_student_note WHERE id = $1
`

func (q *Queries) GetStudentNote(ctx context.Context, id int64) (MathCenterStudentNote, error) {
	row := q.db.QueryRow(ctx, getStudentNote, id)
	var i MathCenterStudentNote
	err := row.Scan(
		&i.ID,
		&i.StudentUserID,
		&i.MathCenterID,
		&i.AuthorUserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentNoteAuthored = `-- name: GetStudentNoteAuthored :one
SELECT n.id,
       n.student_user_id,
       n.math_center_id,
       n.author_user_id,
       u.first_name AS author_first_name,
       u.last_name  AS author_last_name,
       n.body,
       n.created_at,
       n.updated_at
FROM math_center_student_note n
         JOIN users u ON u.id = n.author_user_id
WHERE n.id = $1
`

type GetStudentNoteAuthoredRow struct {
	ID              int64     `json:"id"`
	StudentUserID   int64     `json:"student_user_id"`
	MathCenterID    int64     `json:"math_center_id"`
	AuthorUserID    int64     `json:"author_user_id"`
	AuthorFirstName string    `json:"author_first_name"`
	AuthorLastName  string    `json:"author_last_name"`
	Body            string    `json:"body"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) GetStudentNoteAuthored(ctx context.Context, id int64) (GetStudentNoteAuthoredRow, error) {
	row := q.db.QueryRow(ctx, getStudentNoteAuthored, id)
	var i GetStudentNoteAuthoredRow
	err := row.Scan(
		&i.ID,
		&i.StudentUserID,
		&i.MathCenterID,
		&i.AuthorUserID,
		&i.AuthorFirstName,
		&i.AuthorLastName,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getThreadNote = `-- name: GetThreadNote :one
SELECT id, thread_id, author_user_id, body, created_at, updated_at FROM homework_thread_note WHERE id = $1
`

func (q *Queries) GetThreadNote(ctx context.Context, id int64) (HomeworkThreadNote, error) {
	row := q.db.QueryRow(ctx, getThreadNote, id)
	var i HomeworkThreadNote
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.AuthorUserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getThreadNoteAuthored = `-- name: GetThreadNoteAuthored :one
SELECT n.id,
       n.thread_id,
       n.author_user_id,
       u.first_name AS author_first_name,
       u.last_name  AS author_last_name,
       n.body,
       n.created_at,
       n.updated_at
FROM homework_thread_note n
         JOIN users u ON u.id = n.author_user_id
WHERE n.id = $1
`

type GetThreadNoteAuthoredRow struct {
	ID              int64     `json:"id"`
	ThreadID        int64     `json:"thread_id"`
	AuthorUserID    int64     `json:"author_user_id"`
	AuthorFirstName string    `json:"author_first_name"`
	AuthorLastName  string    `json:"author_last_name"`
	Body            string    `json:"body"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) GetThreadNoteAuthored(ctx context.Context, id int64) (GetThreadNoteAuthoredRow, error) {
	row := q.db.QueryRow(ctx, getThreadNoteAuthored, id)
	var i GetThreadNoteAuthoredRow
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.AuthorUserID,
		&i.AuthorFirstName,
		&i.AuthorLastName,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStudentNotesAuthored = `-- name: ListStudentNotesAuthored :many
SELECT n.id,
       n.student_user_id,
       n.math_center_id,
       n.author_user_id,
       u.first_name AS author_first_name,
       u.last_name  AS author_last_name,
       n.body,
       n.created_at,
       n.updated_at
FROM math_center_student_note n
         JOIN users u ON u.id = n.author_user_id
WHERE n.student_user_id = $1 AND n.math_center_id = $2
ORDER BY n.created_at ASC, n.id ASC
`

type ListStudentNotesAuthoredParams struct {
	StudentUserID int64 `json:"student_user_id"`
	MathCenterID  int64 `json:"math_center_id"`
}

type ListStudentNotesAuthoredRow struct {
	ID              int64     `json:"id"`
	StudentUserID   int64     `json:"student_user_id"`
	MathCenterID    int64     `json:"math_center_id"`
	AuthorUserID    int64     `json:"author_user_id"`
	AuthorFirstName string    `json:"author_first_name"`
	AuthorLastName  string    `json:"author_last_name"`
	Body            string    `json:"body"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) ListStudentNotesAuthored(ctx context.Context, arg ListStudentNotesAuthoredParams) ([]ListStudentNotesAuthoredRow, error) {
	rows, err := q.db.Query(ctx, listStudentNotesAuthored, arg.StudentUserID, arg.MathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentNotesAuthoredRow{}
	for rows.Next() {
		var i ListStudentNotesAuthoredRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentUserID,
			&i.MathCenterID,
			&i.AuthorUserID,
			&i.AuthorFirstName,
			&i.AuthorLastName,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadNotesAuthored = `-- name: ListThreadNotesAuthored :many
SELECT n.id,
       n.thread_id,
       n.author_user_id,
       u.first_name AS author_first_name,
       u.last_name  AS author_last_name,
       n.body,
       n.created_at,
       n.updated_at
FROM homework_thread_note n
         JOIN users u ON u.id = n.author_user_id
WHERE n.thread_id = $1
ORDER BY n.created_at ASC, n.id ASC
`

type ListThreadNotesAuthoredRow struct {
	ID              int64     `json:"id"`
	ThreadID        int64     `json:"thread_id"`
	AuthorUserID    int64     `json:"author_user_id"`
	AuthorFirstName string    `json:"author_first_name"`
	AuthorLastName  string    `json:"author_last_name"`
	Body            string    `json:"body"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) ListThreadNotesAuthored(ctx context.Context, threadID int64) ([]ListThreadNotesAuthoredRow, error) {
	rows, err := q.db.Query(ctx, listThreadNotesAuthored, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListThreadNotesAuthoredRow{}
	for rows.Next() {
		var i ListThreadNotesAuthoredRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.AuthorUserID,
			&i.AuthorFirstName,
			&i.AuthorLastName,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudentNote = `-- name: UpdateStudentNote :execrows
UPDATE math_center_student_note
SET body = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateStudentNoteParams struct {
	ID   int64  `json:"id"`
	Body string `json:"body"`
}

func (q *Queries) UpdateStudentNote(ctx context.Context, arg UpdateStudentNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStudentNote, arg.ID, arg.Body)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateThreadNote = `-- name: UpdateThreadNote :execrows
UPDATE homework_thread_note
SET body = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateThreadNoteParams struct {
	ID   int64  `json:"id"`
	Body string `json:"body"`
}

func (q *Queries) UpdateThreadNote(ctx context.Context, arg UpdateThreadNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateThreadNote, arg.ID, arg.Body)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
