// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: homework.sql

package store

import (
	"context"
	"time"
)

const appendEvent = `-- name: AppendEvent :one
INSERT INTO homework_thread_event
    (thread_id, event_uuid, kind, actor_user_id, body, verdict, refers_to_event_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, thread_id, event_uuid, kind, actor_user_id, body, verdict, refers_to_event_id, created_at
`

type AppendEventParams struct {
	ThreadID        int64   `json:"thread_id"`
	EventUuid       string  `json:"event_uuid"`
	Kind            string  `json:"kind"`
	ActorUserID     int64   `json:"actor_user_id"`
	Body            string  `json:"body"`
	Verdict         *string `json:"verdict"`
	RefersToEventID *int64  `json:"refers_to_event_id"`
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (HomeworkThreadEvent, error) {
	row := q.db.QueryRow(ctx, appendEvent,
		arg.ThreadID,
		arg.EventUuid,
		arg.Kind,
		arg.ActorUserID,
		arg.Body,
		arg.Verdict,
		arg.RefersToEventID,
	)
	var i HomeworkThreadEvent
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.EventUuid,
		&i.Kind,
		&i.ActorUserID,
		&i.Body,
		&i.Verdict,
		&i.RefersToEventID,
		&i.CreatedAt,
	)
	return i, err
}

const findOrCreateThread = `-- name: FindOrCreateThread :one
INSERT INTO homework_thread (student_user_id, subproblem_id, series_id, math_center_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (student_user_id, subproblem_id) DO UPDATE
    SET updated_at = NOW()
RETURNING id, student_user_id, subproblem_id, series_id, math_center_id, current_status, current_attempt_event_id, current_grade_event_id, last_grader_user_id, claim_holder_user_id, claim_expires_at, created_at, updated_at
`

type FindOrCreateThreadParams struct {
	StudentUserID int64 `json:"student_user_id"`
	SubproblemID  int64 `json:"subproblem_id"`
	SeriesID      int64 `json:"series_id"`
	MathCenterID  int64 `json:"math_center_id"`
}

// INSERT ... ON CONFLICT DO UPDATE always returns a row, regardless of
// whether we created it now or matched an existing one. The DO UPDATE bumps
// updated_at so we can see activity even on no-op upserts.
func (q *Queries) FindOrCreateThread(ctx context.Context, arg FindOrCreateThreadParams) (HomeworkThread, error) {
	row := q.db.QueryRow(ctx, findOrCreateThread,
		arg.StudentUserID,
		arg.SubproblemID,
		arg.SeriesID,
		arg.MathCenterID,
	)
	var i HomeworkThread
	err := row.Scan(
		&i.ID,
		&i.StudentUserID,
		&i.SubproblemID,
		&i.SeriesID,
		&i.MathCenterID,
		&i.CurrentStatus,
		&i.CurrentAttemptEventID,
		&i.CurrentGradeEventID,
		&i.LastGraderUserID,
		&i.ClaimHolderUserID,
		&i.ClaimExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventKind = `-- name: GetEventKind :one
SELECT kind
FROM homework_thread_event
WHERE id = $1
`

func (q *Queries) GetEventKind(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getEventKind, id)
	var kind string
	err := row.Scan(&kind)
	return kind, err
}

const getMostRecentGradedEvent = `-- name: GetMostRecentGradedEvent :one
SELECT id, thread_id, event_uuid, kind, actor_user_id, body, verdict, refers_to_event_id, created_at
FROM homework_thread_event
WHERE thread_id = $1
  AND kind      = 'graded'
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetMostRecentGradedEvent(ctx context.Context, threadID int64) (HomeworkThreadEvent, error) {
	row := q.db.QueryRow(ctx, getMostRecentGradedEvent, threadID)
	var i HomeworkThreadEvent
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.EventUuid,
		&i.Kind,
		&i.ActorUserID,
		&i.Body,
		&i.Verdict,
		&i.RefersToEventID,
		&i.CreatedAt,
	)
	return i, err
}

const getSubproblemContext = `-- name: GetSubproblemContext :one
SELECT sp.id            AS subproblem_id,
       sp.label         AS subproblem_label,
       p.id             AS problem_id,
       p.number         AS problem_number,
       s.id             AS series_id,
       s.math_center_id AS math_center_id,
       s.due_at         AS series_due_at,
       s.published_at   AS series_published_at,
       -- Coffin state, so the submit handler can keep a coffin open past the
       -- series deadline until its solution is released. Per-subproblem now.
       COALESCE(ss.is_coffin, false)::boolean AS is_coffin,
       ss.released_at                         AS coffin_released_at
FROM math_center_subproblems sp
         JOIN math_center_problems p ON p.id = sp.problem_id
         JOIN math_center_series   s ON s.id = p.series_id
         LEFT JOIN math_center_subproblem_solutions ss ON ss.subproblem_id = sp.id
WHERE sp.id = $1
`

type GetSubproblemContextRow struct {
	SubproblemID      int64      `json:"subproblem_id"`
	SubproblemLabel   string     `json:"subproblem_label"`
	ProblemID         int64      `json:"problem_id"`
	ProblemNumber     int32      `json:"problem_number"`
	SeriesID          int64      `json:"series_id"`
	MathCenterID      int64      `json:"math_center_id"`
	SeriesDueAt       time.Time  `json:"series_due_at"`
	SeriesPublishedAt *time.Time `json:"series_published_at"`
	IsCoffin          bool       `json:"is_coffin"`
	CoffinReleasedAt  *time.Time `json:"coffin_released_at"`
}

// One-shot fetch of "what center/series/problem does this subproblem belong
// to", used at the start of every event-creating handler so we don't have to
// chain three queries.
func (q *Queries) GetSubproblemContext(ctx context.Context, id int64) (GetSubproblemContextRow, error) {
	row := q.db.QueryRow(ctx, getSubproblemContext, id)
	var i GetSubproblemContextRow
	err := row.Scan(
		&i.SubproblemID,
		&i.SubproblemLabel,
		&i.ProblemID,
		&i.ProblemNumber,
		&i.SeriesID,
		&i.MathCenterID,
		&i.SeriesDueAt,
		&i.SeriesPublishedAt,
		&i.IsCoffin,
		&i.CoffinReleasedAt,
	)
	return i, err
}

const getThread = `-- name: GetThread :one
SELECT id, student_user_id, subproblem_id, series_id, math_center_id, current_status, current_attempt_event_id, current_grade_event_id, last_grader_user_id, claim_holder_user_id, claim_expires_at, created_at, updated_at
FROM homework_thread
WHERE id = $1
`

func (q *Queries) GetThread(ctx context.Context, id int64) (HomeworkThread, error) {
	row := q.db.QueryRow(ctx, getThread, id)
	var i HomeworkThread
	err := row.Scan(
		&i.ID,
		&i.StudentUserID,
		&i.SubproblemID,
		&i.SeriesID,
		&i.MathCenterID,
		&i.CurrentStatus,
		&i.CurrentAttemptEventID,
		&i.CurrentGradeEventID,
		&i.LastGraderUserID,
		&i.ClaimHolderUserID,
		&i.ClaimExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getThreadByStudentAndSubproblem = `-- name: GetThreadByStudentAndSubproblem :one
SELECT id, student_user_id, subproblem_id, series_id, math_center_id, current_status, current_attempt_event_id, current_grade_event_id, last_grader_user_id, claim_holder_user_id, claim_expires_at, created_at, updated_at
FROM homework_thread
WHERE student_user_id = $1
  AND subproblem_id   = $2
`

type GetThreadByStudentAndSubproblemParams struct {
	StudentUserID int64 `json:"student_user_id"`
	SubproblemID  int64 `json:"subproblem_id"`
}

func (q *Queries) GetThreadByStudentAndSubproblem(ctx context.Context, arg GetThreadByStudentAndSubproblemParams) (HomeworkThread, error) {
	row := q.db.QueryRow(ctx, getThreadByStudentAndSubproblem, arg.StudentUserID, arg.SubproblemID)
	var i HomeworkThread
	err := row.Scan(
		&i.ID,
		&i.StudentUserID,
		&i.SubproblemID,
		&i.SeriesID,
		&i.MathCenterID,
		&i.CurrentStatus,
		&i.CurrentAttemptEventID,
		&i.CurrentGradeEventID,
		&i.LastGraderUserID,
		&i.ClaimHolderUserID,
		&i.ClaimExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const graderStatsForCenter = `-- name: GraderStatsForCenter :one
SELECT
    COUNT(*) FILTER (
        WHERE current_status IN ('submitted','appealed')
          AND (claim_holder_user_id IS NULL OR claim_expires_at < NOW())
    )::bigint AS pending_count,
    COUNT(*) FILTER (
        WHERE current_status IN ('submitted','appealed')
          AND claim_holder_user_id = $2::bigint
          AND claim_expires_at >= NOW()
    )::bigint AS my_claimed_count,
    COUNT(*) FILTER (
        WHERE current_status = 'appealed'
          AND last_grader_user_id = $2::bigint
    )::bigint AS my_appeals_count
FROM homework_thread
WHERE math_center_id = $1
`

type GraderStatsForCenterParams struct {
	MathCenterID int64 `json:"math_center_id"`
	CallerUserID int64 `json:"caller_user_id"`
}

type GraderStatsForCenterRow struct {
	PendingCount   int64 `json:"pending_count"`
	MyClaimedCount int64 `json:"my_claimed_count"`
	MyAppealsCount int64 `json:"my_appeals_count"`
}

// {pending, my_claimed, my_appeals} for the grader dashboard.
func (q *Queries) GraderStatsForCenter(ctx context.Context, arg GraderStatsForCenterParams) (GraderStatsForCenterRow, error) {
	row := q.db.QueryRow(ctx, graderStatsForCenter, arg.MathCenterID, arg.CallerUserID)
	var i GraderStatsForCenterRow
	err := row.Scan(&i.PendingCount, &i.MyClaimedCount, &i.MyAppealsCount)
	return i, err
}

const heartbeatClaim = `-- name: HeartbeatClaim :execrows
UPDATE homework_thread
SET claim_expires_at = NOW() + INTERVAL '15 minutes',
    updated_at       = NOW()
WHERE id = $1::bigint
  AND claim_holder_user_id = $2::bigint
  AND claim_expires_at > NOW()
`

type HeartbeatClaimParams struct {
	ID           int64 `json:"id"`
	GraderUserID int64 `json:"grader_user_id"`
}

func (q *Queries) HeartbeatClaim(ctx context.Context, arg HeartbeatClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatClaim, arg.ID, arg.GraderUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertEventPhoto = `-- name: InsertEventPhoto :exec
INSERT INTO homework_thread_event_photo (event_id, idx, object_key, size_bytes, content_type)
VALUES ($1, $2, $3, $4, $5)
`

type InsertEventPhotoParams struct {
	EventID     int64  `json:"event_id"`
	Idx         int32  `json:"idx"`
	ObjectKey   string `json:"object_key"`
	SizeBytes   int64  `json:"size_bytes"`
	ContentType string `json:"content_type"`
}

func (q *Queries) InsertEventPhoto(ctx context.Context, arg InsertEventPhotoParams) error {
	_, err := q.db.Exec(ctx, insertEventPhoto,
		arg.EventID,
		arg.Idx,
		arg.ObjectKey,
		arg.SizeBytes,
		arg.ContentType,
	)
	return err
}

const listEventPhotosForEvents = `-- name: ListEventPhotosForEvents :many
SELECT event_id, idx, object_key, size_bytes, content_type, created_at
FROM homework_thread_event_photo
WHERE event_id = ANY ($1::bigint[])
ORDER BY event_id ASC, idx ASC
`

func (q *Queries) ListEventPhotosForEvents(ctx context.Context, eventIds []int64) ([]HomeworkThreadEventPhoto, error) {
	rows, err := q.db.Query(ctx, listEventPhotosForEvents, eventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HomeworkThreadEventPhoto{}
	for rows.Next() {
		var i HomeworkThreadEventPhoto
		if err := rows.Scan(
			&i.EventID,
			&i.Idx,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.ContentType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGraderQueueForSeries = `-- name: ListGraderQueueForSeries :many
SELECT t.id              AS id,
       t.student_user_id AS student_user_id,
       t.subproblem_id   AS subproblem_id,
       t.series_id       AS series_id,
       t.math_center_id  AS math_center_id,
       t.current_status  AS current_status,
       t.last_grader_user_id AS last_grader_user_id,
       t.claim_holder_user_id AS claim_holder_user_id,
       t.claim_expires_at AS claim_expires_at,
       t.updated_at      AS updated_at,
       u.first_name      AS student_first_name,
       u.middle_name     AS student_middle_name,
       u.last_name       AS student_last_name,
       sp.label          AS subproblem_label,
       p.number          AS problem_number
FROM homework_thread t
         JOIN users u                       ON u.id  = t.student_user_id
         JOIN math_center_subproblems sp    ON sp.id = t.subproblem_id
         JOIN math_center_problems p        ON p.id  = sp.problem_id
WHERE t.series_id = $1
  AND t.current_status IN ('submitted', 'appealed')
  AND (t.claim_holder_user_id IS NULL
       OR t.claim_expires_at < NOW()
       OR t.claim_holder_user_id = $2::bigint)
  AND (NOT $3::bool
       OR t.last_grader_user_id = $2::bigint
       OR (t.claim_holder_user_id = $2::bigint
           AND t.claim_expires_at > NOW()))
ORDER BY t.current_status ASC,
         t.updated_at ASC
`

type ListGraderQueueForSeriesParams struct {
	SeriesID     int64 `json:"series_id"`
	CallerUserID int64 `json:"caller_user_id"`
	MineOnly     bool  `json:"mine_only"`
}

type ListGraderQueueForSeriesRow struct {
	ID                int64      `json:"id"`
	StudentUserID     int64      `json:"student_user_id"`
	SubproblemID      int64      `json:"subproblem_id"`
	SeriesID          int64      `json:"series_id"`
	MathCenterID      int64      `json:"math_center_id"`
	CurrentStatus     string     `json:"current_status"`
	LastGraderUserID  *int64     `json:"last_grader_user_id"`
	ClaimHolderUserID *int64     `json:"claim_holder_user_id"`
	ClaimExpiresAt    *time.Time `json:"claim_expires_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	StudentFirstName  string     `json:"student_first_name"`
	StudentMiddleName *string    `json:"student_middle_name"`
	StudentLastName   string     `json:"student_last_name"`
	SubproblemLabel   string     `json:"subproblem_label"`
	ProblemNumber     int32      `json:"problem_number"`
}

// Items needing grading: 'submitted' or 'appealed', not locked by someone
// else (a stale lock counts as available). mine=true restricts to "my work":
// threads I currently hold a live claim on, OR where I was the most recent
// grader (appeal stickiness) — so a grader can find what they've taken on.
func (q *Queries) ListGraderQueueForSeries(ctx context.Context, arg ListGraderQueueForSeriesParams) ([]ListGraderQueueForSeriesRow, error) {
	rows, err := q.db.Query(ctx, listGraderQueueForSeries, arg.SeriesID, arg.CallerUserID, arg.MineOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGraderQueueForSeriesRow{}
	for rows.Next() {
		var i ListGraderQueueForSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentUserID,
			&i.SubproblemID,
			&i.SeriesID,
			&i.MathCenterID,
			&i.CurrentStatus,
			&i.LastGraderUserID,
			&i.ClaimHolderUserID,
			&i.ClaimExpiresAt,
			&i.UpdatedAt,
			&i.StudentFirstName,
			&i.StudentMiddleName,
			&i.StudentLastName,
			&i.SubproblemLabel,
			&i.ProblemNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadEvents = `-- name: ListThreadEvents :many
SELECT id, thread_id, event_uuid, kind, actor_user_id, body, verdict, refers_to_event_id, created_at
FROM homework_thread_event
WHERE thread_id = $1
ORDER BY id ASC
`

func (q *Queries) ListThreadEvents(ctx context.Context, threadID int64) ([]HomeworkThreadEvent, error) {
	rows, err := q.db.Query(ctx, listThreadEvents, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HomeworkThreadEvent{}
	for rows.Next() {
		var i HomeworkThreadEvent
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.EventUuid,
			&i.Kind,
			&i.ActorUserID,
			&i.Body,
			&i.Verdict,
			&i.RefersToEventID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseClaim = `-- name: ReleaseClaim :execrows
UPDATE homework_thread
SET claim_holder_user_id = NULL,
    claim_expires_at     = NULL,
    updated_at           = NOW()
WHERE id = $1::bigint
  AND claim_holder_user_id = $2::bigint
`

type ReleaseClaimParams struct {
	ID           int64 `json:"id"`
	GraderUserID int64 `json:"grader_user_id"`
}

func (q *Queries) ReleaseClaim(ctx context.Context, arg ReleaseClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseClaim, arg.ID, arg.GraderUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const seriesProblemStats = `-- name: SeriesProblemStats :many
SELECT
    mcs.user_id                            AS student_user_id,
    p.id                                   AS problem_id,
    p.number                               AS problem_number,
    sp.id                                  AS subproblem_id,
    sp.label                               AS subproblem_label,
    COALESCE(t.current_status, 'ungraded') AS current_status
FROM math_center_subproblems sp
         JOIN math_center_problems p ON p.id = sp.problem_id
         LEFT JOIN math_center_groups g
                   ON g.math_center_id = (SELECT s.math_center_id FROM math_center_series s WHERE s.id = $1)
         LEFT JOIN math_center_students mcs ON mcs.group_id = g.id
         LEFT JOIN homework_thread t
                   ON t.student_user_id = mcs.user_id
                  AND t.subproblem_id   = sp.id
WHERE p.series_id = $1
ORDER BY p.number ASC, p.id ASC, sp.label ASC, mcs.user_id ASC NULLS LAST
`

type SeriesProblemStatsRow struct {
	StudentUserID   *int64 `json:"student_user_id"`
	ProblemID       int64  `json:"problem_id"`
	ProblemNumber   int32  `json:"problem_number"`
	SubproblemID    int64  `json:"subproblem_id"`
	SubproblemLabel string `json:"subproblem_label"`
	CurrentStatus   string `json:"current_status"`
}

// One row per (subproblem × roster student) for a whole series. The series's
// subproblems are the spine, so EVERY subproblem appears even before anyone is
// enrolled: the roster (students of a group in the series's center) is
// LEFT JOINed, yielding a single placeholder row with student_user_id = NULL
// when the roster is empty. Each student's thread is LEFT JOINed so untouched
// subproblems read 'ungraded'. The handler tallies each subproblem into its own
// line (1а, 1б are distinct); placeholder rows register the subproblem with
// zero counts. Roster scoping mirrors TeacherSeriesGrid.
func (q *Queries) SeriesProblemStats(ctx context.Context, id int64) ([]SeriesProblemStatsRow, error) {
	rows, err := q.db.Query(ctx, seriesProblemStats, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SeriesProblemStatsRow{}
	for rows.Next() {
		var i SeriesProblemStatsRow
		if err := rows.Scan(
			&i.StudentUserID,
			&i.ProblemID,
			&i.ProblemNumber,
			&i.SubproblemID,
			&i.SubproblemLabel,
			&i.CurrentStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const studentSeriesCounts = `-- name: StudentSeriesCounts :one
SELECT
    COUNT(*) FILTER (
        WHERE COALESCE(t.current_status, 'ungraded') = 'accepted'
    )::bigint AS accepted_count,
    COUNT(*) FILTER (
        WHERE COALESCE(t.current_status, 'ungraded') = 'rejected'
    )::bigint AS rejected_count,
    COUNT(*) FILTER (
        WHERE COALESCE(t.current_status, 'ungraded') IN ('ungraded','submitted','appealed')
    )::bigint AS pending_count
FROM math_center_subproblems sp
         JOIN math_center_problems p ON p.id = sp.problem_id
         LEFT JOIN homework_thread t
                   ON t.subproblem_id   = sp.id
                  AND t.student_user_id = $2::bigint
WHERE p.series_id = $1
`

type StudentSeriesCountsParams struct {
	SeriesID      int64 `json:"series_id"`
	StudentUserID int64 `json:"student_user_id"`
}

type StudentSeriesCountsRow struct {
	AcceptedCount int64 `json:"accepted_count"`
	RejectedCount int64 `json:"rejected_count"`
	PendingCount  int64 `json:"pending_count"`
}

// One-row summary: accepted / rejected / pending. Pending lumps 'ungraded',
// 'submitted', 'appealed' together (anything the student can't yet call done).
func (q *Queries) StudentSeriesCounts(ctx context.Context, arg StudentSeriesCountsParams) (StudentSeriesCountsRow, error) {
	row := q.db.QueryRow(ctx, studentSeriesCounts, arg.SeriesID, arg.StudentUserID)
	var i StudentSeriesCountsRow
	err := row.Scan(&i.AcceptedCount, &i.RejectedCount, &i.PendingCount)
	return i, err
}

const studentSeriesRollup = `-- name: StudentSeriesRollup :many
SELECT sp.id                                  AS subproblem_id,
       sp.label                               AS subproblem_label,
       p.id                                   AS problem_id,
       p.number                               AS problem_number,
       COALESCE(t.id, 0)::bigint              AS thread_id,
       COALESCE(t.current_status, 'ungraded') AS current_status,
       -- Privacy-safe "a grader has claimed this" flag: lets the student see
       -- "На проверке" vs "В очереди" without exposing the grader's identity.
       (t.claim_holder_user_id IS NOT NULL
            AND t.claim_expires_at > now())::boolean AS being_graded
FROM math_center_subproblems sp
         JOIN math_center_problems p ON p.id = sp.problem_id
         LEFT JOIN homework_thread t
                   ON t.subproblem_id   = sp.id
                  AND t.student_user_id = $2::bigint
WHERE p.series_id = $1
ORDER BY p.number ASC, sp.label ASC
`

type StudentSeriesRollupParams struct {
	SeriesID      int64 `json:"series_id"`
	StudentUserID int64 `json:"student_user_id"`
}

type StudentSeriesRollupRow struct {
	SubproblemID    int64  `json:"subproblem_id"`
	SubproblemLabel string `json:"subproblem_label"`
	ProblemID       int64  `json:"problem_id"`
	ProblemNumber   int32  `json:"problem_number"`
	ThreadID        int64  `json:"thread_id"`
	CurrentStatus   string `json:"current_status"`
	BeingGraded     bool   `json:"being_graded"`
}

// Per-subproblem status grid for one student in one series. The LEFT JOIN
// means subproblems the student hasn't touched still appear, with
// status='ungraded'.
func (q *Queries) StudentSeriesRollup(ctx context.Context, arg StudentSeriesRollupParams) ([]StudentSeriesRollupRow, error) {
	rows, err := q.db.Query(ctx, studentSeriesRollup, arg.SeriesID, arg.StudentUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentSeriesRollupRow{}
	for rows.Next() {
		var i StudentSeriesRollupRow
		if err := rows.Scan(
			&i.SubproblemID,
			&i.SubproblemLabel,
			&i.ProblemID,
			&i.ProblemNumber,
			&i.ThreadID,
			&i.CurrentStatus,
			&i.BeingGraded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const teacherCenterGrid = `-- name: TeacherCenterGrid :many
SELECT
    s.id                                   AS series_id,
    s.number                               AS series_number,
    s.name                                 AS series_name,
    s.due_at                               AS series_due_at,
    mcs.user_id                            AS student_user_id,
    u.first_name                           AS student_first_name,
    u.middle_name                          AS student_middle_name,
    u.last_name                            AS student_last_name,
    g.id                                   AS group_id,
    g.name                                 AS group_name,
    sp.id                                  AS subproblem_id,
    sp.label                               AS subproblem_label,
    p.id                                   AS problem_id,
    p.number                               AS problem_number,
    COALESCE(ss.is_coffin, false)::boolean AS is_coffin,
    ss.released_at                         AS coffin_released_at,
    COALESCE(t.id, 0)::bigint              AS thread_id,
    COALESCE(t.current_status, 'ungraded') AS current_status,
    t.last_grader_user_id                  AS last_grader_user_id,
    gu.first_name                          AS grader_first_name,
    gu.last_name                           AS grader_last_name,
    t.claim_holder_user_id                 AS claim_holder_user_id,
    t.claim_expires_at                     AS claim_expires_at
FROM math_center_students mcs
         JOIN users u                       ON u.id = mcs.user_id
         JOIN math_center_groups g          ON g.id = mcs.group_id
         JOIN math_center_series s          ON s.math_center_id = g.math_center_id
         JOIN math_center_problems p        ON p.series_id = s.id
         JOIN math_center_subproblems sp    ON sp.problem_id = p.id
         LEFT JOIN math_center_subproblem_solutions ss ON ss.subproblem_id = sp.id
         LEFT JOIN homework_thread t
                   ON t.student_user_id = mcs.user_id
                  AND t.subproblem_id   = sp.id
         LEFT JOIN users gu                 ON gu.id = t.last_grader_user_id
WHERE g.math_center_id = $1
ORDER BY g.name ASC, u.last_name ASC, u.first_name ASC, s.number ASC, p.number ASC, sp.label ASC
`

type TeacherCenterGridRow struct {
	SeriesID          int64      `json:"series_id"`
	SeriesNumber      int32      `json:"series_number"`
	SeriesName        string     `json:"series_name"`
	SeriesDueAt       time.Time  `json:"series_due_at"`
	StudentUserID     int64      `json:"student_user_id"`
	StudentFirstName  string     `json:"student_first_name"`
	StudentMiddleName *string    `json:"student_middle_name"`
	StudentLastName   string     `json:"student_last_name"`
	GroupID           int64      `json:"group_id"`
	GroupName         string     `json:"group_name"`
	SubproblemID      int64      `json:"subproblem_id"`
	SubproblemLabel   string     `json:"subproblem_label"`
	ProblemID         int64      `json:"problem_id"`
	ProblemNumber     int32      `json:"problem_number"`
	IsCoffin          bool       `json:"is_coffin"`
	CoffinReleasedAt  *time.Time `json:"coffin_released_at"`
	ThreadID          int64      `json:"thread_id"`
	CurrentStatus     string     `json:"current_status"`
	LastGraderUserID  *int64     `json:"last_grader_user_id"`
	GraderFirstName   *string    `json:"grader_first_name"`
	GraderLastName    *string    `json:"grader_last_name"`
	ClaimHolderUserID *int64     `json:"claim_holder_user_id"`
	ClaimExpiresAt    *time.Time `json:"claim_expires_at"`
}

// The "all series for this center, every student" matrix used by the
// teacher spreadsheet. Same shape as TeacherSeriesGrid but spans every
// math_center_series in the center, so the frontend can render one
// side-scrolling table across all psets and keep grouping/sort stable.
func (q *Queries) TeacherCenterGrid(ctx context.Context, mathCenterID int64) ([]TeacherCenterGridRow, error) {
	rows, err := q.db.Query(ctx, teacherCenterGrid, mathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeacherCenterGridRow{}
	for rows.Next() {
		var i TeacherCenterGridRow
		if err := rows.Scan(
			&i.SeriesID,
			&i.SeriesNumber,
			&i.SeriesName,
			&i.SeriesDueAt,
			&i.StudentUserID,
			&i.StudentFirstName,
			&i.StudentMiddleName,
			&i.StudentLastName,
			&i.GroupID,
			&i.GroupName,
			&i.SubproblemID,
			&i.SubproblemLabel,
			&i.ProblemID,
			&i.ProblemNumber,
			&i.IsCoffin,
			&i.CoffinReleasedAt,
			&i.ThreadID,
			&i.CurrentStatus,
			&i.LastGraderUserID,
			&i.GraderFirstName,
			&i.GraderLastName,
			&i.ClaimHolderUserID,
			&i.ClaimExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const teacherSeriesGrid = `-- name: TeacherSeriesGrid :many
SELECT
    mcs.user_id                            AS student_user_id,
    u.first_name                           AS student_first_name,
    u.middle_name                          AS student_middle_name,
    u.last_name                            AS student_last_name,
    g.id                                   AS group_id,
    g.name                                 AS group_name,
    sp.id                                  AS subproblem_id,
    sp.label                               AS subproblem_label,
    p.id                                   AS problem_id,
    p.number                               AS problem_number,
    COALESCE(ss.is_coffin, false)::boolean AS is_coffin,
    ss.released_at                         AS coffin_released_at,
    COALESCE(t.id, 0)::bigint              AS thread_id,
    COALESCE(t.current_status, 'ungraded') AS current_status,
    t.last_grader_user_id                  AS last_grader_user_id,
    t.claim_holder_user_id                 AS claim_holder_user_id,
    t.claim_expires_at                     AS claim_expires_at,
    t.updated_at                           AS thread_updated_at
FROM math_center_students mcs
         JOIN users u  ON u.id  = mcs.user_id
         JOIN math_center_groups g ON g.id = mcs.group_id
         CROSS JOIN math_center_subproblems sp
         JOIN math_center_problems p  ON p.id  = sp.problem_id
         LEFT JOIN math_center_subproblem_solutions ss ON ss.subproblem_id = sp.id
         LEFT JOIN homework_thread t
                   ON t.student_user_id = mcs.user_id
                  AND t.subproblem_id   = sp.id
WHERE g.math_center_id = (SELECT s.math_center_id FROM math_center_series s WHERE s.id = $1)
  AND p.series_id = $1
ORDER BY g.name ASC, u.last_name ASC, u.first_name ASC, p.number ASC, sp.label ASC
`

type TeacherSeriesGridRow struct {
	StudentUserID     int64      `json:"student_user_id"`
	StudentFirstName  string     `json:"student_first_name"`
	StudentMiddleName *string    `json:"student_middle_name"`
	StudentLastName   string     `json:"student_last_name"`
	GroupID           int64      `json:"group_id"`
	GroupName         string     `json:"group_name"`
	SubproblemID      int64      `json:"subproblem_id"`
	SubproblemLabel   string     `json:"subproblem_label"`
	ProblemID         int64      `json:"problem_id"`
	ProblemNumber     int32      `json:"problem_number"`
	IsCoffin          bool       `json:"is_coffin"`
	CoffinReleasedAt  *time.Time `json:"coffin_released_at"`
	ThreadID          int64      `json:"thread_id"`
	CurrentStatus     string     `json:"current_status"`
	LastGraderUserID  *int64     `json:"last_grader_user_id"`
	ClaimHolderUserID *int64     `json:"claim_holder_user_id"`
	ClaimExpiresAt    *time.Time `json:"claim_expires_at"`
	ThreadUpdatedAt   *time.Time `json:"thread_updated_at"`
}

// The full (student × subproblem) matrix for one series. Used by the
// teacher spreadsheet view: every student of the series's math center is
// crossed with every subproblem of the series, with the LEFT JOIN filling
// in thread state where it exists (and 'ungraded' / null FKs where it
// doesn't yet). Rows ordered for stable spreadsheet rendering.
func (q *Queries) TeacherSeriesGrid(ctx context.Context, id int64) ([]TeacherSeriesGridRow, error) {
	rows, err := q.db.Query(ctx, teacherSeriesGrid, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeacherSeriesGridRow{}
	for rows.Next() {
		var i TeacherSeriesGridRow
		if err := rows.Scan(
			&i.StudentUserID,
			&i.StudentFirstName,
			&i.StudentMiddleName,
			&i.StudentLastName,
			&i.GroupID,
			&i.GroupName,
			&i.SubproblemID,
			&i.SubproblemLabel,
			&i.ProblemID,
			&i.ProblemNumber,
			&i.IsCoffin,
			&i.CoffinReleasedAt,
			&i.ThreadID,
			&i.CurrentStatus,
			&i.LastGraderUserID,
			&i.ClaimHolderUserID,
			&i.ClaimExpiresAt,
			&i.ThreadUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryClaim = `-- name: TryClaim :one
UPDATE homework_thread
SET claim_holder_user_id = $1::bigint,
    claim_expires_at     = NOW() + INTERVAL '15 minutes',
    updated_at           = NOW()
WHERE id = $2::bigint
  AND (claim_holder_user_id IS NULL
       OR claim_expires_at < NOW()
       OR claim_holder_user_id = $1::bigint)
RETURNING id, student_user_id, subproblem_id, series_id, math_center_id, current_status, current_attempt_event_id, current_grade_event_id, last_grader_user_id, claim_holder_user_id, claim_expires_at, created_at, updated_at
`

type TryClaimParams struct {
	GraderUserID int64 `json:"grader_user_id"`
	ID           int64 `json:"id"`
}

// Returns the row when the claim is granted (no live holder, or the caller
// already holds it). Returns no rows when someone else holds a live claim.
func (q *Queries) TryClaim(ctx context.Context, arg TryClaimParams) (HomeworkThread, error) {
	row := q.db.QueryRow(ctx, tryClaim, arg.GraderUserID, arg.ID)
	var i HomeworkThread
	err := row.Scan(
		&i.ID,
		&i.StudentUserID,
		&i.SubproblemID,
		&i.SeriesID,
		&i.MathCenterID,
		&i.CurrentStatus,
		&i.CurrentAttemptEventID,
		&i.CurrentGradeEventID,
		&i.LastGraderUserID,
		&i.ClaimHolderUserID,
		&i.ClaimExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateThreadAfterAppeal = `-- name: UpdateThreadAfterAppeal :exec
UPDATE homework_thread
SET current_status           = 'appealed',
    current_attempt_event_id = $2,
    updated_at               = NOW()
WHERE id = $1
`

type UpdateThreadAfterAppealParams struct {
	ID                    int64  `json:"id"`
	CurrentAttemptEventID *int64 `json:"current_attempt_event_id"`
}

func (q *Queries) UpdateThreadAfterAppeal(ctx context.Context, arg UpdateThreadAfterAppealParams) error {
	_, err := q.db.Exec(ctx, updateThreadAfterAppeal, arg.ID, arg.CurrentAttemptEventID)
	return err
}

const updateThreadAfterGrade = `-- name: UpdateThreadAfterGrade :execrows
UPDATE homework_thread
SET current_status         = CASE
                                 WHEN $1::text = 'accepted' THEN 'accepted'
                                 ELSE 'rejected'
                             END,
    current_grade_event_id = $2::bigint,
    last_grader_user_id    = $3::bigint,
    claim_holder_user_id   = NULL,
    claim_expires_at       = NULL,
    updated_at             = NOW()
WHERE id = $4::bigint
  AND claim_holder_user_id = $3::bigint
  AND claim_expires_at > NOW()
`

type UpdateThreadAfterGradeParams struct {
	Verdict      string `json:"verdict"`
	GradeEventID int64  `json:"grade_event_id"`
	GraderUserID int64  `json:"grader_user_id"`
	ID           int64  `json:"id"`
}

// One statement does all four things atomically: set new status from
// verdict, point the cache at the new grade event, record the grader for
// appeal stickiness, AND clear the claim. The WHERE re-checks claim
// ownership so a slow grader whose lease expired can't overwrite someone
// else's claim. Caller inspects affected-row count to detect contention.
func (q *Queries) UpdateThreadAfterGrade(ctx context.Context, arg UpdateThreadAfterGradeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateThreadAfterGrade,
		arg.Verdict,
		arg.GradeEventID,
		arg.GraderUserID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateThreadAfterRetract = `-- name: UpdateThreadAfterRetract :exec
UPDATE homework_thread
SET current_status         = $2,
    current_grade_event_id = NULL,
    updated_at             = NOW()
WHERE id = $1
`

type UpdateThreadAfterRetractParams struct {
	ID            int64  `json:"id"`
	CurrentStatus string `json:"current_status"`
}

// After a retraction the thread reverts to whatever its most recent attempt
// event was: 'submitted' for an original submission, 'appealed' for an
// appeal. The handler passes that rollback status in $2.
func (q *Queries) UpdateThreadAfterRetract(ctx context.Context, arg UpdateThreadAfterRetractParams) error {
	_, err := q.db.Exec(ctx, updateThreadAfterRetract, arg.ID, arg.CurrentStatus)
	return err
}

const updateThreadAfterSubmit = `-- name: UpdateThreadAfterSubmit :exec
UPDATE homework_thread
SET current_status           = 'submitted',
    current_attempt_event_id = $2,
    updated_at               = NOW()
WHERE id = $1
`

type UpdateThreadAfterSubmitParams struct {
	ID                    int64  `json:"id"`
	CurrentAttemptEventID *int64 `json:"current_attempt_event_id"`
}

func (q *Queries) UpdateThreadAfterSubmit(ctx context.Context, arg UpdateThreadAfterSubmitParams) error {
	_, err := q.db.Exec(ctx, updateThreadAfterSubmit, arg.ID, arg.CurrentAttemptEventID)
	return err
}
