// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitation_tokens.sql

package store

import (
	"context"
	"encoding/json"
	"time"
)

const createInvitationToken = `-- name: CreateInvitationToken :one
INSERT INTO invitation_tokens (token, description, max_uses, expires_at, preset, math_center_id)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, token, description, max_uses, expires_at, created_at, preset, math_center_id
`

type CreateInvitationTokenParams struct {
	Token        string          `json:"token"`
	Description  string          `json:"description"`
	MaxUses      int32           `json:"max_uses"`
	ExpiresAt    time.Time       `json:"expires_at"`
	Preset       json.RawMessage `json:"preset"`
	MathCenterID *int64          `json:"math_center_id"`
}

func (q *Queries) CreateInvitationToken(ctx context.Context, arg CreateInvitationTokenParams) (InvitationToken, error) {
	row := q.db.QueryRow(ctx, createInvitationToken,
		arg.Token,
		arg.Description,
		arg.MaxUses,
		arg.ExpiresAt,
		arg.Preset,
		arg.MathCenterID,
	)
	var i InvitationToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Description,
		&i.MaxUses,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Preset,
		&i.MathCenterID,
	)
	return i, err
}

const getInvitationTokenByID = `-- name: GetInvitationTokenByID :one
SELECT id, token, description, max_uses, expires_at, created_at, preset, math_center_id
FROM invitation_tokens
WHERE id = $1
`

func (q *Queries) GetInvitationTokenByID(ctx context.Context, id int64) (InvitationToken, error) {
	row := q.db.QueryRow(ctx, getInvitationTokenByID, id)
	var i InvitationToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Description,
		&i.MaxUses,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Preset,
		&i.MathCenterID,
	)
	return i, err
}

const getInvitationTokenByValue = `-- name: GetInvitationTokenByValue :one
SELECT id, token, description, max_uses, expires_at, created_at, preset, math_center_id
FROM invitation_tokens
WHERE token = $1
`

func (q *Queries) GetInvitationTokenByValue(ctx context.Context, token string) (InvitationToken, error) {
	row := q.db.QueryRow(ctx, getInvitationTokenByValue, token)
	var i InvitationToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Description,
		&i.MaxUses,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Preset,
		&i.MathCenterID,
	)
	return i, err
}

const getInvitationTokenByValueForUpdate = `-- name: GetInvitationTokenByValueForUpdate :one
SELECT id, token, description, max_uses, expires_at, created_at, preset, math_center_id
FROM invitation_tokens
WHERE token = $1 FOR UPDATE
`

func (q *Queries) GetInvitationTokenByValueForUpdate(ctx context.Context, token string) (InvitationToken, error) {
	row := q.db.QueryRow(ctx, getInvitationTokenByValueForUpdate, token)
	var i InvitationToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Description,
		&i.MaxUses,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Preset,
		&i.MathCenterID,
	)
	return i, err
}

const listInvitationTokens = `-- name: ListInvitationTokens :many
SELECT id, token, description, max_uses, expires_at, created_at, preset, math_center_id
FROM invitation_tokens
ORDER BY created_at DESC
`

func (q *Queries) ListInvitationTokens(ctx context.Context) ([]InvitationToken, error) {
	rows, err := q.db.Query(ctx, listInvitationTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvitationToken{}
	for rows.Next() {
		var i InvitationToken
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.Description,
			&i.MaxUses,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.Preset,
			&i.MathCenterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitationTokensForCenter = `-- name: ListInvitationTokensForCenter :many
SELECT id, token, description, max_uses, expires_at, created_at, preset, math_center_id
FROM invitation_tokens
WHERE math_center_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListInvitationTokensForCenter(ctx context.Context, mathCenterID *int64) ([]InvitationToken, error) {
	rows, err := q.db.Query(ctx, listInvitationTokensForCenter, mathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvitationToken{}
	for rows.Next() {
		var i InvitationToken
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.Description,
			&i.MaxUses,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.Preset,
			&i.MathCenterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvitationTokenByID = `-- name: RevokeInvitationTokenByID :execrows
UPDATE invitation_tokens
SET expires_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeInvitationTokenByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvitationTokenByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeInvitationTokenByValue = `-- name: RevokeInvitationTokenByValue :execrows
UPDATE invitation_tokens
SET expires_at = NOW()
WHERE token = $1
`

func (q *Queries) RevokeInvitationTokenByValue(ctx context.Context, token string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvitationTokenByValue, token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
