// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: math_center_terms.sql

package store

import (
	"context"
)

const archiveActiveTermsForCenter = `-- name: ArchiveActiveTermsForCenter :exec
UPDATE math_center_terms
SET is_active = FALSE,
    archived_at = NOW()
WHERE math_center_id = $1
  AND is_active = TRUE
`

func (q *Queries) ArchiveActiveTermsForCenter(ctx context.Context, mathCenterID int64) error {
	_, err := q.db.Exec(ctx, archiveActiveTermsForCenter, mathCenterID)
	return err
}

const copyGroupsToTerm = `-- name: CopyGroupsToTerm :exec
INSERT INTO math_center_groups (math_center_id, term_id, name)
SELECT g.math_center_id, $2, g.name
FROM math_center_groups g
WHERE g.term_id = $1
ORDER BY g.name ASC
`

type CopyGroupsToTermParams struct {
	TermID   int64 `json:"term_id"`
	TermID_2 int64 `json:"term_id_2"`
}

func (q *Queries) CopyGroupsToTerm(ctx context.Context, arg CopyGroupsToTermParams) error {
	_, err := q.db.Exec(ctx, copyGroupsToTerm, arg.TermID, arg.TermID_2)
	return err
}

const createMathCenterGroupForTerm = `-- name: CreateMathCenterGroupForTerm :one
INSERT INTO math_center_groups (math_center_id, term_id, name)
SELECT t.math_center_id, t.id, $2
FROM math_center_terms t
WHERE t.id = $1
RETURNING id, math_center_id, name, created_at, term_id
`

type CreateMathCenterGroupForTermParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreateMathCenterGroupForTerm(ctx context.Context, arg CreateMathCenterGroupForTermParams) (MathCenterGroup, error) {
	row := q.db.QueryRow(ctx, createMathCenterGroupForTerm, arg.ID, arg.Name)
	var i MathCenterGroup
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.Name,
		&i.CreatedAt,
		&i.TermID,
	)
	return i, err
}

const createMathCenterTerm = `-- name: CreateMathCenterTerm :one
INSERT INTO math_center_terms (math_center_id, kind, grade, is_active)
VALUES ($1, $2, $3, TRUE)
RETURNING id, math_center_id, kind, grade, is_active, created_at, archived_at
`

type CreateMathCenterTermParams struct {
	MathCenterID int64  `json:"math_center_id"`
	Kind         string `json:"kind"`
	Grade        *int32 `json:"grade"`
}

func (q *Queries) CreateMathCenterTerm(ctx context.Context, arg CreateMathCenterTermParams) (MathCenterTerm, error) {
	row := q.db.QueryRow(ctx, createMathCenterTerm, arg.MathCenterID, arg.Kind, arg.Grade)
	var i MathCenterTerm
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.Kind,
		&i.Grade,
		&i.IsActive,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getActiveTermForCenter = `-- name: GetActiveTermForCenter :one
SELECT id, math_center_id, kind, grade, is_active, created_at, archived_at
FROM math_center_terms
WHERE math_center_id = $1
  AND is_active = TRUE
`

func (q *Queries) GetActiveTermForCenter(ctx context.Context, mathCenterID int64) (MathCenterTerm, error) {
	row := q.db.QueryRow(ctx, getActiveTermForCenter, mathCenterID)
	var i MathCenterTerm
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.Kind,
		&i.Grade,
		&i.IsActive,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getLegacyTermForCenter = `-- name: GetLegacyTermForCenter :one
SELECT id, math_center_id, kind, grade, is_active, created_at, archived_at
FROM math_center_terms
WHERE math_center_id = $1
  AND kind = 'legacy'
`

func (q *Queries) GetLegacyTermForCenter(ctx context.Context, mathCenterID int64) (MathCenterTerm, error) {
	row := q.db.QueryRow(ctx, getLegacyTermForCenter, mathCenterID)
	var i MathCenterTerm
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.Kind,
		&i.Grade,
		&i.IsActive,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getTerm = `-- name: GetTerm :one
SELECT id, math_center_id, kind, grade, is_active, created_at, archived_at
FROM math_center_terms
WHERE id = $1
`

func (q *Queries) GetTerm(ctx context.Context, id int64) (MathCenterTerm, error) {
	row := q.db.QueryRow(ctx, getTerm, id)
	var i MathCenterTerm
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.Kind,
		&i.Grade,
		&i.IsActive,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const isTermActive = `-- name: IsTermActive :one
SELECT is_active
FROM math_center_terms
WHERE id = $1
`

func (q *Queries) IsTermActive(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, isTermActive, id)
	var is_active bool
	err := row.Scan(&is_active)
	return is_active, err
}

const listGroupsForTerm = `-- name: ListGroupsForTerm :many
SELECT id, math_center_id, name, created_at, term_id
FROM math_center_groups
WHERE term_id = $1
ORDER BY name ASC
`

func (q *Queries) ListGroupsForTerm(ctx context.Context, termID int64) ([]MathCenterGroup, error) {
	rows, err := q.db.Query(ctx, listGroupsForTerm, termID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MathCenterGroup{}
	for rows.Next() {
		var i MathCenterGroup
		if err := rows.Scan(
			&i.ID,
			&i.MathCenterID,
			&i.Name,
			&i.CreatedAt,
			&i.TermID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsForTerm = `-- name: ListStudentsForTerm :many
SELECT s.id          AS id,
       s.user_id     AS user_id,
       s.group_id    AS group_id,
       s.term_id     AS term_id,
       g.name        AS group_name,
       u.first_name  AS first_name,
       u.middle_name AS middle_name,
       u.last_name   AS last_name
FROM math_center_students s
         JOIN math_center_groups g ON g.id = s.group_id
         JOIN users u ON u.id = s.user_id
WHERE s.term_id = $1
ORDER BY g.name ASC, u.last_name ASC, u.first_name ASC
`

type ListStudentsForTermRow struct {
	ID         int64   `json:"id"`
	UserID     int64   `json:"user_id"`
	GroupID    int64   `json:"group_id"`
	TermID     int64   `json:"term_id"`
	GroupName  string  `json:"group_name"`
	FirstName  string  `json:"first_name"`
	MiddleName *string `json:"middle_name"`
	LastName   string  `json:"last_name"`
}

func (q *Queries) ListStudentsForTerm(ctx context.Context, termID int64) ([]ListStudentsForTermRow, error) {
	rows, err := q.db.Query(ctx, listStudentsForTerm, termID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentsForTermRow{}
	for rows.Next() {
		var i ListStudentsForTermRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.TermID,
			&i.GroupName,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTermsForCenter = `-- name: ListTermsForCenter :many
SELECT id, math_center_id, kind, grade, is_active, created_at, archived_at
FROM math_center_terms
WHERE math_center_id = $1
ORDER BY is_active DESC, created_at DESC, id DESC
`

func (q *Queries) ListTermsForCenter(ctx context.Context, mathCenterID int64) ([]MathCenterTerm, error) {
	rows, err := q.db.Query(ctx, listTermsForCenter, mathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MathCenterTerm{}
	for rows.Next() {
		var i MathCenterTerm
		if err := rows.Scan(
			&i.ID,
			&i.MathCenterID,
			&i.Kind,
			&i.Grade,
			&i.IsActive,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
