// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: math_center.sql

package store

import (
	"context"
	"time"
)

const addStudentToGroup = `-- name: AddStudentToGroup :one
INSERT INTO math_center_students (
    user_id,
    group_id,
    term_id,
    razbor_default_video,
    razbor_default_pdf_tex
)
SELECT $1,
       g.id,
       g.term_id,
       g.razbor_default_video,
       g.razbor_default_pdf_tex
FROM math_center_groups g
WHERE g.id = $2::bigint
RETURNING id, user_id, group_id, created_at
`

type AddStudentToGroupParams struct {
	UserID  int64 `json:"user_id"`
	GroupID int64 `json:"group_id"`
}

type AddStudentToGroupRow struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	GroupID   int64     `json:"group_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) AddStudentToGroup(ctx context.Context, arg AddStudentToGroupParams) (AddStudentToGroupRow, error) {
	row := q.db.QueryRow(ctx, addStudentToGroup, arg.UserID, arg.GroupID)
	var i AddStudentToGroupRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.CreatedAt,
	)
	return i, err
}

const addTeacherToCenter = `-- name: AddTeacherToCenter :one
INSERT INTO math_center_teachers (user_id, math_center_id, is_head_teacher)
VALUES ($1, $2, $3)
RETURNING id, user_id, math_center_id, is_head_teacher, created_at
`

type AddTeacherToCenterParams struct {
	UserID        int64 `json:"user_id"`
	MathCenterID  int64 `json:"math_center_id"`
	IsHeadTeacher bool  `json:"is_head_teacher"`
}

func (q *Queries) AddTeacherToCenter(ctx context.Context, arg AddTeacherToCenterParams) (MathCenterTeacher, error) {
	row := q.db.QueryRow(ctx, addTeacherToCenter, arg.UserID, arg.MathCenterID, arg.IsHeadTeacher)
	var i MathCenterTeacher
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MathCenterID,
		&i.IsHeadTeacher,
		&i.CreatedAt,
	)
	return i, err
}

const canStudentViewRazbors = `-- name: CanStudentViewRazbors :one
SELECT COALESCE((
    SELECT s.can_view_razbors
    FROM math_center_students s
             JOIN math_center_groups g ON g.id = s.group_id
             JOIN math_center_terms t ON t.id = s.term_id
    WHERE s.user_id = $1
      AND g.math_center_id = $2
      AND (
          t.is_active = TRUE
          OR NOT EXISTS (
              SELECT 1
              FROM math_center_terms active
              WHERE active.math_center_id = $2
                AND active.is_active = TRUE
          )
      )
    ORDER BY t.is_active DESC, s.id DESC
    LIMIT 1
), FALSE)::boolean AS can_view_razbors
`

type CanStudentViewRazborsParams struct {
	UserID       int64 `json:"user_id"`
	MathCenterID int64 `json:"math_center_id"`
}

// Match the current-enrollment semantics used by IsStudentInCenter. The legacy
// fallback keeps pre-term centers working until they open an active term.
func (q *Queries) CanStudentViewRazbors(ctx context.Context, arg CanStudentViewRazborsParams) (bool, error) {
	row := q.db.QueryRow(ctx, canStudentViewRazbors, arg.UserID, arg.MathCenterID)
	var can_view_razbors bool
	err := row.Scan(&can_view_razbors)
	return can_view_razbors, err
}

const countHeadTeachersForCenter = `-- name: CountHeadTeachersForCenter :one
SELECT COUNT(*)
FROM math_center_teachers
WHERE math_center_id = $1
  AND is_head_teacher = TRUE
`

func (q *Queries) CountHeadTeachersForCenter(ctx context.Context, mathCenterID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countHeadTeachersForCenter, mathCenterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMathCenter = `-- name: CreateMathCenter :one
INSERT INTO math_centers (graduation_year)
VALUES ($1)
RETURNING id, graduation_year, created_at
`

func (q *Queries) CreateMathCenter(ctx context.Context, graduationYear int32) (MathCenter, error) {
	row := q.db.QueryRow(ctx, createMathCenter, graduationYear)
	var i MathCenter
	err := row.Scan(&i.ID, &i.GraduationYear, &i.CreatedAt)
	return i, err
}

const createMathCenterGroup = `-- name: CreateMathCenterGroup :one
INSERT INTO math_center_groups (math_center_id, term_id, name)
SELECT $1, t.id, $2
FROM math_center_terms t
WHERE t.math_center_id = $1
  AND t.is_active = TRUE
RETURNING id, math_center_id, name, created_at
`

type CreateMathCenterGroupParams struct {
	MathCenterID int64  `json:"math_center_id"`
	Name         string `json:"name"`
}

type CreateMathCenterGroupRow struct {
	ID           int64     `json:"id"`
	MathCenterID int64     `json:"math_center_id"`
	Name         string    `json:"name"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) CreateMathCenterGroup(ctx context.Context, arg CreateMathCenterGroupParams) (CreateMathCenterGroupRow, error) {
	row := q.db.QueryRow(ctx, createMathCenterGroup, arg.MathCenterID, arg.Name)
	var i CreateMathCenterGroupRow
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMathCenter = `-- name: DeleteMathCenter :execrows
DELETE
FROM math_centers
WHERE id = $1
`

func (q *Queries) DeleteMathCenter(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMathCenter, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMathCenterGroup = `-- name: DeleteMathCenterGroup :execrows
DELETE
FROM math_center_groups
WHERE id = $1
  AND name <> 'Не распределены'
`

func (q *Queries) DeleteMathCenterGroup(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMathCenterGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveStudentByUser = `-- name: GetActiveStudentByUser :one
SELECT student.id,
       student.user_id,
       student.group_id,
       student.term_id,
       student.can_view_razbors,
       student.razbor_default_video,
       student.razbor_default_pdf_tex
FROM math_center_students student
JOIN math_center_groups group_row ON group_row.id = student.group_id
JOIN math_center_terms term_row ON term_row.id = student.term_id
WHERE student.user_id = $1
  AND group_row.math_center_id = $2
  AND term_row.is_active = TRUE
`

type GetActiveStudentByUserParams struct {
	UserID       int64 `json:"user_id"`
	MathCenterID int64 `json:"math_center_id"`
}

type GetActiveStudentByUserRow struct {
	ID                  int64 `json:"id"`
	UserID              int64 `json:"user_id"`
	GroupID             int64 `json:"group_id"`
	TermID              int64 `json:"term_id"`
	CanViewRazbors      bool  `json:"can_view_razbors"`
	RazborDefaultVideo  bool  `json:"razbor_default_video"`
	RazborDefaultPdfTex bool  `json:"razbor_default_pdf_tex"`
}

func (q *Queries) GetActiveStudentByUser(ctx context.Context, arg GetActiveStudentByUserParams) (GetActiveStudentByUserRow, error) {
	row := q.db.QueryRow(ctx, getActiveStudentByUser, arg.UserID, arg.MathCenterID)
	var i GetActiveStudentByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.TermID,
		&i.CanViewRazbors,
		&i.RazborDefaultVideo,
		&i.RazborDefaultPdfTex,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, math_center_id, name, created_at
FROM math_center_groups
WHERE id = $1
`

type GetGroupRow struct {
	ID           int64     `json:"id"`
	MathCenterID int64     `json:"math_center_id"`
	Name         string    `json:"name"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) GetGroup(ctx context.Context, id int64) (GetGroupRow, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i GetGroupRow
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupCenter = `-- name: GetGroupCenter :one
SELECT id, math_center_id, term_id
FROM math_center_groups
WHERE id = $1
`

type GetGroupCenterRow struct {
	ID           int64 `json:"id"`
	MathCenterID int64 `json:"math_center_id"`
	TermID       int64 `json:"term_id"`
}

func (q *Queries) GetGroupCenter(ctx context.Context, id int64) (GetGroupCenterRow, error) {
	row := q.db.QueryRow(ctx, getGroupCenter, id)
	var i GetGroupCenterRow
	err := row.Scan(&i.ID, &i.MathCenterID, &i.TermID)
	return i, err
}

const getMathCenter = `-- name: GetMathCenter :one
SELECT id, graduation_year, created_at
FROM math_centers
WHERE id = $1
`

func (q *Queries) GetMathCenter(ctx context.Context, id int64) (MathCenter, error) {
	row := q.db.QueryRow(ctx, getMathCenter, id)
	var i MathCenter
	err := row.Scan(&i.ID, &i.GraduationYear, &i.CreatedAt)
	return i, err
}

const getRosterBoardMetadata = `-- name: GetRosterBoardMetadata :one
WITH active_term AS (
    SELECT term_row.id, term_row.created_at
    FROM math_center_terms term_row
    WHERE term_row.math_center_id = $1
      AND term_row.is_active = TRUE
    LIMIT 1
),
previous_term AS (
    SELECT t.id, t.created_at
    FROM math_center_terms t
    WHERE t.math_center_id = $1
      AND t.is_active = FALSE
    ORDER BY t.created_at DESC, t.id DESC
    LIMIT 1
),
published_series AS (
    SELECT COUNT(*)::bigint AS count
    FROM math_center_series series
    WHERE series.term_id = (SELECT id FROM active_term)
      AND series.published_at IS NOT NULL
)
SELECT (SELECT id FROM active_term)::bigint AS active_term_id,
       published_series.count AS published_series_count,
       CASE
         WHEN published_series.count >= 10
              OR NOT EXISTS (SELECT 1 FROM previous_term)
           THEN (SELECT id FROM active_term)
         ELSE (SELECT id FROM previous_term)
       END::bigint AS rating_term_id
FROM published_series
`

type GetRosterBoardMetadataRow struct {
	ActiveTermID         int64 `json:"active_term_id"`
	PublishedSeriesCount int64 `json:"published_series_count"`
	RatingTermID         int64 `json:"rating_term_id"`
}

func (q *Queries) GetRosterBoardMetadata(ctx context.Context, mathCenterID int64) (GetRosterBoardMetadataRow, error) {
	row := q.db.QueryRow(ctx, getRosterBoardMetadata, mathCenterID)
	var i GetRosterBoardMetadataRow
	err := row.Scan(&i.ActiveTermID, &i.PublishedSeriesCount, &i.RatingTermID)
	return i, err
}

const getStudent = `-- name: GetStudent :one
SELECT id, user_id, group_id, created_at, can_view_razbors
FROM math_center_students
WHERE id = $1
`

type GetStudentRow struct {
	ID             int64     `json:"id"`
	UserID         int64     `json:"user_id"`
	GroupID        int64     `json:"group_id"`
	CreatedAt      time.Time `json:"created_at"`
	CanViewRazbors bool      `json:"can_view_razbors"`
}

func (q *Queries) GetStudent(ctx context.Context, id int64) (GetStudentRow, error) {
	row := q.db.QueryRow(ctx, getStudent, id)
	var i GetStudentRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.CreatedAt,
		&i.CanViewRazbors,
	)
	return i, err
}

const getStudentByUserID = `-- name: GetStudentByUserID :one
SELECT s.id          AS id,
       s.user_id     AS user_id,
       s.group_id    AS group_id,
       s.can_view_razbors AS can_view_razbors,
       g.name        AS group_name,
       g.math_center_id AS math_center_id,
       mc.graduation_year AS graduation_year
FROM math_center_students s
         JOIN math_center_groups g ON g.id = s.group_id
         JOIN math_centers mc ON mc.id = g.math_center_id
         JOIN math_center_terms t ON t.id = s.term_id
WHERE s.user_id = $1
  AND (t.is_active = TRUE OR NOT EXISTS (
      SELECT 1 FROM math_center_terms active
      WHERE active.math_center_id = g.math_center_id
        AND active.is_active = TRUE
  ))
ORDER BY t.is_active DESC, s.id DESC
LIMIT 1
`

type GetStudentByUserIDRow struct {
	ID             int64  `json:"id"`
	UserID         int64  `json:"user_id"`
	GroupID        int64  `json:"group_id"`
	CanViewRazbors bool   `json:"can_view_razbors"`
	GroupName      string `json:"group_name"`
	MathCenterID   int64  `json:"math_center_id"`
	GraduationYear int32  `json:"graduation_year"`
}

func (q *Queries) GetStudentByUserID(ctx context.Context, userID int64) (GetStudentByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getStudentByUserID, userID)
	var i GetStudentByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.CanViewRazbors,
		&i.GroupName,
		&i.MathCenterID,
		&i.GraduationYear,
	)
	return i, err
}

const getStudentSeriesRazborAccess = `-- name: GetStudentSeriesRazborAccess :one
SELECT series.id AS series_id,
       COALESCE(access.can_view_video, enrollment.razbor_default_video, enrollment.can_view_razbors, FALSE)::boolean AS can_view_video,
       COALESCE(access.can_view_pdf_tex, enrollment.razbor_default_pdf_tex, enrollment.can_view_razbors, FALSE)::boolean AS can_view_pdf_tex
FROM math_center_series series
         LEFT JOIN LATERAL (
             SELECT student.razbor_default_video,
                    student.razbor_default_pdf_tex,
                    student.can_view_razbors
             FROM math_center_students student
                      JOIN math_center_groups student_group ON student_group.id = student.group_id
                      JOIN math_center_terms term ON term.id = student.term_id
             WHERE student.user_id = $1
               AND student_group.math_center_id = series.math_center_id
             ORDER BY (student.term_id = series.term_id) DESC,
                      term.is_active DESC,
                      student.id DESC
             LIMIT 1
         ) enrollment ON TRUE
         LEFT JOIN math_center_student_series_razbor_access access
                   ON access.student_user_id = $1
                       AND access.series_id = series.id
WHERE series.id = $2
`

type GetStudentSeriesRazborAccessParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

type GetStudentSeriesRazborAccessRow struct {
	SeriesID      int64 `json:"series_id"`
	CanViewVideo  bool  `json:"can_view_video"`
	CanViewPdfTex bool  `json:"can_view_pdf_tex"`
}

func (q *Queries) GetStudentSeriesRazborAccess(ctx context.Context, arg GetStudentSeriesRazborAccessParams) (GetStudentSeriesRazborAccessRow, error) {
	row := q.db.QueryRow(ctx, getStudentSeriesRazborAccess, arg.UserID, arg.ID)
	var i GetStudentSeriesRazborAccessRow
	err := row.Scan(&i.SeriesID, &i.CanViewVideo, &i.CanViewPdfTex)
	return i, err
}

const getTeacher = `-- name: GetTeacher :one
SELECT id, user_id, math_center_id, is_head_teacher, created_at
FROM math_center_teachers
WHERE id = $1
`

func (q *Queries) GetTeacher(ctx context.Context, id int64) (MathCenterTeacher, error) {
	row := q.db.QueryRow(ctx, getTeacher, id)
	var i MathCenterTeacher
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MathCenterID,
		&i.IsHeadTeacher,
		&i.CreatedAt,
	)
	return i, err
}

const initializeSeriesRazborAccess = `-- name: InitializeSeriesRazborAccess :exec
INSERT INTO math_center_student_series_razbor_access (
    student_user_id,
    series_id,
    can_view_video,
    can_view_pdf_tex
)
SELECT student.user_id,
       series.id,
       student.razbor_default_video,
       student.razbor_default_pdf_tex
FROM math_center_students student
JOIN math_center_series series ON series.id = $1 AND series.term_id = student.term_id
ON CONFLICT (student_user_id, series_id) DO NOTHING
`

func (q *Queries) InitializeSeriesRazborAccess(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, initializeSeriesRazborAccess, id)
	return err
}

const initializeStudentRazborAccess = `-- name: InitializeStudentRazborAccess :exec
INSERT INTO math_center_student_series_razbor_access (
    student_user_id,
    series_id,
    can_view_video,
    can_view_pdf_tex
)
SELECT student.user_id,
       series.id,
       student.razbor_default_video,
       student.razbor_default_pdf_tex
FROM math_center_students student
JOIN math_center_series series ON series.term_id = student.term_id
WHERE student.id = $1
ON CONFLICT (student_user_id, series_id) DO NOTHING
`

func (q *Queries) InitializeStudentRazborAccess(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, initializeStudentRazborAccess, id)
	return err
}

const isHeadTeacherInCenter = `-- name: IsHeadTeacherInCenter :one
SELECT EXISTS (
    SELECT 1
    FROM math_center_teachers
    WHERE user_id = $1
      AND math_center_id = $2
      AND is_head_teacher = TRUE
) AS is_head_teacher
`

type IsHeadTeacherInCenterParams struct {
	UserID       int64 `json:"user_id"`
	MathCenterID int64 `json:"math_center_id"`
}

func (q *Queries) IsHeadTeacherInCenter(ctx context.Context, arg IsHeadTeacherInCenterParams) (bool, error) {
	row := q.db.QueryRow(ctx, isHeadTeacherInCenter, arg.UserID, arg.MathCenterID)
	var is_head_teacher bool
	err := row.Scan(&is_head_teacher)
	return is_head_teacher, err
}

const listCentersForTeacher = `-- name: ListCentersForTeacher :many
SELECT mc.id                AS id,
       mc.graduation_year   AS graduation_year,
       t.is_head_teacher    AS is_head_teacher
FROM math_center_teachers t
         JOIN math_centers mc ON mc.id = t.math_center_id
WHERE t.user_id = $1
ORDER BY mc.graduation_year ASC
`

type ListCentersForTeacherRow struct {
	ID             int64 `json:"id"`
	GraduationYear int32 `json:"graduation_year"`
	IsHeadTeacher  bool  `json:"is_head_teacher"`
}

func (q *Queries) ListCentersForTeacher(ctx context.Context, userID int64) ([]ListCentersForTeacherRow, error) {
	rows, err := q.db.Query(ctx, listCentersForTeacher, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCentersForTeacherRow{}
	for rows.Next() {
		var i ListCentersForTeacherRow
		if err := rows.Scan(&i.ID, &i.GraduationYear, &i.IsHeadTeacher); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForCenter = `-- name: ListGroupsForCenter :many
WITH selected_term AS (
    SELECT COALESCE(
        (SELECT t.id FROM math_center_terms t WHERE t.math_center_id = $1 AND t.is_active = TRUE),
        (SELECT t.id FROM math_center_terms t WHERE t.math_center_id = $1 AND t.kind = 'legacy')
    ) AS id
)
SELECT g.id, g.math_center_id, g.name, g.created_at
FROM math_center_groups g
WHERE g.math_center_id = $1
  AND g.term_id = (SELECT id FROM selected_term)
ORDER BY name ASC
`

type ListGroupsForCenterRow struct {
	ID           int64     `json:"id"`
	MathCenterID int64     `json:"math_center_id"`
	Name         string    `json:"name"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) ListGroupsForCenter(ctx context.Context, mathCenterID int64) ([]ListGroupsForCenterRow, error) {
	rows, err := q.db.Query(ctx, listGroupsForCenter, mathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupsForCenterRow{}
	for rows.Next() {
		var i ListGroupsForCenterRow
		if err := rows.Scan(
			&i.ID,
			&i.MathCenterID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForCenters = `-- name: ListGroupsForCenters :many
SELECT id, math_center_id, name, created_at, term_id
FROM math_center_groups
WHERE term_id = COALESCE(
    (SELECT id
     FROM math_center_terms t
     WHERE t.math_center_id = math_center_groups.math_center_id
       AND t.is_active = TRUE),
    (SELECT id
     FROM math_center_terms t
     WHERE t.math_center_id = math_center_groups.math_center_id
       AND t.kind = 'legacy')
)
  AND math_center_id = ANY($1::bigint[])
ORDER BY math_center_id ASC, name ASC
`

type ListGroupsForCentersRow struct {
	ID           int64     `json:"id"`
	MathCenterID int64     `json:"math_center_id"`
	Name         string    `json:"name"`
	CreatedAt    time.Time `json:"created_at"`
	TermID       int64     `json:"term_id"`
}

func (q *Queries) ListGroupsForCenters(ctx context.Context, centerIds []int64) ([]ListGroupsForCentersRow, error) {
	rows, err := q.db.Query(ctx, listGroupsForCenters, centerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupsForCentersRow{}
	for rows.Next() {
		var i ListGroupsForCentersRow
		if err := rows.Scan(
			&i.ID,
			&i.MathCenterID,
			&i.Name,
			&i.CreatedAt,
			&i.TermID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeadTeachersForCenter = `-- name: ListHeadTeachersForCenter :many
SELECT t.id          AS id,
       t.user_id     AS user_id,
       u.first_name  AS first_name,
       u.middle_name AS middle_name,
       u.last_name   AS last_name
FROM math_center_teachers t
         JOIN users u ON u.id = t.user_id
WHERE t.math_center_id = $1
  AND t.is_head_teacher = TRUE
ORDER BY u.last_name ASC, u.first_name ASC
`

type ListHeadTeachersForCenterRow struct {
	ID         int64   `json:"id"`
	UserID     int64   `json:"user_id"`
	FirstName  string  `json:"first_name"`
	MiddleName *string `json:"middle_name"`
	LastName   string  `json:"last_name"`
}

func (q *Queries) ListHeadTeachersForCenter(ctx context.Context, mathCenterID int64) ([]ListHeadTeachersForCenterRow, error) {
	rows, err := q.db.Query(ctx, listHeadTeachersForCenter, mathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHeadTeachersForCenterRow{}
	for rows.Next() {
		var i ListHeadTeachersForCenterRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMathCenters = `-- name: ListMathCenters :many
SELECT id, graduation_year, created_at
FROM math_centers
ORDER BY graduation_year ASC
`

func (q *Queries) ListMathCenters(ctx context.Context) ([]MathCenter, error) {
	rows, err := q.db.Query(ctx, listMathCenters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MathCenter{}
	for rows.Next() {
		var i MathCenter
		if err := rows.Scan(&i.ID, &i.GraduationYear, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRazborAccessCellsForManage = `-- name: ListRazborAccessCellsForManage :many
WITH selected_term AS (
    SELECT COALESCE(
        (SELECT t.id FROM math_center_terms t WHERE t.math_center_id = $1 AND t.is_active = TRUE),
        (SELECT t.id FROM math_center_terms t WHERE t.math_center_id = $1 AND t.kind = 'legacy')
    ) AS id
)
SELECT student.id AS student_id,
       student.group_id,
       series.id AS series_id,
       COALESCE(access.can_view_video, student.razbor_default_video)::boolean AS can_view_video,
       COALESCE(access.can_view_pdf_tex, student.razbor_default_pdf_tex)::boolean AS can_view_pdf_tex
FROM math_center_students student
JOIN math_center_series series ON series.term_id = student.term_id
LEFT JOIN math_center_student_series_razbor_access access
  ON access.student_user_id = student.user_id
 AND access.series_id = series.id
WHERE student.term_id = (SELECT id FROM selected_term)
  AND EXISTS (
      SELECT 1 FROM math_center_groups group_row
      WHERE group_row.id = student.group_id
        AND group_row.math_center_id = $1
  )
ORDER BY student.id, series.number
`

type ListRazborAccessCellsForManageRow struct {
	StudentID     int64 `json:"student_id"`
	GroupID       int64 `json:"group_id"`
	SeriesID      int64 `json:"series_id"`
	CanViewVideo  bool  `json:"can_view_video"`
	CanViewPdfTex bool  `json:"can_view_pdf_tex"`
}

func (q *Queries) ListRazborAccessCellsForManage(ctx context.Context, mathCenterID int64) ([]ListRazborAccessCellsForManageRow, error) {
	rows, err := q.db.Query(ctx, listRazborAccessCellsForManage, mathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRazborAccessCellsForManageRow{}
	for rows.Next() {
		var i ListRazborAccessCellsForManageRow
		if err := rows.Scan(
			&i.StudentID,
			&i.GroupID,
			&i.SeriesID,
			&i.CanViewVideo,
			&i.CanViewPdfTex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRazborAccessGroupsForManage = `-- name: ListRazborAccessGroupsForManage :many
WITH selected_term AS (
    SELECT COALESCE(
        (SELECT t.id FROM math_center_terms t WHERE t.math_center_id = $1 AND t.is_active = TRUE),
        (SELECT t.id FROM math_center_terms t WHERE t.math_center_id = $1 AND t.kind = 'legacy')
    ) AS id
)
SELECT group_row.id,
       group_row.math_center_id,
       group_row.name,
       group_row.razbor_default_video,
       group_row.razbor_default_pdf_tex
FROM math_center_groups group_row
WHERE group_row.math_center_id = $1
  AND group_row.term_id = (SELECT id FROM selected_term)
ORDER BY group_row.name ASC
`

type ListRazborAccessGroupsForManageRow struct {
	ID                  int64  `json:"id"`
	MathCenterID        int64  `json:"math_center_id"`
	Name                string `json:"name"`
	RazborDefaultVideo  bool   `json:"razbor_default_video"`
	RazborDefaultPdfTex bool   `json:"razbor_default_pdf_tex"`
}

func (q *Queries) ListRazborAccessGroupsForManage(ctx context.Context, mathCenterID int64) ([]ListRazborAccessGroupsForManageRow, error) {
	rows, err := q.db.Query(ctx, listRazborAccessGroupsForManage, mathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRazborAccessGroupsForManageRow{}
	for rows.Next() {
		var i ListRazborAccessGroupsForManageRow
		if err := rows.Scan(
			&i.ID,
			&i.MathCenterID,
			&i.Name,
			&i.RazborDefaultVideo,
			&i.RazborDefaultPdfTex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRazborAccessSeriesForManage = `-- name: ListRazborAccessSeriesForManage :many
WITH selected_term AS (
    SELECT COALESCE(
        (SELECT t.id FROM math_center_terms t WHERE t.math_center_id = $1 AND t.is_active = TRUE),
        (SELECT t.id FROM math_center_terms t WHERE t.math_center_id = $1 AND t.kind = 'legacy')
    ) AS id
)
SELECT series.id AS series_id,
       series.number AS series_number,
       series.name AS series_name,
       EXISTS (
           SELECT 1
           FROM math_center_problems problem
           JOIN math_center_subproblems subproblem ON subproblem.problem_id = problem.id
           JOIN math_center_subproblem_solutions solution ON solution.subproblem_id = subproblem.id
           WHERE problem.series_id = series.id
             AND NOT solution.is_coffin
             AND (solution.solution_tex_source IS NOT NULL OR solution.solution_pdf_object_key IS NOT NULL)
       ) AS written_posted,
       EXISTS (
           SELECT 1
           FROM math_center_problems problem
           JOIN math_center_subproblems subproblem ON subproblem.problem_id = problem.id
           JOIN math_center_subproblem_solutions solution ON solution.subproblem_id = subproblem.id
           WHERE problem.series_id = series.id
             AND NOT solution.is_coffin
             AND solution.solution_link IS NOT NULL
       ) AS video_posted
FROM math_center_series series
WHERE series.math_center_id = $1
  AND series.term_id = (SELECT id FROM selected_term)
ORDER BY series.number ASC
`

type ListRazborAccessSeriesForManageRow struct {
	SeriesID      int64  `json:"series_id"`
	SeriesNumber  int32  `json:"series_number"`
	SeriesName    string `json:"series_name"`
	WrittenPosted bool   `json:"written_posted"`
	VideoPosted   bool   `json:"video_posted"`
}

func (q *Queries) ListRazborAccessSeriesForManage(ctx context.Context, mathCenterID int64) ([]ListRazborAccessSeriesForManageRow, error) {
	rows, err := q.db.Query(ctx, listRazborAccessSeriesForManage, mathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRazborAccessSeriesForManageRow{}
	for rows.Next() {
		var i ListRazborAccessSeriesForManageRow
		if err := rows.Scan(
			&i.SeriesID,
			&i.SeriesNumber,
			&i.SeriesName,
			&i.WrittenPosted,
			&i.VideoPosted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRazborAccessStudentsForManage = `-- name: ListRazborAccessStudentsForManage :many
WITH selected_term AS (
    SELECT COALESCE(
        (SELECT t.id FROM math_center_terms t WHERE t.math_center_id = $1 AND t.is_active = TRUE),
        (SELECT t.id FROM math_center_terms t WHERE t.math_center_id = $1 AND t.kind = 'legacy')
    ) AS id
)
SELECT student.id AS student_id,
       student.user_id,
       student.group_id,
       student.razbor_default_video,
       student.razbor_default_pdf_tex,
       group_row.name AS group_name,
       user_row.first_name,
       user_row.middle_name,
       user_row.last_name
FROM math_center_students student
JOIN math_center_groups group_row ON group_row.id = student.group_id
JOIN users user_row ON user_row.id = student.user_id
WHERE group_row.math_center_id = $1
  AND student.term_id = (SELECT id FROM selected_term)
ORDER BY group_row.name ASC, user_row.last_name ASC, user_row.first_name ASC
`

type ListRazborAccessStudentsForManageRow struct {
	StudentID           int64   `json:"student_id"`
	UserID              int64   `json:"user_id"`
	GroupID             int64   `json:"group_id"`
	RazborDefaultVideo  bool    `json:"razbor_default_video"`
	RazborDefaultPdfTex bool    `json:"razbor_default_pdf_tex"`
	GroupName           string  `json:"group_name"`
	FirstName           string  `json:"first_name"`
	MiddleName          *string `json:"middle_name"`
	LastName            string  `json:"last_name"`
}

func (q *Queries) ListRazborAccessStudentsForManage(ctx context.Context, mathCenterID int64) ([]ListRazborAccessStudentsForManageRow, error) {
	rows, err := q.db.Query(ctx, listRazborAccessStudentsForManage, mathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRazborAccessStudentsForManageRow{}
	for rows.Next() {
		var i ListRazborAccessStudentsForManageRow
		if err := rows.Scan(
			&i.StudentID,
			&i.UserID,
			&i.GroupID,
			&i.RazborDefaultVideo,
			&i.RazborDefaultPdfTex,
			&i.GroupName,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRosterBoardStudentsForManage = `-- name: ListRosterBoardStudentsForManage :many
WITH active_term AS (
    SELECT term_row.id, term_row.created_at
    FROM math_center_terms term_row
    WHERE term_row.math_center_id = $1
      AND term_row.is_active = TRUE
    LIMIT 1
),
previous_term AS (
    SELECT t.id, t.created_at
    FROM math_center_terms t
    WHERE t.math_center_id = $1
      AND t.is_active = FALSE
    ORDER BY t.created_at DESC, t.id DESC
    LIMIT 1
),
published_series AS (
    SELECT COUNT(*)::bigint AS count
    FROM math_center_series series
    WHERE series.term_id = (SELECT id FROM active_term)
      AND series.published_at IS NOT NULL
),
rating_term AS (
    SELECT CASE
             WHEN published_series.count >= 10
                  OR NOT EXISTS (SELECT 1 FROM previous_term)
               THEN (SELECT id FROM active_term)
             ELSE (SELECT id FROM previous_term)
           END AS id
    FROM published_series
),
candidates AS (
    SELECT student.user_id
    FROM math_center_students student
    WHERE student.term_id = (SELECT id FROM active_term)
),
current_enrollment AS (
    SELECT student.id AS student_id,
           student.user_id,
           CASE WHEN group_row.name = 'Не распределены' THEN NULL::bigint ELSE student.group_id END AS group_id
    FROM math_center_students student
    JOIN math_center_groups group_row ON group_row.id = student.group_id
    WHERE student.term_id = (SELECT id FROM active_term)
),
previous_enrollment AS (
    SELECT student.user_id,
           CASE WHEN group_row.name = 'Не распределены' THEN NULL::bigint ELSE group_row.id END AS group_id,
           CASE WHEN group_row.name = 'Не распределены' THEN NULL::text ELSE group_row.name END AS group_name
    FROM math_center_students student
    JOIN math_center_groups group_row ON group_row.id = student.group_id
    WHERE student.term_id = (SELECT id FROM previous_term)
),
rating_totals AS (
    SELECT thread.student_user_id,
           COUNT(*)::double precision AS rating
    FROM homework_thread thread
    JOIN math_center_subproblems subproblem ON subproblem.id = thread.subproblem_id
    JOIN math_center_problems problem ON problem.id = subproblem.problem_id
    JOIN math_center_series series ON series.id = problem.series_id
    WHERE series.term_id = (SELECT id FROM rating_term)
      AND series.published_at IS NOT NULL
      AND problem.number <> 0
      AND thread.current_status = 'accepted'
      AND NOT EXISTS (
          SELECT 1
          FROM math_center_problems exercise
          JOIN math_center_subproblems exercise_subproblem
            ON exercise_subproblem.problem_id = exercise.id
          LEFT JOIN homework_thread exercise_thread
            ON exercise_thread.student_user_id = thread.student_user_id
           AND exercise_thread.subproblem_id = exercise_subproblem.id
          WHERE exercise.series_id = series.id
            AND exercise.number = 0
            AND COALESCE(exercise_thread.current_status, 'ungraded') <> 'accepted'
      )
    GROUP BY thread.student_user_id
)
SELECT current_enrollment.student_id,
       candidate.user_id,
       current_enrollment.group_id AS current_group_id,
       previous_enrollment.group_id AS previous_group_id,
       previous_enrollment.group_name AS previous_group_name,
       (previous_enrollment.user_id IS NOT NULL)::boolean AS previous_term_enrolled,
       user_row.first_name,
       user_row.middle_name,
       user_row.last_name,
       COALESCE(rating_totals.rating, 0)::double precision AS rating,
       (SELECT count FROM published_series)::bigint AS published_series_count,
       (SELECT id FROM rating_term)::bigint AS rating_term_id
FROM candidates candidate
JOIN users user_row ON user_row.id = candidate.user_id
LEFT JOIN current_enrollment ON current_enrollment.user_id = candidate.user_id
LEFT JOIN previous_enrollment ON previous_enrollment.user_id = candidate.user_id
LEFT JOIN rating_totals ON rating_totals.student_user_id = candidate.user_id
ORDER BY user_row.last_name ASC, user_row.first_name ASC, user_row.middle_name ASC, candidate.user_id ASC
`

type ListRosterBoardStudentsForManageRow struct {
	StudentID            int64   `json:"student_id"`
	UserID               int64   `json:"user_id"`
	CurrentGroupID       *int64  `json:"current_group_id"`
	PreviousGroupID      *int64  `json:"previous_group_id"`
	PreviousGroupName    *string `json:"previous_group_name"`
	PreviousTermEnrolled bool    `json:"previous_term_enrolled"`
	FirstName            string  `json:"first_name"`
	MiddleName           *string `json:"middle_name"`
	LastName             string  `json:"last_name"`
	Rating               float64 `json:"rating"`
	PublishedSeriesCount int64   `json:"published_series_count"`
	RatingTermID         int64   `json:"rating_term_id"`
}

// The allocation board lists the active roster and joins metadata from the
// immediately preceding term. The protected "Не распределены" group is
// represented as a null current/previous group in this management view. Rating
// is deliberately a derived value: it currently mirrors the credited "Решено"
// total and can be replaced by a difficulty-weighted calculation without
// changing the API.
func (q *Queries) ListRosterBoardStudentsForManage(ctx context.Context, mathCenterID int64) ([]ListRosterBoardStudentsForManageRow, error) {
	rows, err := q.db.Query(ctx, listRosterBoardStudentsForManage, mathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRosterBoardStudentsForManageRow{}
	for rows.Next() {
		var i ListRosterBoardStudentsForManageRow
		if err := rows.Scan(
			&i.StudentID,
			&i.UserID,
			&i.CurrentGroupID,
			&i.PreviousGroupID,
			&i.PreviousGroupName,
			&i.PreviousTermEnrolled,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
			&i.Rating,
			&i.PublishedSeriesCount,
			&i.RatingTermID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeActiveStudentForCenter = `-- name: RemoveActiveStudentForCenter :execrows
DELETE FROM math_center_students student
USING math_center_groups group_row, math_center_terms term_row
WHERE student.id = $1::bigint
  AND group_row.id = student.group_id
  AND term_row.id = student.term_id
  AND group_row.math_center_id = $2::bigint
  AND term_row.is_active = TRUE`

type RemoveActiveStudentForCenterParams struct {
	StudentID    int64 `json:"student_id"`
	MathCenterID int64 `json:"math_center_id"`
}

func (q *Queries) RemoveActiveStudentForCenter(ctx context.Context, arg RemoveActiveStudentForCenterParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeActiveStudentForCenter, arg.StudentID, arg.MathCenterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listStudentSeriesRazborAccessForCenter = `-- name: ListStudentSeriesRazborAccessForCenter :many
SELECT series.id AS series_id,
       COALESCE(access.can_view_video, enrollment.razbor_default_video, enrollment.can_view_razbors, FALSE)::boolean AS can_view_video,
       COALESCE(access.can_view_pdf_tex, enrollment.razbor_default_pdf_tex, enrollment.can_view_razbors, FALSE)::boolean AS can_view_pdf_tex
FROM math_center_series series
         LEFT JOIN LATERAL (
             SELECT student.razbor_default_video,
                    student.razbor_default_pdf_tex,
                    student.can_view_razbors
             FROM math_center_students student
                      JOIN math_center_groups student_group ON student_group.id = student.group_id
                      JOIN math_center_terms term ON term.id = student.term_id
             WHERE student.user_id = $1
               AND student_group.math_center_id = series.math_center_id
             ORDER BY (student.term_id = series.term_id) DESC,
                      term.is_active DESC,
                      student.id DESC
             LIMIT 1
         ) enrollment ON TRUE
         LEFT JOIN math_center_student_series_razbor_access access
                   ON access.student_user_id = $1
                       AND access.series_id = series.id
WHERE series.math_center_id = $2
ORDER BY series.number ASC
`

type ListStudentSeriesRazborAccessForCenterParams struct {
	UserID       int64 `json:"user_id"`
	MathCenterID int64 `json:"math_center_id"`
}

type ListStudentSeriesRazborAccessForCenterRow struct {
	SeriesID      int64 `json:"series_id"`
	CanViewVideo  bool  `json:"can_view_video"`
	CanViewPdfTex bool  `json:"can_view_pdf_tex"`
}

// Use the enrollment belonging to the series' term when it exists; otherwise
// fall back to the student's current center enrollment for carried coffins.
func (q *Queries) ListStudentSeriesRazborAccessForCenter(ctx context.Context, arg ListStudentSeriesRazborAccessForCenterParams) ([]ListStudentSeriesRazborAccessForCenterRow, error) {
	rows, err := q.db.Query(ctx, listStudentSeriesRazborAccessForCenter, arg.UserID, arg.MathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentSeriesRazborAccessForCenterRow{}
	for rows.Next() {
		var i ListStudentSeriesRazborAccessForCenterRow
		if err := rows.Scan(&i.SeriesID, &i.CanViewVideo, &i.CanViewPdfTex); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentSeriesRazborAccessForManage = `-- name: ListStudentSeriesRazborAccessForManage :many
SELECT series.id AS series_id,
       series.number AS series_number,
       series.name AS series_name,
       COALESCE(access.can_view_video, student.razbor_default_video, student.can_view_razbors)::boolean AS can_view_video,
       COALESCE(access.can_view_pdf_tex, student.razbor_default_pdf_tex, student.can_view_razbors)::boolean AS can_view_pdf_tex
FROM math_center_students student
         JOIN math_center_series series ON series.term_id = student.term_id
         LEFT JOIN math_center_student_series_razbor_access access
                   ON access.student_user_id = student.user_id
                       AND access.series_id = series.id
WHERE student.id = $1
ORDER BY series.number ASC
`

type ListStudentSeriesRazborAccessForManageRow struct {
	SeriesID      int64  `json:"series_id"`
	SeriesNumber  int32  `json:"series_number"`
	SeriesName    string `json:"series_name"`
	CanViewVideo  bool   `json:"can_view_video"`
	CanViewPdfTex bool   `json:"can_view_pdf_tex"`
}

// The management panel is term-scoped through the selected student enrollment.
// Missing overrides inherit the enrollment-wide default.
func (q *Queries) ListStudentSeriesRazborAccessForManage(ctx context.Context, id int64) ([]ListStudentSeriesRazborAccessForManageRow, error) {
	rows, err := q.db.Query(ctx, listStudentSeriesRazborAccessForManage, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentSeriesRazborAccessForManageRow{}
	for rows.Next() {
		var i ListStudentSeriesRazborAccessForManageRow
		if err := rows.Scan(
			&i.SeriesID,
			&i.SeriesNumber,
			&i.SeriesName,
			&i.CanViewVideo,
			&i.CanViewPdfTex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsForCenter = `-- name: ListStudentsForCenter :many
SELECT s.id        AS id,
       s.user_id   AS user_id,
       s.group_id  AS group_id,
       s.can_view_razbors AS can_view_razbors,
       g.name      AS group_name,
       u.first_name AS first_name,
       u.middle_name AS middle_name,
       u.last_name AS last_name
FROM math_center_students s
         JOIN math_center_groups g ON g.id = s.group_id
         JOIN users u ON u.id = s.user_id
WHERE g.term_id = COALESCE(
    (SELECT t.id FROM math_center_terms t WHERE t.math_center_id = $1 AND t.is_active = TRUE),
    (SELECT t.id FROM math_center_terms t WHERE t.math_center_id = $1 AND t.kind = 'legacy')
)
ORDER BY g.name ASC, u.last_name ASC, u.first_name ASC
`

type ListStudentsForCenterRow struct {
	ID             int64   `json:"id"`
	UserID         int64   `json:"user_id"`
	GroupID        int64   `json:"group_id"`
	CanViewRazbors bool    `json:"can_view_razbors"`
	GroupName      string  `json:"group_name"`
	FirstName      string  `json:"first_name"`
	MiddleName     *string `json:"middle_name"`
	LastName       string  `json:"last_name"`
}

func (q *Queries) ListStudentsForCenter(ctx context.Context, mathCenterID int64) ([]ListStudentsForCenterRow, error) {
	rows, err := q.db.Query(ctx, listStudentsForCenter, mathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentsForCenterRow{}
	for rows.Next() {
		var i ListStudentsForCenterRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.CanViewRazbors,
			&i.GroupName,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsForCenters = `-- name: ListStudentsForCenters :many
SELECT s.id            AS id,
       s.user_id       AS user_id,
       s.group_id      AS group_id,
       g.name          AS group_name,
       g.math_center_id AS math_center_id,
       u.first_name    AS first_name,
       u.middle_name   AS middle_name,
       u.last_name     AS last_name
FROM math_center_students s
         JOIN math_center_groups g ON g.id = s.group_id
         JOIN users u ON u.id = s.user_id
WHERE s.term_id = COALESCE(
    (SELECT id
     FROM math_center_terms t
     WHERE t.math_center_id = g.math_center_id
       AND t.is_active = TRUE),
    (SELECT id
     FROM math_center_terms t
     WHERE t.math_center_id = g.math_center_id
       AND t.kind = 'legacy')
)
  AND g.math_center_id = ANY($1::bigint[])
ORDER BY g.math_center_id ASC, g.name ASC, u.last_name ASC, u.first_name ASC
`

type ListStudentsForCentersRow struct {
	ID           int64   `json:"id"`
	UserID       int64   `json:"user_id"`
	GroupID      int64   `json:"group_id"`
	GroupName    string  `json:"group_name"`
	MathCenterID int64   `json:"math_center_id"`
	FirstName    string  `json:"first_name"`
	MiddleName   *string `json:"middle_name"`
	LastName     string  `json:"last_name"`
}

func (q *Queries) ListStudentsForCenters(ctx context.Context, centerIds []int64) ([]ListStudentsForCentersRow, error) {
	rows, err := q.db.Query(ctx, listStudentsForCenters, centerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentsForCentersRow{}
	for rows.Next() {
		var i ListStudentsForCentersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.GroupName,
			&i.MathCenterID,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeacherEnrollmentsForUser = `-- name: ListTeacherEnrollmentsForUser :many
SELECT t.id              AS teacher_id,
       t.math_center_id  AS center_id,
       mc.graduation_year AS graduation_year,
       t.is_head_teacher AS is_head_teacher
FROM math_center_teachers t
         JOIN math_centers mc ON mc.id = t.math_center_id
WHERE t.user_id = $1
ORDER BY mc.graduation_year DESC
`

type ListTeacherEnrollmentsForUserRow struct {
	TeacherID      int64 `json:"teacher_id"`
	CenterID       int64 `json:"center_id"`
	GraduationYear int32 `json:"graduation_year"`
	IsHeadTeacher  bool  `json:"is_head_teacher"`
}

// Like ListCentersForTeacher, but also returns the math_center_teachers row id
// (teacher_id) so the admin UI can remove an individual teaching enrollment.
func (q *Queries) ListTeacherEnrollmentsForUser(ctx context.Context, userID int64) ([]ListTeacherEnrollmentsForUserRow, error) {
	rows, err := q.db.Query(ctx, listTeacherEnrollmentsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeacherEnrollmentsForUserRow{}
	for rows.Next() {
		var i ListTeacherEnrollmentsForUserRow
		if err := rows.Scan(
			&i.TeacherID,
			&i.CenterID,
			&i.GraduationYear,
			&i.IsHeadTeacher,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeachersForCenter = `-- name: ListTeachersForCenter :many
SELECT t.id              AS id,
       t.user_id         AS user_id,
       t.math_center_id  AS math_center_id,
       t.is_head_teacher AS is_head_teacher,
       u.first_name      AS first_name,
       u.middle_name     AS middle_name,
       u.last_name       AS last_name
FROM math_center_teachers t
         JOIN users u ON u.id = t.user_id
WHERE t.math_center_id = $1
ORDER BY t.is_head_teacher DESC, u.last_name ASC, u.first_name ASC
`

type ListTeachersForCenterRow struct {
	ID            int64   `json:"id"`
	UserID        int64   `json:"user_id"`
	MathCenterID  int64   `json:"math_center_id"`
	IsHeadTeacher bool    `json:"is_head_teacher"`
	FirstName     string  `json:"first_name"`
	MiddleName    *string `json:"middle_name"`
	LastName      string  `json:"last_name"`
}

func (q *Queries) ListTeachersForCenter(ctx context.Context, mathCenterID int64) ([]ListTeachersForCenterRow, error) {
	rows, err := q.db.Query(ctx, listTeachersForCenter, mathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeachersForCenterRow{}
	for rows.Next() {
		var i ListTeachersForCenterRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MathCenterID,
			&i.IsHeadTeacher,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeachersForCenters = `-- name: ListTeachersForCenters :many
SELECT t.id              AS id,
       t.user_id         AS user_id,
       t.math_center_id  AS math_center_id,
       t.is_head_teacher AS is_head_teacher,
       u.first_name      AS first_name,
       u.middle_name     AS middle_name,
       u.last_name       AS last_name
FROM math_center_teachers t
         JOIN users u ON u.id = t.user_id
WHERE t.math_center_id = ANY($1::bigint[])
ORDER BY t.math_center_id ASC, t.is_head_teacher DESC, u.last_name ASC, u.first_name ASC
`

type ListTeachersForCentersRow struct {
	ID            int64   `json:"id"`
	UserID        int64   `json:"user_id"`
	MathCenterID  int64   `json:"math_center_id"`
	IsHeadTeacher bool    `json:"is_head_teacher"`
	FirstName     string  `json:"first_name"`
	MiddleName    *string `json:"middle_name"`
	LastName      string  `json:"last_name"`
}

func (q *Queries) ListTeachersForCenters(ctx context.Context, centerIds []int64) ([]ListTeachersForCentersRow, error) {
	rows, err := q.db.Query(ctx, listTeachersForCenters, centerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeachersForCentersRow{}
	for rows.Next() {
		var i ListTeachersForCentersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MathCenterID,
			&i.IsHeadTeacher,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeActiveStudentByUser = `-- name: RemoveActiveStudentByUser :execrows
DELETE FROM math_center_students student
USING math_center_groups group_row, math_center_terms term_row
WHERE student.user_id = $1
  AND group_row.id = student.group_id
  AND term_row.id = student.term_id
  AND group_row.math_center_id = $2
  AND term_row.is_active = TRUE
`

type RemoveActiveStudentByUserParams struct {
	UserID       int64 `json:"user_id"`
	MathCenterID int64 `json:"math_center_id"`
}

func (q *Queries) RemoveActiveStudentByUser(ctx context.Context, arg RemoveActiveStudentByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeActiveStudentByUser, arg.UserID, arg.MathCenterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeStudent = `-- name: RemoveStudent :execrows
DELETE
FROM math_center_students
WHERE id = $1
`

func (q *Queries) RemoveStudent(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, removeStudent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeTeacher = `-- name: RemoveTeacher :execrows
DELETE
FROM math_center_teachers
WHERE id = $1
`

func (q *Queries) RemoveTeacher(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, removeTeacher, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, first_name, middle_name, last_name
FROM users
WHERE username ILIKE '%' || $1::text || '%'
   OR first_name ILIKE '%' || $1::text || '%'
   OR last_name ILIKE '%' || $1::text || '%'
ORDER BY username ASC
LIMIT 20
`

type SearchUsersRow struct {
	ID         int64   `json:"id"`
	Username   string  `json:"username"`
	FirstName  string  `json:"first_name"`
	MiddleName *string `json:"middle_name"`
	LastName   string  `json:"last_name"`
}

func (q *Queries) SearchUsers(ctx context.Context, q_ string) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, q_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGroupRazborDefaultPDFTex = `-- name: SetGroupRazborDefaultPDFTex :execrows
UPDATE math_center_groups
SET razbor_default_pdf_tex = $1::boolean
WHERE id = $2::bigint
  AND term_id = (SELECT id FROM math_center_terms WHERE is_active = TRUE AND math_center_id = (SELECT math_center_id FROM math_center_groups WHERE id = $2::bigint))
`

type SetGroupRazborDefaultPDFTexParams struct {
	Allowed bool  `json:"allowed"`
	GroupID int64 `json:"group_id"`
}

func (q *Queries) SetGroupRazborDefaultPDFTex(ctx context.Context, arg SetGroupRazborDefaultPDFTexParams) (int64, error) {
	result, err := q.db.Exec(ctx, setGroupRazborDefaultPDFTex, arg.Allowed, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setGroupRazborDefaultVideo = `-- name: SetGroupRazborDefaultVideo :execrows
UPDATE math_center_groups
SET razbor_default_video = $1::boolean
WHERE id = $2::bigint
  AND term_id = (SELECT id FROM math_center_terms WHERE is_active = TRUE AND math_center_id = (SELECT math_center_id FROM math_center_groups WHERE id = $2::bigint))
`

type SetGroupRazborDefaultVideoParams struct {
	Allowed bool  `json:"allowed"`
	GroupID int64 `json:"group_id"`
}

func (q *Queries) SetGroupRazborDefaultVideo(ctx context.Context, arg SetGroupRazborDefaultVideoParams) (int64, error) {
	result, err := q.db.Exec(ctx, setGroupRazborDefaultVideo, arg.Allowed, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setGroupRazborMatrixSeries = `-- name: SetGroupRazborMatrixSeries :execrows
INSERT INTO math_center_student_series_razbor_access (
    student_user_id,
    series_id,
    can_view_video,
    can_view_pdf_tex
)
SELECT student.user_id,
       series.id,
       CASE WHEN $1::text = 'video'
            THEN $2::boolean
            ELSE COALESCE(access.can_view_video, student.razbor_default_video)
       END,
       CASE WHEN $1::text = 'pdf_tex'
            THEN $2::boolean
            ELSE COALESCE(access.can_view_pdf_tex, student.razbor_default_pdf_tex)
       END
FROM math_center_students student
JOIN math_center_series series ON series.term_id = student.term_id
JOIN math_center_terms active_term ON active_term.id = student.term_id AND active_term.is_active = TRUE
LEFT JOIN math_center_student_series_razbor_access access
  ON access.student_user_id = student.user_id
 AND access.series_id = series.id
WHERE student.group_id = $3::bigint
  AND ($4::bigint = 0 OR series.id = $4::bigint)
ON CONFLICT (student_user_id, series_id)
DO UPDATE SET can_view_video = EXCLUDED.can_view_video,
              can_view_pdf_tex = EXCLUDED.can_view_pdf_tex,
              updated_at = NOW()
`

type SetGroupRazborMatrixSeriesParams struct {
	Format   string `json:"format"`
	Allowed  bool   `json:"allowed"`
	GroupID  int64  `json:"group_id"`
	SeriesID int64  `json:"series_id"`
}

func (q *Queries) SetGroupRazborMatrixSeries(ctx context.Context, arg SetGroupRazborMatrixSeriesParams) (int64, error) {
	result, err := q.db.Exec(ctx, setGroupRazborMatrixSeries,
		arg.Format,
		arg.Allowed,
		arg.GroupID,
		arg.SeriesID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setGroupsRazborDefaultPDFTexForCenter = `-- name: SetGroupsRazborDefaultPDFTexForCenter :exec
UPDATE math_center_groups
SET razbor_default_pdf_tex = $1::boolean
WHERE math_center_id = $2::bigint
  AND term_id = (SELECT id FROM math_center_terms WHERE math_center_id = $2::bigint AND is_active = TRUE)
`

type SetGroupsRazborDefaultPDFTexForCenterParams struct {
	Allowed      bool  `json:"allowed"`
	MathCenterID int64 `json:"math_center_id"`
}

func (q *Queries) SetGroupsRazborDefaultPDFTexForCenter(ctx context.Context, arg SetGroupsRazborDefaultPDFTexForCenterParams) error {
	_, err := q.db.Exec(ctx, setGroupsRazborDefaultPDFTexForCenter, arg.Allowed, arg.MathCenterID)
	return err
}

const setGroupsRazborDefaultVideoForCenter = `-- name: SetGroupsRazborDefaultVideoForCenter :exec
UPDATE math_center_groups
SET razbor_default_video = $1::boolean
WHERE math_center_id = $2::bigint
  AND term_id = (SELECT id FROM math_center_terms WHERE math_center_id = $2::bigint AND is_active = TRUE)
`

type SetGroupsRazborDefaultVideoForCenterParams struct {
	Allowed      bool  `json:"allowed"`
	MathCenterID int64 `json:"math_center_id"`
}

func (q *Queries) SetGroupsRazborDefaultVideoForCenter(ctx context.Context, arg SetGroupsRazborDefaultVideoForCenterParams) error {
	_, err := q.db.Exec(ctx, setGroupsRazborDefaultVideoForCenter, arg.Allowed, arg.MathCenterID)
	return err
}

const setStudentGroup = `-- name: SetStudentGroup :execrows
UPDATE math_center_students
SET group_id = $2
WHERE id = $1
`

type SetStudentGroupParams struct {
	ID      int64 `json:"id"`
	GroupID int64 `json:"group_id"`
}

func (q *Queries) SetStudentGroup(ctx context.Context, arg SetStudentGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, setStudentGroup, arg.ID, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setStudentRazborAccess = `-- name: SetStudentRazborAccess :execrows
UPDATE math_center_students
SET can_view_razbors = $2
WHERE id = $1
`

type SetStudentRazborAccessParams struct {
	ID             int64 `json:"id"`
	CanViewRazbors bool  `json:"can_view_razbors"`
}

func (q *Queries) SetStudentRazborAccess(ctx context.Context, arg SetStudentRazborAccessParams) (int64, error) {
	result, err := q.db.Exec(ctx, setStudentRazborAccess, arg.ID, arg.CanViewRazbors)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setStudentRazborDefaultPDFTex = `-- name: SetStudentRazborDefaultPDFTex :execrows
UPDATE math_center_students
SET razbor_default_pdf_tex = $1::boolean
WHERE id = $2::bigint
  AND term_id = (SELECT id FROM math_center_terms WHERE is_active = TRUE AND math_center_id = (SELECT g.math_center_id FROM math_center_groups g JOIN math_center_students s ON s.group_id = g.id WHERE s.id = $2::bigint))
`

type SetStudentRazborDefaultPDFTexParams struct {
	Allowed   bool  `json:"allowed"`
	StudentID int64 `json:"student_id"`
}

func (q *Queries) SetStudentRazborDefaultPDFTex(ctx context.Context, arg SetStudentRazborDefaultPDFTexParams) (int64, error) {
	result, err := q.db.Exec(ctx, setStudentRazborDefaultPDFTex, arg.Allowed, arg.StudentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setStudentRazborDefaultVideo = `-- name: SetStudentRazborDefaultVideo :execrows
UPDATE math_center_students
SET razbor_default_video = $1::boolean
WHERE id = $2::bigint
  AND term_id = (SELECT id FROM math_center_terms WHERE is_active = TRUE AND math_center_id = (SELECT g.math_center_id FROM math_center_groups g JOIN math_center_students s ON s.group_id = g.id WHERE s.id = $2::bigint))
`

type SetStudentRazborDefaultVideoParams struct {
	Allowed   bool  `json:"allowed"`
	StudentID int64 `json:"student_id"`
}

func (q *Queries) SetStudentRazborDefaultVideo(ctx context.Context, arg SetStudentRazborDefaultVideoParams) (int64, error) {
	result, err := q.db.Exec(ctx, setStudentRazborDefaultVideo, arg.Allowed, arg.StudentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setStudentRazborMatrixSeries = `-- name: SetStudentRazborMatrixSeries :execrows
INSERT INTO math_center_student_series_razbor_access (
    student_user_id,
    series_id,
    can_view_video,
    can_view_pdf_tex
)
SELECT student.user_id,
       series.id,
       CASE WHEN $1::text = 'video'
            THEN $2::boolean
            ELSE COALESCE(access.can_view_video, student.razbor_default_video)
       END,
       CASE WHEN $1::text = 'pdf_tex'
            THEN $2::boolean
            ELSE COALESCE(access.can_view_pdf_tex, student.razbor_default_pdf_tex)
       END
FROM math_center_students student
JOIN math_center_series series ON series.term_id = student.term_id
JOIN math_center_terms active_term ON active_term.id = student.term_id AND active_term.is_active = TRUE
LEFT JOIN math_center_student_series_razbor_access access
  ON access.student_user_id = student.user_id
 AND access.series_id = series.id
WHERE student.id = $3::bigint
  AND ($4::bigint = 0 OR series.id = $4::bigint)
ON CONFLICT (student_user_id, series_id)
DO UPDATE SET can_view_video = EXCLUDED.can_view_video,
              can_view_pdf_tex = EXCLUDED.can_view_pdf_tex,
              updated_at = NOW()
`

type SetStudentRazborMatrixSeriesParams struct {
	Format    string `json:"format"`
	Allowed   bool   `json:"allowed"`
	StudentID int64  `json:"student_id"`
	SeriesID  int64  `json:"series_id"`
}

func (q *Queries) SetStudentRazborMatrixSeries(ctx context.Context, arg SetStudentRazborMatrixSeriesParams) (int64, error) {
	result, err := q.db.Exec(ctx, setStudentRazborMatrixSeries,
		arg.Format,
		arg.Allowed,
		arg.StudentID,
		arg.SeriesID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setStudentSeriesRazborAccess = `-- name: SetStudentSeriesRazborAccess :execrows
INSERT INTO math_center_student_series_razbor_access (
    student_user_id,
    series_id,
    can_view_video,
    can_view_pdf_tex
)
SELECT student.user_id,
       series.id,
       $3,
       $4
FROM math_center_students student
         JOIN math_center_groups student_group ON student_group.id = student.group_id
         JOIN math_center_series series
              ON series.id = $2
                  AND series.term_id = student.term_id
                  AND series.math_center_id = student_group.math_center_id
WHERE student.id = $1
ON CONFLICT (student_user_id, series_id)
    DO UPDATE SET can_view_video = EXCLUDED.can_view_video,
                  can_view_pdf_tex = EXCLUDED.can_view_pdf_tex,
                  updated_at = NOW()
`

type SetStudentSeriesRazborAccessParams struct {
	ID            int64 `json:"id"`
	ID_2          int64 `json:"id_2"`
	CanViewVideo  bool  `json:"can_view_video"`
	CanViewPdfTex bool  `json:"can_view_pdf_tex"`
}

// The INSERT ... SELECT is also the same-center/same-term authorization check:
// a series outside this enrollment produces zero affected rows.
func (q *Queries) SetStudentSeriesRazborAccess(ctx context.Context, arg SetStudentSeriesRazborAccessParams) (int64, error) {
	result, err := q.db.Exec(ctx, setStudentSeriesRazborAccess,
		arg.ID,
		arg.ID_2,
		arg.CanViewVideo,
		arg.CanViewPdfTex,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setStudentsRazborDefaultPDFTexForCenter = `-- name: SetStudentsRazborDefaultPDFTexForCenter :exec
UPDATE math_center_students
SET razbor_default_pdf_tex = $1::boolean
WHERE term_id = (SELECT id FROM math_center_terms WHERE math_center_id = $2::bigint AND is_active = TRUE)
`

type SetStudentsRazborDefaultPDFTexForCenterParams struct {
	Allowed      bool  `json:"allowed"`
	MathCenterID int64 `json:"math_center_id"`
}

func (q *Queries) SetStudentsRazborDefaultPDFTexForCenter(ctx context.Context, arg SetStudentsRazborDefaultPDFTexForCenterParams) error {
	_, err := q.db.Exec(ctx, setStudentsRazborDefaultPDFTexForCenter, arg.Allowed, arg.MathCenterID)
	return err
}

const setStudentsRazborDefaultPDFTexForGroup = `-- name: SetStudentsRazborDefaultPDFTexForGroup :exec
UPDATE math_center_students
SET razbor_default_pdf_tex = $1::boolean
WHERE group_id = $2::bigint
  AND term_id = (SELECT id FROM math_center_terms WHERE is_active = TRUE AND math_center_id = (SELECT math_center_id FROM math_center_groups WHERE id = $2::bigint))
`

type SetStudentsRazborDefaultPDFTexForGroupParams struct {
	Allowed bool  `json:"allowed"`
	GroupID int64 `json:"group_id"`
}

func (q *Queries) SetStudentsRazborDefaultPDFTexForGroup(ctx context.Context, arg SetStudentsRazborDefaultPDFTexForGroupParams) error {
	_, err := q.db.Exec(ctx, setStudentsRazborDefaultPDFTexForGroup, arg.Allowed, arg.GroupID)
	return err
}

const setStudentsRazborDefaultVideoForCenter = `-- name: SetStudentsRazborDefaultVideoForCenter :exec
UPDATE math_center_students
SET razbor_default_video = $1::boolean
WHERE term_id = (SELECT id FROM math_center_terms WHERE math_center_id = $2::bigint AND is_active = TRUE)
`

type SetStudentsRazborDefaultVideoForCenterParams struct {
	Allowed      bool  `json:"allowed"`
	MathCenterID int64 `json:"math_center_id"`
}

func (q *Queries) SetStudentsRazborDefaultVideoForCenter(ctx context.Context, arg SetStudentsRazborDefaultVideoForCenterParams) error {
	_, err := q.db.Exec(ctx, setStudentsRazborDefaultVideoForCenter, arg.Allowed, arg.MathCenterID)
	return err
}

const setStudentsRazborDefaultVideoForGroup = `-- name: SetStudentsRazborDefaultVideoForGroup :exec
UPDATE math_center_students
SET razbor_default_video = $1::boolean
WHERE group_id = $2::bigint
  AND term_id = (SELECT id FROM math_center_terms WHERE is_active = TRUE AND math_center_id = (SELECT math_center_id FROM math_center_groups WHERE id = $2::bigint))
`

type SetStudentsRazborDefaultVideoForGroupParams struct {
	Allowed bool  `json:"allowed"`
	GroupID int64 `json:"group_id"`
}

func (q *Queries) SetStudentsRazborDefaultVideoForGroup(ctx context.Context, arg SetStudentsRazborDefaultVideoForGroupParams) error {
	_, err := q.db.Exec(ctx, setStudentsRazborDefaultVideoForGroup, arg.Allowed, arg.GroupID)
	return err
}

const setTeacherHead = `-- name: SetTeacherHead :execrows
UPDATE math_center_teachers
SET is_head_teacher = $2
WHERE id = $1
`

type SetTeacherHeadParams struct {
	ID            int64 `json:"id"`
	IsHeadTeacher bool  `json:"is_head_teacher"`
}

func (q *Queries) SetTeacherHead(ctx context.Context, arg SetTeacherHeadParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTeacherHead, arg.ID, arg.IsHeadTeacher)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTermRazborMatrixSeries = `-- name: SetTermRazborMatrixSeries :execrows
INSERT INTO math_center_student_series_razbor_access (
    student_user_id,
    series_id,
    can_view_video,
    can_view_pdf_tex
)
SELECT student.user_id,
       series.id,
       CASE WHEN $1::text = 'video'
            THEN $2::boolean
            ELSE COALESCE(access.can_view_video, student.razbor_default_video)
       END,
       CASE WHEN $1::text = 'pdf_tex'
            THEN $2::boolean
            ELSE COALESCE(access.can_view_pdf_tex, student.razbor_default_pdf_tex)
       END
FROM math_center_students student
JOIN math_center_series series ON series.term_id = student.term_id
JOIN math_center_terms term ON term.id = student.term_id
LEFT JOIN math_center_student_series_razbor_access access
  ON access.student_user_id = student.user_id
 AND access.series_id = series.id
WHERE term.math_center_id = $3::bigint
  AND term.is_active = TRUE
  AND ($4::bigint = 0 OR series.id = $4::bigint)
ON CONFLICT (student_user_id, series_id)
DO UPDATE SET can_view_video = EXCLUDED.can_view_video,
              can_view_pdf_tex = EXCLUDED.can_view_pdf_tex,
              updated_at = NOW()
`

type SetTermRazborMatrixSeriesParams struct {
	Format       string `json:"format"`
	Allowed      bool   `json:"allowed"`
	MathCenterID int64  `json:"math_center_id"`
	SeriesID     int64  `json:"series_id"`
}

func (q *Queries) SetTermRazborMatrixSeries(ctx context.Context, arg SetTermRazborMatrixSeriesParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTermRazborMatrixSeries,
		arg.Format,
		arg.Allowed,
		arg.MathCenterID,
		arg.SeriesID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
