// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: math_center_series.sql

package store

import (
	"context"
	"time"
)

const clearSeriesTex = `-- name: ClearSeriesTex :one
UPDATE math_center_series
SET tex_source = NULL
WHERE id = $1
RETURNING id, math_center_id, number, name, due_at, pdf_object_key, published_at, created_at, tex_source
`

func (q *Queries) ClearSeriesTex(ctx context.Context, id int64) (MathCenterSeries, error) {
	row := q.db.QueryRow(ctx, clearSeriesTex, id)
	var i MathCenterSeries
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.Number,
		&i.Name,
		&i.DueAt,
		&i.PdfObjectKey,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.TexSource,
	)
	return i, err
}

const createProblem = `-- name: CreateProblem :one
INSERT INTO math_center_problems (series_id, number)
VALUES ($1, $2)
RETURNING id, series_id, number, created_at
`

type CreateProblemParams struct {
	SeriesID int64 `json:"series_id"`
	Number   int32 `json:"number"`
}

func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (MathCenterProblem, error) {
	row := q.db.QueryRow(ctx, createProblem, arg.SeriesID, arg.Number)
	var i MathCenterProblem
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Number,
		&i.CreatedAt,
	)
	return i, err
}

const createSeries = `-- name: CreateSeries :one
INSERT INTO math_center_series (math_center_id, number, name, due_at)
VALUES ($1, $2, $3, $4)
RETURNING id, math_center_id, number, name, due_at, pdf_object_key, published_at, created_at, tex_source
`

type CreateSeriesParams struct {
	MathCenterID int64     `json:"math_center_id"`
	Number       int32     `json:"number"`
	Name         string    `json:"name"`
	DueAt        time.Time `json:"due_at"`
}

func (q *Queries) CreateSeries(ctx context.Context, arg CreateSeriesParams) (MathCenterSeries, error) {
	row := q.db.QueryRow(ctx, createSeries,
		arg.MathCenterID,
		arg.Number,
		arg.Name,
		arg.DueAt,
	)
	var i MathCenterSeries
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.Number,
		&i.Name,
		&i.DueAt,
		&i.PdfObjectKey,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.TexSource,
	)
	return i, err
}

const createSubproblem = `-- name: CreateSubproblem :one
INSERT INTO math_center_subproblems (problem_id, label)
VALUES ($1, $2)
RETURNING id, problem_id, label, created_at
`

type CreateSubproblemParams struct {
	ProblemID int64  `json:"problem_id"`
	Label     string `json:"label"`
}

func (q *Queries) CreateSubproblem(ctx context.Context, arg CreateSubproblemParams) (MathCenterSubproblem, error) {
	row := q.db.QueryRow(ctx, createSubproblem, arg.ProblemID, arg.Label)
	var i MathCenterSubproblem
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProblemsForSeries = `-- name: DeleteProblemsForSeries :exec
DELETE
FROM math_center_problems
WHERE series_id = $1
`

func (q *Queries) DeleteProblemsForSeries(ctx context.Context, seriesID int64) error {
	_, err := q.db.Exec(ctx, deleteProblemsForSeries, seriesID)
	return err
}

const deleteSeries = `-- name: DeleteSeries :execrows
DELETE
FROM math_center_series
WHERE id = $1
`

func (q *Queries) DeleteSeries(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSeries, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProblemCenter = `-- name: GetProblemCenter :one
SELECT p.id             AS problem_id,
       s.id             AS series_id,
       s.math_center_id AS math_center_id
FROM math_center_problems p
         JOIN math_center_series s ON s.id = p.series_id
WHERE p.id = $1
`

type GetProblemCenterRow struct {
	ProblemID    int64 `json:"problem_id"`
	SeriesID     int64 `json:"series_id"`
	MathCenterID int64 `json:"math_center_id"`
}

// Resolve a problem to its series + center, for authorizing coffin actions.
func (q *Queries) GetProblemCenter(ctx context.Context, id int64) (GetProblemCenterRow, error) {
	row := q.db.QueryRow(ctx, getProblemCenter, id)
	var i GetProblemCenterRow
	err := row.Scan(&i.ProblemID, &i.SeriesID, &i.MathCenterID)
	return i, err
}

const getSeries = `-- name: GetSeries :one
SELECT id, math_center_id, number, name, due_at, pdf_object_key, published_at, created_at, tex_source
FROM math_center_series
WHERE id = $1
`

func (q *Queries) GetSeries(ctx context.Context, id int64) (MathCenterSeries, error) {
	row := q.db.QueryRow(ctx, getSeries, id)
	var i MathCenterSeries
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.Number,
		&i.Name,
		&i.DueAt,
		&i.PdfObjectKey,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.TexSource,
	)
	return i, err
}

const getSeriesTex = `-- name: GetSeriesTex :one
SELECT tex_source
FROM math_center_series
WHERE id = $1
`

func (q *Queries) GetSeriesTex(ctx context.Context, id int64) (*string, error) {
	row := q.db.QueryRow(ctx, getSeriesTex, id)
	var tex_source *string
	err := row.Scan(&tex_source)
	return tex_source, err
}

const isStudentInCenter = `-- name: IsStudentInCenter :one
SELECT EXISTS (
    SELECT 1
    FROM math_center_students s
             JOIN math_center_groups g ON g.id = s.group_id
    WHERE s.user_id = $1
      AND g.math_center_id = $2
) AS is_student
`

type IsStudentInCenterParams struct {
	UserID       int64 `json:"user_id"`
	MathCenterID int64 `json:"math_center_id"`
}

func (q *Queries) IsStudentInCenter(ctx context.Context, arg IsStudentInCenterParams) (bool, error) {
	row := q.db.QueryRow(ctx, isStudentInCenter, arg.UserID, arg.MathCenterID)
	var is_student bool
	err := row.Scan(&is_student)
	return is_student, err
}

const isTeacherInCenter = `-- name: IsTeacherInCenter :one
SELECT EXISTS (
    SELECT 1
    FROM math_center_teachers
    WHERE user_id = $1
      AND math_center_id = $2
) AS is_teacher
`

type IsTeacherInCenterParams struct {
	UserID       int64 `json:"user_id"`
	MathCenterID int64 `json:"math_center_id"`
}

func (q *Queries) IsTeacherInCenter(ctx context.Context, arg IsTeacherInCenterParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTeacherInCenter, arg.UserID, arg.MathCenterID)
	var is_teacher bool
	err := row.Scan(&is_teacher)
	return is_teacher, err
}

const listProblemsForSeries = `-- name: ListProblemsForSeries :many
SELECT id, series_id, number, created_at
FROM math_center_problems
WHERE series_id = $1
ORDER BY number ASC
`

func (q *Queries) ListProblemsForSeries(ctx context.Context, seriesID int64) ([]MathCenterProblem, error) {
	rows, err := q.db.Query(ctx, listProblemsForSeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MathCenterProblem{}
	for rows.Next() {
		var i MathCenterProblem
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Number,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblemsForSeriesIDs = `-- name: ListProblemsForSeriesIDs :many
SELECT id, series_id, number, created_at
FROM math_center_problems
WHERE series_id = ANY($1::bigint[])
ORDER BY series_id ASC, number ASC
`

func (q *Queries) ListProblemsForSeriesIDs(ctx context.Context, seriesIds []int64) ([]MathCenterProblem, error) {
	rows, err := q.db.Query(ctx, listProblemsForSeriesIDs, seriesIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MathCenterProblem{}
	for rows.Next() {
		var i MathCenterProblem
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Number,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedSeriesForCenter = `-- name: ListPublishedSeriesForCenter :many
SELECT id, math_center_id, number, name, due_at, pdf_object_key, published_at, created_at, tex_source
FROM math_center_series
WHERE math_center_id = $1
  AND published_at IS NOT NULL
ORDER BY number ASC
`

func (q *Queries) ListPublishedSeriesForCenter(ctx context.Context, mathCenterID int64) ([]MathCenterSeries, error) {
	rows, err := q.db.Query(ctx, listPublishedSeriesForCenter, mathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MathCenterSeries{}
	for rows.Next() {
		var i MathCenterSeries
		if err := rows.Scan(
			&i.ID,
			&i.MathCenterID,
			&i.Number,
			&i.Name,
			&i.DueAt,
			&i.PdfObjectKey,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.TexSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesForCenter = `-- name: ListSeriesForCenter :many
SELECT id, math_center_id, number, name, due_at, pdf_object_key, published_at, created_at, tex_source
FROM math_center_series
WHERE math_center_id = $1
ORDER BY number ASC
`

func (q *Queries) ListSeriesForCenter(ctx context.Context, mathCenterID int64) ([]MathCenterSeries, error) {
	rows, err := q.db.Query(ctx, listSeriesForCenter, mathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MathCenterSeries{}
	for rows.Next() {
		var i MathCenterSeries
		if err := rows.Scan(
			&i.ID,
			&i.MathCenterID,
			&i.Number,
			&i.Name,
			&i.DueAt,
			&i.PdfObjectKey,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.TexSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubproblemsForSeries = `-- name: ListSubproblemsForSeries :many
SELECT s.id        AS id,
       s.problem_id AS problem_id,
       s.label     AS label
FROM math_center_subproblems s
         JOIN math_center_problems p ON p.id = s.problem_id
WHERE p.series_id = $1
ORDER BY p.number ASC, s.label ASC
`

type ListSubproblemsForSeriesRow struct {
	ID        int64  `json:"id"`
	ProblemID int64  `json:"problem_id"`
	Label     string `json:"label"`
}

func (q *Queries) ListSubproblemsForSeries(ctx context.Context, seriesID int64) ([]ListSubproblemsForSeriesRow, error) {
	rows, err := q.db.Query(ctx, listSubproblemsForSeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubproblemsForSeriesRow{}
	for rows.Next() {
		var i ListSubproblemsForSeriesRow
		if err := rows.Scan(&i.ID, &i.ProblemID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubproblemsForSeriesIDs = `-- name: ListSubproblemsForSeriesIDs :many
SELECT s.id         AS id,
       s.problem_id AS problem_id,
       s.label      AS label
FROM math_center_subproblems s
         JOIN math_center_problems p ON p.id = s.problem_id
WHERE p.series_id = ANY($1::bigint[])
ORDER BY p.number ASC, s.label ASC
`

type ListSubproblemsForSeriesIDsRow struct {
	ID        int64  `json:"id"`
	ProblemID int64  `json:"problem_id"`
	Label     string `json:"label"`
}

func (q *Queries) ListSubproblemsForSeriesIDs(ctx context.Context, seriesIds []int64) ([]ListSubproblemsForSeriesIDsRow, error) {
	rows, err := q.db.Query(ctx, listSubproblemsForSeriesIDs, seriesIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubproblemsForSeriesIDsRow{}
	for rows.Next() {
		var i ListSubproblemsForSeriesIDsRow
		if err := rows.Scan(&i.ID, &i.ProblemID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishSeries = `-- name: PublishSeries :one
UPDATE math_center_series
SET pdf_object_key = $2,
    published_at   = NOW()
WHERE id = $1
RETURNING id, math_center_id, number, name, due_at, pdf_object_key, published_at, created_at, tex_source
`

type PublishSeriesParams struct {
	ID           int64   `json:"id"`
	PdfObjectKey *string `json:"pdf_object_key"`
}

// Sets the PDF object key and stamps published_at to NOW(). Used both for
// first-time publishing and re-uploads (we just overwrite; the caller is
// responsible for deleting the prior key first if needed).
func (q *Queries) PublishSeries(ctx context.Context, arg PublishSeriesParams) (MathCenterSeries, error) {
	row := q.db.QueryRow(ctx, publishSeries, arg.ID, arg.PdfObjectKey)
	var i MathCenterSeries
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.Number,
		&i.Name,
		&i.DueAt,
		&i.PdfObjectKey,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.TexSource,
	)
	return i, err
}

const setSeriesTex = `-- name: SetSeriesTex :one
UPDATE math_center_series
SET tex_source  = $2,
    published_at = COALESCE(published_at, NOW())
WHERE id = $1
RETURNING id, math_center_id, number, name, due_at, pdf_object_key, published_at, created_at, tex_source
`

type SetSeriesTexParams struct {
	ID        int64   `json:"id"`
	TexSource *string `json:"tex_source"`
}

// Stores or replaces the raw LaTeX source. Also stamps published_at if
// the series wasn't already published, mirroring the PDF publish flow:
// a series with any rendered content is considered visible to students.
func (q *Queries) SetSeriesTex(ctx context.Context, arg SetSeriesTexParams) (MathCenterSeries, error) {
	row := q.db.QueryRow(ctx, setSeriesTex, arg.ID, arg.TexSource)
	var i MathCenterSeries
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.Number,
		&i.Name,
		&i.DueAt,
		&i.PdfObjectKey,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.TexSource,
	)
	return i, err
}

const updateSeries = `-- name: UpdateSeries :one
UPDATE math_center_series
SET number = $2,
    name   = $3,
    due_at = $4
WHERE id = $1
RETURNING id, math_center_id, number, name, due_at, pdf_object_key, published_at, created_at, tex_source
`

type UpdateSeriesParams struct {
	ID     int64     `json:"id"`
	Number int32     `json:"number"`
	Name   string    `json:"name"`
	DueAt  time.Time `json:"due_at"`
}

func (q *Queries) UpdateSeries(ctx context.Context, arg UpdateSeriesParams) (MathCenterSeries, error) {
	row := q.db.QueryRow(ctx, updateSeries,
		arg.ID,
		arg.Number,
		arg.Name,
		arg.DueAt,
	)
	var i MathCenterSeries
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.Number,
		&i.Name,
		&i.DueAt,
		&i.PdfObjectKey,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.TexSource,
	)
	return i, err
}
