// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: math_center_likbez.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLikbez = `-- name: CreateLikbez :one
INSERT INTO math_center_likbez (math_center_id, term_id, number, title, held_on, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, math_center_id, term_id, number, title, held_on, description, pdf_object_key, tex_source, video_url, published_at, created_at, updated_at
`

type CreateLikbezParams struct {
	MathCenterID int64       `json:"math_center_id"`
	TermID       int64       `json:"term_id"`
	Number       int32       `json:"number"`
	Title        string      `json:"title"`
	HeldOn       pgtype.Date `json:"held_on"`
	Description  string      `json:"description"`
}

func (q *Queries) CreateLikbez(ctx context.Context, arg CreateLikbezParams) (MathCenterLikbez, error) {
	row := q.db.QueryRow(ctx, createLikbez,
		arg.MathCenterID,
		arg.TermID,
		arg.Number,
		arg.Title,
		arg.HeldOn,
		arg.Description,
	)
	var i MathCenterLikbez
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.TermID,
		&i.Number,
		&i.Title,
		&i.HeldOn,
		&i.Description,
		&i.PdfObjectKey,
		&i.TexSource,
		&i.VideoUrl,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLikbez = `-- name: DeleteLikbez :execrows
DELETE FROM math_center_likbez
WHERE id = $1
`

func (q *Queries) DeleteLikbez(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLikbez, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLikbez = `-- name: GetLikbez :one
SELECT l.id, l.math_center_id, l.term_id, l.number, l.title, l.held_on, l.description, l.pdf_object_key, l.tex_source, l.video_url, l.published_at, l.created_at, l.updated_at, t.kind AS term_kind, t.grade AS term_grade
FROM math_center_likbez l
         JOIN math_center_terms t ON t.id = l.term_id
WHERE l.id = $1
`

type GetLikbezRow struct {
	ID           int64       `json:"id"`
	MathCenterID int64       `json:"math_center_id"`
	TermID       int64       `json:"term_id"`
	Number       int32       `json:"number"`
	Title        string      `json:"title"`
	HeldOn       pgtype.Date `json:"held_on"`
	Description  string      `json:"description"`
	PdfObjectKey *string     `json:"pdf_object_key"`
	TexSource    *string     `json:"tex_source"`
	VideoUrl     *string     `json:"video_url"`
	PublishedAt  *time.Time  `json:"published_at"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	TermKind     string      `json:"term_kind"`
	TermGrade    *int32      `json:"term_grade"`
}

func (q *Queries) GetLikbez(ctx context.Context, id int64) (GetLikbezRow, error) {
	row := q.db.QueryRow(ctx, getLikbez, id)
	var i GetLikbezRow
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.TermID,
		&i.Number,
		&i.Title,
		&i.HeldOn,
		&i.Description,
		&i.PdfObjectKey,
		&i.TexSource,
		&i.VideoUrl,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TermKind,
		&i.TermGrade,
	)
	return i, err
}

const listLikbezForCenter = `-- name: ListLikbezForCenter :many
SELECT l.id, l.math_center_id, l.term_id, l.number, l.title, l.held_on, l.description, l.pdf_object_key, l.tex_source, l.video_url, l.published_at, l.created_at, l.updated_at, t.kind AS term_kind, t.grade AS term_grade
FROM math_center_likbez l
         JOIN math_center_terms t ON t.id = l.term_id
WHERE l.math_center_id = $1
ORDER BY l.number DESC
`

type ListLikbezForCenterRow struct {
	ID           int64       `json:"id"`
	MathCenterID int64       `json:"math_center_id"`
	TermID       int64       `json:"term_id"`
	Number       int32       `json:"number"`
	Title        string      `json:"title"`
	HeldOn       pgtype.Date `json:"held_on"`
	Description  string      `json:"description"`
	PdfObjectKey *string     `json:"pdf_object_key"`
	TexSource    *string     `json:"tex_source"`
	VideoUrl     *string     `json:"video_url"`
	PublishedAt  *time.Time  `json:"published_at"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	TermKind     string      `json:"term_kind"`
	TermGrade    *int32      `json:"term_grade"`
}

func (q *Queries) ListLikbezForCenter(ctx context.Context, mathCenterID int64) ([]ListLikbezForCenterRow, error) {
	rows, err := q.db.Query(ctx, listLikbezForCenter, mathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLikbezForCenterRow{}
	for rows.Next() {
		var i ListLikbezForCenterRow
		if err := rows.Scan(
			&i.ID,
			&i.MathCenterID,
			&i.TermID,
			&i.Number,
			&i.Title,
			&i.HeldOn,
			&i.Description,
			&i.PdfObjectKey,
			&i.TexSource,
			&i.VideoUrl,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TermKind,
			&i.TermGrade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedLikbezForCenter = `-- name: ListPublishedLikbezForCenter :many
SELECT l.id, l.math_center_id, l.term_id, l.number, l.title, l.held_on, l.description, l.pdf_object_key, l.tex_source, l.video_url, l.published_at, l.created_at, l.updated_at, t.kind AS term_kind, t.grade AS term_grade
FROM math_center_likbez l
         JOIN math_center_terms t ON t.id = l.term_id
WHERE l.math_center_id = $1
  AND l.published_at IS NOT NULL
ORDER BY l.number DESC
`

type ListPublishedLikbezForCenterRow struct {
	ID           int64       `json:"id"`
	MathCenterID int64       `json:"math_center_id"`
	TermID       int64       `json:"term_id"`
	Number       int32       `json:"number"`
	Title        string      `json:"title"`
	HeldOn       pgtype.Date `json:"held_on"`
	Description  string      `json:"description"`
	PdfObjectKey *string     `json:"pdf_object_key"`
	TexSource    *string     `json:"tex_source"`
	VideoUrl     *string     `json:"video_url"`
	PublishedAt  *time.Time  `json:"published_at"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	TermKind     string      `json:"term_kind"`
	TermGrade    *int32      `json:"term_grade"`
}

func (q *Queries) ListPublishedLikbezForCenter(ctx context.Context, mathCenterID int64) ([]ListPublishedLikbezForCenterRow, error) {
	rows, err := q.db.Query(ctx, listPublishedLikbezForCenter, mathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedLikbezForCenterRow{}
	for rows.Next() {
		var i ListPublishedLikbezForCenterRow
		if err := rows.Scan(
			&i.ID,
			&i.MathCenterID,
			&i.TermID,
			&i.Number,
			&i.Title,
			&i.HeldOn,
			&i.Description,
			&i.PdfObjectKey,
			&i.TexSource,
			&i.VideoUrl,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TermKind,
			&i.TermGrade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMathCenterForLikbezNumbering = `-- name: LockMathCenterForLikbezNumbering :one
SELECT id
FROM math_centers
WHERE id = $1
FOR UPDATE
`

// Serializes automatic per-center numbering without an application-level lock.
func (q *Queries) LockMathCenterForLikbezNumbering(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockMathCenterForLikbezNumbering, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const nextLikbezNumber = `-- name: NextLikbezNumber :one
SELECT COALESCE(MAX(number), 0)::integer + 1 AS number
FROM math_center_likbez
WHERE math_center_id = $1
`

func (q *Queries) NextLikbezNumber(ctx context.Context, mathCenterID int64) (int32, error) {
	row := q.db.QueryRow(ctx, nextLikbezNumber, mathCenterID)
	var number int32
	err := row.Scan(&number)
	return number, err
}

const publishLikbez = `-- name: PublishLikbez :one
UPDATE math_center_likbez
SET published_at = COALESCE(published_at, NOW()),
    updated_at = NOW()
WHERE id = $1
  AND (pdf_object_key IS NOT NULL OR tex_source IS NOT NULL OR video_url IS NOT NULL)
RETURNING id, math_center_id, term_id, number, title, held_on, description, pdf_object_key, tex_source, video_url, published_at, created_at, updated_at
`

func (q *Queries) PublishLikbez(ctx context.Context, id int64) (MathCenterLikbez, error) {
	row := q.db.QueryRow(ctx, publishLikbez, id)
	var i MathCenterLikbez
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.TermID,
		&i.Number,
		&i.Title,
		&i.HeldOn,
		&i.Description,
		&i.PdfObjectKey,
		&i.TexSource,
		&i.VideoUrl,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setLikbezPDF = `-- name: SetLikbezPDF :one
UPDATE math_center_likbez
SET pdf_object_key = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, math_center_id, term_id, number, title, held_on, description, pdf_object_key, tex_source, video_url, published_at, created_at, updated_at
`

type SetLikbezPDFParams struct {
	ID           int64   `json:"id"`
	PdfObjectKey *string `json:"pdf_object_key"`
}

func (q *Queries) SetLikbezPDF(ctx context.Context, arg SetLikbezPDFParams) (MathCenterLikbez, error) {
	row := q.db.QueryRow(ctx, setLikbezPDF, arg.ID, arg.PdfObjectKey)
	var i MathCenterLikbez
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.TermID,
		&i.Number,
		&i.Title,
		&i.HeldOn,
		&i.Description,
		&i.PdfObjectKey,
		&i.TexSource,
		&i.VideoUrl,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setLikbezTex = `-- name: SetLikbezTex :one
UPDATE math_center_likbez
SET tex_source = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, math_center_id, term_id, number, title, held_on, description, pdf_object_key, tex_source, video_url, published_at, created_at, updated_at
`

type SetLikbezTexParams struct {
	ID        int64   `json:"id"`
	TexSource *string `json:"tex_source"`
}

func (q *Queries) SetLikbezTex(ctx context.Context, arg SetLikbezTexParams) (MathCenterLikbez, error) {
	row := q.db.QueryRow(ctx, setLikbezTex, arg.ID, arg.TexSource)
	var i MathCenterLikbez
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.TermID,
		&i.Number,
		&i.Title,
		&i.HeldOn,
		&i.Description,
		&i.PdfObjectKey,
		&i.TexSource,
		&i.VideoUrl,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setLikbezVideoURL = `-- name: SetLikbezVideoURL :one
UPDATE math_center_likbez
SET video_url = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, math_center_id, term_id, number, title, held_on, description, pdf_object_key, tex_source, video_url, published_at, created_at, updated_at
`

type SetLikbezVideoURLParams struct {
	ID       int64   `json:"id"`
	VideoUrl *string `json:"video_url"`
}

func (q *Queries) SetLikbezVideoURL(ctx context.Context, arg SetLikbezVideoURLParams) (MathCenterLikbez, error) {
	row := q.db.QueryRow(ctx, setLikbezVideoURL, arg.ID, arg.VideoUrl)
	var i MathCenterLikbez
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.TermID,
		&i.Number,
		&i.Title,
		&i.HeldOn,
		&i.Description,
		&i.PdfObjectKey,
		&i.TexSource,
		&i.VideoUrl,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unpublishLikbez = `-- name: UnpublishLikbez :one
UPDATE math_center_likbez
SET published_at = NULL,
    updated_at = NOW()
WHERE id = $1
RETURNING id, math_center_id, term_id, number, title, held_on, description, pdf_object_key, tex_source, video_url, published_at, created_at, updated_at
`

func (q *Queries) UnpublishLikbez(ctx context.Context, id int64) (MathCenterLikbez, error) {
	row := q.db.QueryRow(ctx, unpublishLikbez, id)
	var i MathCenterLikbez
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.TermID,
		&i.Number,
		&i.Title,
		&i.HeldOn,
		&i.Description,
		&i.PdfObjectKey,
		&i.TexSource,
		&i.VideoUrl,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLikbez = `-- name: UpdateLikbez :one
UPDATE math_center_likbez
SET term_id = $2,
    number = $3,
    title = $4,
    held_on = $5,
    description = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, math_center_id, term_id, number, title, held_on, description, pdf_object_key, tex_source, video_url, published_at, created_at, updated_at
`

type UpdateLikbezParams struct {
	ID          int64       `json:"id"`
	TermID      int64       `json:"term_id"`
	Number      int32       `json:"number"`
	Title       string      `json:"title"`
	HeldOn      pgtype.Date `json:"held_on"`
	Description string      `json:"description"`
}

func (q *Queries) UpdateLikbez(ctx context.Context, arg UpdateLikbezParams) (MathCenterLikbez, error) {
	row := q.db.QueryRow(ctx, updateLikbez,
		arg.ID,
		arg.TermID,
		arg.Number,
		arg.Title,
		arg.HeldOn,
		arg.Description,
	)
	var i MathCenterLikbez
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.TermID,
		&i.Number,
		&i.Title,
		&i.HeldOn,
		&i.Description,
		&i.PdfObjectKey,
		&i.TexSource,
		&i.VideoUrl,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
