// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: math_center.sql

package store

import (
	"context"
)

const addStudentToGroup = `-- name: AddStudentToGroup :one
INSERT INTO math_center_students (user_id, group_id)
VALUES ($1, $2)
RETURNING id, user_id, group_id, created_at
`

type AddStudentToGroupParams struct {
	UserID  int64 `json:"user_id"`
	GroupID int64 `json:"group_id"`
}

func (q *Queries) AddStudentToGroup(ctx context.Context, arg AddStudentToGroupParams) (MathCenterStudent, error) {
	row := q.db.QueryRow(ctx, addStudentToGroup, arg.UserID, arg.GroupID)
	var i MathCenterStudent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.CreatedAt,
	)
	return i, err
}

const addTeacherToCenter = `-- name: AddTeacherToCenter :one
INSERT INTO math_center_teachers (user_id, math_center_id, is_head_teacher)
VALUES ($1, $2, $3)
RETURNING id, user_id, math_center_id, is_head_teacher, created_at
`

type AddTeacherToCenterParams struct {
	UserID        int64 `json:"user_id"`
	MathCenterID  int64 `json:"math_center_id"`
	IsHeadTeacher bool  `json:"is_head_teacher"`
}

func (q *Queries) AddTeacherToCenter(ctx context.Context, arg AddTeacherToCenterParams) (MathCenterTeacher, error) {
	row := q.db.QueryRow(ctx, addTeacherToCenter, arg.UserID, arg.MathCenterID, arg.IsHeadTeacher)
	var i MathCenterTeacher
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MathCenterID,
		&i.IsHeadTeacher,
		&i.CreatedAt,
	)
	return i, err
}

const createMathCenter = `-- name: CreateMathCenter :one
INSERT INTO math_centers (graduation_year)
VALUES ($1)
RETURNING id, graduation_year, created_at
`

func (q *Queries) CreateMathCenter(ctx context.Context, graduationYear int32) (MathCenter, error) {
	row := q.db.QueryRow(ctx, createMathCenter, graduationYear)
	var i MathCenter
	err := row.Scan(&i.ID, &i.GraduationYear, &i.CreatedAt)
	return i, err
}

const createMathCenterGroup = `-- name: CreateMathCenterGroup :one
INSERT INTO math_center_groups (math_center_id, name)
VALUES ($1, $2)
RETURNING id, math_center_id, name, created_at
`

type CreateMathCenterGroupParams struct {
	MathCenterID int64  `json:"math_center_id"`
	Name         string `json:"name"`
}

func (q *Queries) CreateMathCenterGroup(ctx context.Context, arg CreateMathCenterGroupParams) (MathCenterGroup, error) {
	row := q.db.QueryRow(ctx, createMathCenterGroup, arg.MathCenterID, arg.Name)
	var i MathCenterGroup
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMathCenter = `-- name: DeleteMathCenter :execrows
DELETE
FROM math_centers
WHERE id = $1
`

func (q *Queries) DeleteMathCenter(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMathCenter, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMathCenterGroup = `-- name: DeleteMathCenterGroup :execrows
DELETE
FROM math_center_groups
WHERE id = $1
`

func (q *Queries) DeleteMathCenterGroup(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMathCenterGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGroup = `-- name: GetGroup :one
SELECT id, math_center_id, name, created_at
FROM math_center_groups
WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id int64) (MathCenterGroup, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i MathCenterGroup
	err := row.Scan(
		&i.ID,
		&i.MathCenterID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getMathCenter = `-- name: GetMathCenter :one
SELECT id, graduation_year, created_at
FROM math_centers
WHERE id = $1
`

func (q *Queries) GetMathCenter(ctx context.Context, id int64) (MathCenter, error) {
	row := q.db.QueryRow(ctx, getMathCenter, id)
	var i MathCenter
	err := row.Scan(&i.ID, &i.GraduationYear, &i.CreatedAt)
	return i, err
}

const getStudentByUserID = `-- name: GetStudentByUserID :one
SELECT s.id          AS id,
       s.user_id     AS user_id,
       s.group_id    AS group_id,
       g.name        AS group_name,
       g.math_center_id AS math_center_id,
       mc.graduation_year AS graduation_year
FROM math_center_students s
         JOIN math_center_groups g ON g.id = s.group_id
         JOIN math_centers mc ON mc.id = g.math_center_id
WHERE s.user_id = $1
`

type GetStudentByUserIDRow struct {
	ID             int64  `json:"id"`
	UserID         int64  `json:"user_id"`
	GroupID        int64  `json:"group_id"`
	GroupName      string `json:"group_name"`
	MathCenterID   int64  `json:"math_center_id"`
	GraduationYear int32  `json:"graduation_year"`
}

func (q *Queries) GetStudentByUserID(ctx context.Context, userID int64) (GetStudentByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getStudentByUserID, userID)
	var i GetStudentByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.GroupName,
		&i.MathCenterID,
		&i.GraduationYear,
	)
	return i, err
}

const listCentersForTeacher = `-- name: ListCentersForTeacher :many
SELECT mc.id                AS id,
       mc.graduation_year   AS graduation_year,
       t.is_head_teacher    AS is_head_teacher
FROM math_center_teachers t
         JOIN math_centers mc ON mc.id = t.math_center_id
WHERE t.user_id = $1
ORDER BY mc.graduation_year ASC
`

type ListCentersForTeacherRow struct {
	ID             int64 `json:"id"`
	GraduationYear int32 `json:"graduation_year"`
	IsHeadTeacher  bool  `json:"is_head_teacher"`
}

func (q *Queries) ListCentersForTeacher(ctx context.Context, userID int64) ([]ListCentersForTeacherRow, error) {
	rows, err := q.db.Query(ctx, listCentersForTeacher, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCentersForTeacherRow{}
	for rows.Next() {
		var i ListCentersForTeacherRow
		if err := rows.Scan(&i.ID, &i.GraduationYear, &i.IsHeadTeacher); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForCenter = `-- name: ListGroupsForCenter :many
SELECT id, math_center_id, name, created_at
FROM math_center_groups
WHERE math_center_id = $1
ORDER BY name ASC
`

func (q *Queries) ListGroupsForCenter(ctx context.Context, mathCenterID int64) ([]MathCenterGroup, error) {
	rows, err := q.db.Query(ctx, listGroupsForCenter, mathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MathCenterGroup{}
	for rows.Next() {
		var i MathCenterGroup
		if err := rows.Scan(
			&i.ID,
			&i.MathCenterID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForCenters = `-- name: ListGroupsForCenters :many
SELECT id, math_center_id, name, created_at
FROM math_center_groups
WHERE math_center_id = ANY($1::bigint[])
ORDER BY math_center_id ASC, name ASC
`

func (q *Queries) ListGroupsForCenters(ctx context.Context, centerIds []int64) ([]MathCenterGroup, error) {
	rows, err := q.db.Query(ctx, listGroupsForCenters, centerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MathCenterGroup{}
	for rows.Next() {
		var i MathCenterGroup
		if err := rows.Scan(
			&i.ID,
			&i.MathCenterID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeadTeachersForCenter = `-- name: ListHeadTeachersForCenter :many
SELECT t.id          AS id,
       t.user_id     AS user_id,
       u.first_name  AS first_name,
       u.middle_name AS middle_name,
       u.last_name   AS last_name
FROM math_center_teachers t
         JOIN users u ON u.id = t.user_id
WHERE t.math_center_id = $1
  AND t.is_head_teacher = TRUE
ORDER BY u.last_name ASC, u.first_name ASC
`

type ListHeadTeachersForCenterRow struct {
	ID         int64   `json:"id"`
	UserID     int64   `json:"user_id"`
	FirstName  string  `json:"first_name"`
	MiddleName *string `json:"middle_name"`
	LastName   string  `json:"last_name"`
}

func (q *Queries) ListHeadTeachersForCenter(ctx context.Context, mathCenterID int64) ([]ListHeadTeachersForCenterRow, error) {
	rows, err := q.db.Query(ctx, listHeadTeachersForCenter, mathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHeadTeachersForCenterRow{}
	for rows.Next() {
		var i ListHeadTeachersForCenterRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMathCenters = `-- name: ListMathCenters :many
SELECT id, graduation_year, created_at
FROM math_centers
ORDER BY graduation_year ASC
`

func (q *Queries) ListMathCenters(ctx context.Context) ([]MathCenter, error) {
	rows, err := q.db.Query(ctx, listMathCenters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MathCenter{}
	for rows.Next() {
		var i MathCenter
		if err := rows.Scan(&i.ID, &i.GraduationYear, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsForCenter = `-- name: ListStudentsForCenter :many
SELECT s.id        AS id,
       s.user_id   AS user_id,
       s.group_id  AS group_id,
       g.name      AS group_name,
       u.first_name AS first_name,
       u.middle_name AS middle_name,
       u.last_name AS last_name
FROM math_center_students s
         JOIN math_center_groups g ON g.id = s.group_id
         JOIN users u ON u.id = s.user_id
WHERE g.math_center_id = $1
ORDER BY g.name ASC, u.last_name ASC, u.first_name ASC
`

type ListStudentsForCenterRow struct {
	ID         int64   `json:"id"`
	UserID     int64   `json:"user_id"`
	GroupID    int64   `json:"group_id"`
	GroupName  string  `json:"group_name"`
	FirstName  string  `json:"first_name"`
	MiddleName *string `json:"middle_name"`
	LastName   string  `json:"last_name"`
}

func (q *Queries) ListStudentsForCenter(ctx context.Context, mathCenterID int64) ([]ListStudentsForCenterRow, error) {
	rows, err := q.db.Query(ctx, listStudentsForCenter, mathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentsForCenterRow{}
	for rows.Next() {
		var i ListStudentsForCenterRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.GroupName,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsForCenters = `-- name: ListStudentsForCenters :many
SELECT s.id            AS id,
       s.user_id       AS user_id,
       s.group_id      AS group_id,
       g.name          AS group_name,
       g.math_center_id AS math_center_id,
       u.first_name    AS first_name,
       u.middle_name   AS middle_name,
       u.last_name     AS last_name
FROM math_center_students s
         JOIN math_center_groups g ON g.id = s.group_id
         JOIN users u ON u.id = s.user_id
WHERE g.math_center_id = ANY($1::bigint[])
ORDER BY g.math_center_id ASC, g.name ASC, u.last_name ASC, u.first_name ASC
`

type ListStudentsForCentersRow struct {
	ID           int64   `json:"id"`
	UserID       int64   `json:"user_id"`
	GroupID      int64   `json:"group_id"`
	GroupName    string  `json:"group_name"`
	MathCenterID int64   `json:"math_center_id"`
	FirstName    string  `json:"first_name"`
	MiddleName   *string `json:"middle_name"`
	LastName     string  `json:"last_name"`
}

func (q *Queries) ListStudentsForCenters(ctx context.Context, centerIds []int64) ([]ListStudentsForCentersRow, error) {
	rows, err := q.db.Query(ctx, listStudentsForCenters, centerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentsForCentersRow{}
	for rows.Next() {
		var i ListStudentsForCentersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.GroupName,
			&i.MathCenterID,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeachersForCenter = `-- name: ListTeachersForCenter :many
SELECT t.id              AS id,
       t.user_id         AS user_id,
       t.math_center_id  AS math_center_id,
       t.is_head_teacher AS is_head_teacher,
       u.first_name      AS first_name,
       u.middle_name     AS middle_name,
       u.last_name       AS last_name
FROM math_center_teachers t
         JOIN users u ON u.id = t.user_id
WHERE t.math_center_id = $1
ORDER BY t.is_head_teacher DESC, u.last_name ASC, u.first_name ASC
`

type ListTeachersForCenterRow struct {
	ID            int64   `json:"id"`
	UserID        int64   `json:"user_id"`
	MathCenterID  int64   `json:"math_center_id"`
	IsHeadTeacher bool    `json:"is_head_teacher"`
	FirstName     string  `json:"first_name"`
	MiddleName    *string `json:"middle_name"`
	LastName      string  `json:"last_name"`
}

func (q *Queries) ListTeachersForCenter(ctx context.Context, mathCenterID int64) ([]ListTeachersForCenterRow, error) {
	rows, err := q.db.Query(ctx, listTeachersForCenter, mathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeachersForCenterRow{}
	for rows.Next() {
		var i ListTeachersForCenterRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MathCenterID,
			&i.IsHeadTeacher,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeachersForCenters = `-- name: ListTeachersForCenters :many
SELECT t.id              AS id,
       t.user_id         AS user_id,
       t.math_center_id  AS math_center_id,
       t.is_head_teacher AS is_head_teacher,
       u.first_name      AS first_name,
       u.middle_name     AS middle_name,
       u.last_name       AS last_name
FROM math_center_teachers t
         JOIN users u ON u.id = t.user_id
WHERE t.math_center_id = ANY($1::bigint[])
ORDER BY t.math_center_id ASC, t.is_head_teacher DESC, u.last_name ASC, u.first_name ASC
`

type ListTeachersForCentersRow struct {
	ID            int64   `json:"id"`
	UserID        int64   `json:"user_id"`
	MathCenterID  int64   `json:"math_center_id"`
	IsHeadTeacher bool    `json:"is_head_teacher"`
	FirstName     string  `json:"first_name"`
	MiddleName    *string `json:"middle_name"`
	LastName      string  `json:"last_name"`
}

func (q *Queries) ListTeachersForCenters(ctx context.Context, centerIds []int64) ([]ListTeachersForCentersRow, error) {
	rows, err := q.db.Query(ctx, listTeachersForCenters, centerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeachersForCentersRow{}
	for rows.Next() {
		var i ListTeachersForCentersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MathCenterID,
			&i.IsHeadTeacher,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeStudent = `-- name: RemoveStudent :execrows
DELETE
FROM math_center_students
WHERE id = $1
`

func (q *Queries) RemoveStudent(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, removeStudent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeTeacher = `-- name: RemoveTeacher :execrows
DELETE
FROM math_center_teachers
WHERE id = $1
`

func (q *Queries) RemoveTeacher(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, removeTeacher, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTeacherHead = `-- name: SetTeacherHead :execrows
UPDATE math_center_teachers
SET is_head_teacher = $2
WHERE id = $1
`

type SetTeacherHeadParams struct {
	ID            int64 `json:"id"`
	IsHeadTeacher bool  `json:"is_head_teacher"`
}

func (q *Queries) SetTeacherHead(ctx context.Context, arg SetTeacherHeadParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTeacherHead, arg.ID, arg.IsHeadTeacher)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
