// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type HomeworkThread struct {
	ID                    int64      `json:"id"`
	StudentUserID         int64      `json:"student_user_id"`
	SubproblemID          int64      `json:"subproblem_id"`
	SeriesID              int64      `json:"series_id"`
	MathCenterID          int64      `json:"math_center_id"`
	CurrentStatus         string     `json:"current_status"`
	CurrentAttemptEventID *int64     `json:"current_attempt_event_id"`
	CurrentGradeEventID   *int64     `json:"current_grade_event_id"`
	LastGraderUserID      *int64     `json:"last_grader_user_id"`
	ClaimHolderUserID     *int64     `json:"claim_holder_user_id"`
	ClaimExpiresAt        *time.Time `json:"claim_expires_at"`
	CreatedAt             time.Time  `json:"created_at"`
	UpdatedAt             time.Time  `json:"updated_at"`
	LastGraderName        string     `json:"last_grader_name"`
}

type HomeworkThreadEvent struct {
	ID                   int64     `json:"id"`
	ThreadID             int64     `json:"thread_id"`
	EventUuid            string    `json:"event_uuid"`
	Kind                 string    `json:"kind"`
	ActorUserID          int64     `json:"actor_user_id"`
	Body                 string    `json:"body"`
	Verdict              *string   `json:"verdict"`
	RefersToEventID      *int64    `json:"refers_to_event_id"`
	CreatedAt            time.Time `json:"created_at"`
	IsOffline            bool      `json:"is_offline"`
	CreditedGraderUserID *int64    `json:"credited_grader_user_id"`
	CreditedGraderName   string    `json:"credited_grader_name"`
	GoogleSheetLinkID    *int64    `json:"google_sheet_link_id"`
	GoogleSheetCell      string    `json:"google_sheet_cell"`
	GoogleSheetVersion   string    `json:"google_sheet_version"`
}

type HomeworkThreadEventPhoto struct {
	EventID     int64     `json:"event_id"`
	Idx         int32     `json:"idx"`
	ObjectKey   string    `json:"object_key"`
	SizeBytes   int64     `json:"size_bytes"`
	ContentType string    `json:"content_type"`
	CreatedAt   time.Time `json:"created_at"`
}

type HomeworkThreadNote struct {
	ID           int64     `json:"id"`
	ThreadID     int64     `json:"thread_id"`
	AuthorUserID int64     `json:"author_user_id"`
	Body         string    `json:"body"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type InvitationToken struct {
	ID           int64           `json:"id"`
	Token        string          `json:"token"`
	Description  string          `json:"description"`
	MaxUses      int32           `json:"max_uses"`
	ExpiresAt    time.Time       `json:"expires_at"`
	CreatedAt    time.Time       `json:"created_at"`
	Preset       json.RawMessage `json:"preset"`
	MathCenterID *int64          `json:"math_center_id"`
}

type MathCenter struct {
	ID             int64     `json:"id"`
	GraduationYear int32     `json:"graduation_year"`
	CreatedAt      time.Time `json:"created_at"`
}

type MathCenterGoogleSheetLink struct {
	ID                   int64           `json:"id"`
	TermID               int64           `json:"term_id"`
	SpreadsheetID        string          `json:"spreadsheet_id"`
	SheetID              int64           `json:"sheet_id"`
	SheetTitle           string          `json:"sheet_title"`
	Enabled              bool            `json:"enabled"`
	LastGoogleVersion    string          `json:"last_google_version"`
	LastGoogleModifiedAt *time.Time      `json:"last_google_modified_at"`
	LastSnapshot         json.RawMessage `json:"last_snapshot"`
	CreatedByUserID      int64           `json:"created_by_user_id"`
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
	GroupID              *int64          `json:"group_id"`
	LinkKind             string          `json:"link_kind"`
	SyncDirection        string          `json:"sync_direction"`
}

type MathCenterGoogleSheetOutbox struct {
	ID          int64      `json:"id"`
	ThreadID    int64      `json:"thread_id"`
	Attempts    int32      `json:"attempts"`
	AvailableAt time.Time  `json:"available_at"`
	LockedAt    *time.Time `json:"locked_at"`
	LastError   string     `json:"last_error"`
	CompletedAt *time.Time `json:"completed_at"`
	CreatedAt   time.Time  `json:"created_at"`
}

type MathCenterGoogleSheetSyncRun struct {
	ID                int64           `json:"id"`
	LinkID            int64           `json:"link_id"`
	RequestedByUserID int64           `json:"requested_by_user_id"`
	Status            string          `json:"status"`
	GoogleVersion     string          `json:"google_version"`
	GoogleModifiedAt  *time.Time      `json:"google_modified_at"`
	Summary           json.RawMessage `json:"summary"`
	ErrorMessage      string          `json:"error_message"`
	StartedAt         time.Time       `json:"started_at"`
	FinishedAt        *time.Time      `json:"finished_at"`
}

type MathCenterGroup struct {
	ID                  int64     `json:"id"`
	MathCenterID        int64     `json:"math_center_id"`
	Name                string    `json:"name"`
	CreatedAt           time.Time `json:"created_at"`
	TermID              int64     `json:"term_id"`
	RazborDefaultVideo  bool      `json:"razbor_default_video"`
	RazborDefaultPdfTex bool      `json:"razbor_default_pdf_tex"`
}

type MathCenterLatexSetting struct {
	MathCenterID int64     `json:"math_center_id"`
	Preamble     string    `json:"preamble"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type MathCenterLikbez struct {
	ID           int64       `json:"id"`
	MathCenterID int64       `json:"math_center_id"`
	TermID       int64       `json:"term_id"`
	Number       int32       `json:"number"`
	Title        string      `json:"title"`
	HeldOn       pgtype.Date `json:"held_on"`
	Description  string      `json:"description"`
	PdfObjectKey *string     `json:"pdf_object_key"`
	TexSource    *string     `json:"tex_source"`
	VideoUrl     *string     `json:"video_url"`
	PublishedAt  *time.Time  `json:"published_at"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type MathCenterProblem struct {
	ID        int64     `json:"id"`
	SeriesID  int64     `json:"series_id"`
	Number    int32     `json:"number"`
	CreatedAt time.Time `json:"created_at"`
}

type MathCenterSeries struct {
	ID           int64      `json:"id"`
	MathCenterID int64      `json:"math_center_id"`
	Number       int32      `json:"number"`
	Name         string     `json:"name"`
	DueAt        time.Time  `json:"due_at"`
	PdfObjectKey *string    `json:"pdf_object_key"`
	PublishedAt  *time.Time `json:"published_at"`
	CreatedAt    time.Time  `json:"created_at"`
	TexSource    *string    `json:"tex_source"`
	TermID       int64      `json:"term_id"`
}

type MathCenterSolutionGroup struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

type MathCenterStudent struct {
	ID                  int64     `json:"id"`
	UserID              int64     `json:"user_id"`
	GroupID             int64     `json:"group_id"`
	CreatedAt           time.Time `json:"created_at"`
	TermID              int64     `json:"term_id"`
	CanViewRazbors      bool      `json:"can_view_razbors"`
	RazborDefaultVideo  bool      `json:"razbor_default_video"`
	RazborDefaultPdfTex bool      `json:"razbor_default_pdf_tex"`
}

type MathCenterStudentNote struct {
	ID            int64     `json:"id"`
	StudentUserID int64     `json:"student_user_id"`
	MathCenterID  int64     `json:"math_center_id"`
	AuthorUserID  int64     `json:"author_user_id"`
	Body          string    `json:"body"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type MathCenterStudentSeriesRazborAccess struct {
	StudentUserID int64     `json:"student_user_id"`
	SeriesID      int64     `json:"series_id"`
	CanViewVideo  bool      `json:"can_view_video"`
	CanViewPdfTex bool      `json:"can_view_pdf_tex"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type MathCenterSubproblem struct {
	ID        int64     `json:"id"`
	ProblemID int64     `json:"problem_id"`
	Label     string    `json:"label"`
	CreatedAt time.Time `json:"created_at"`
}

type MathCenterSubproblemSolution struct {
	ID                   int64      `json:"id"`
	SubproblemID         int64      `json:"subproblem_id"`
	IsCoffin             bool       `json:"is_coffin"`
	ReleasedAt           *time.Time `json:"released_at"`
	SolutionTexSource    *string    `json:"solution_tex_source"`
	SolutionPdfObjectKey *string    `json:"solution_pdf_object_key"`
	SolutionLink         *string    `json:"solution_link"`
	CreatedAt            time.Time  `json:"created_at"`
	UpdatedAt            time.Time  `json:"updated_at"`
	SolutionGroupID      *int64     `json:"solution_group_id"`
	PublishedAt          *time.Time `json:"published_at"`
}

type MathCenterTeacher struct {
	ID            int64     `json:"id"`
	UserID        int64     `json:"user_id"`
	MathCenterID  int64     `json:"math_center_id"`
	IsHeadTeacher bool      `json:"is_head_teacher"`
	CreatedAt     time.Time `json:"created_at"`
}

type MathCenterTerm struct {
	ID           int64      `json:"id"`
	MathCenterID int64      `json:"math_center_id"`
	Kind         string     `json:"kind"`
	Grade        *int32     `json:"grade"`
	IsActive     bool       `json:"is_active"`
	CreatedAt    time.Time  `json:"created_at"`
	ArchivedAt   *time.Time `json:"archived_at"`
}

type RefreshToken struct {
	ID           int64      `json:"id"`
	UserID       int64      `json:"user_id"`
	TokenHash    []byte     `json:"token_hash"`
	ExpiresAt    time.Time  `json:"expires_at"`
	RevokedAt    *time.Time `json:"revoked_at"`
	ReplacedByID *int64     `json:"replaced_by_id"`
	CreatedAt    time.Time  `json:"created_at"`
}

type User struct {
	ID                int64     `json:"id"`
	Username          string    `json:"username"`
	PasswordHash      string    `json:"-"`
	FirstName         string    `json:"first_name"`
	MiddleName        *string   `json:"middle_name"`
	LastName          string    `json:"last_name"`
	InvitationTokenID *int64    `json:"invitation_token_id"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	IsAdmin           bool      `json:"is_admin"`
	IsMathCenter      bool      `json:"is_math_center"`
}
