// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"
)

type InvitationToken struct {
	ID          int64     `json:"id"`
	Token       string    `json:"token"`
	Description string    `json:"description"`
	MaxUses     int32     `json:"max_uses"`
	ExpiresAt   time.Time `json:"expires_at"`
	CreatedAt   time.Time `json:"created_at"`
}

type MathCenter struct {
	ID             int64     `json:"id"`
	GraduationYear int32     `json:"graduation_year"`
	CreatedAt      time.Time `json:"created_at"`
}

type MathCenterGroup struct {
	ID           int64     `json:"id"`
	MathCenterID int64     `json:"math_center_id"`
	Name         string    `json:"name"`
	CreatedAt    time.Time `json:"created_at"`
}

type MathCenterProblem struct {
	ID        int64     `json:"id"`
	SeriesID  int64     `json:"series_id"`
	Number    int32     `json:"number"`
	CreatedAt time.Time `json:"created_at"`
}

type MathCenterSeries struct {
	ID           int64      `json:"id"`
	MathCenterID int64      `json:"math_center_id"`
	Number       int32      `json:"number"`
	Name         string     `json:"name"`
	DueAt        time.Time  `json:"due_at"`
	PdfObjectKey *string    `json:"pdf_object_key"`
	PublishedAt  *time.Time `json:"published_at"`
	CreatedAt    time.Time  `json:"created_at"`
}

type MathCenterStudent struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	GroupID   int64     `json:"group_id"`
	CreatedAt time.Time `json:"created_at"`
}

type MathCenterSubproblem struct {
	ID        int64     `json:"id"`
	ProblemID int64     `json:"problem_id"`
	Label     string    `json:"label"`
	CreatedAt time.Time `json:"created_at"`
}

type MathCenterTeacher struct {
	ID            int64     `json:"id"`
	UserID        int64     `json:"user_id"`
	MathCenterID  int64     `json:"math_center_id"`
	IsHeadTeacher bool      `json:"is_head_teacher"`
	CreatedAt     time.Time `json:"created_at"`
}

type RefreshToken struct {
	ID           int64      `json:"id"`
	UserID       int64      `json:"user_id"`
	TokenHash    []byte     `json:"token_hash"`
	ExpiresAt    time.Time  `json:"expires_at"`
	RevokedAt    *time.Time `json:"revoked_at"`
	ReplacedByID *int64     `json:"replaced_by_id"`
	CreatedAt    time.Time  `json:"created_at"`
}

type User struct {
	ID                int64     `json:"id"`
	Username          string    `json:"username"`
	PasswordHash      string    `json:"-"`
	FirstName         string    `json:"first_name"`
	MiddleName        *string   `json:"middle_name"`
	LastName          string    `json:"last_name"`
	InvitationTokenID int64     `json:"invitation_token_id"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	IsAdmin           bool      `json:"is_admin"`
}
