// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subproblem_solutions.sql

package store

import (
	"context"
	"time"
)

const createSolutionGroup = `-- name: CreateSolutionGroup :one
INSERT INTO math_center_solution_groups DEFAULT VALUES
RETURNING id
`

// Mint a fresh shared-разбор group id.
func (q *Queries) CreateSolutionGroup(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, createSolutionGroup)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteSubproblemSolution = `-- name: DeleteSubproblemSolution :execrows
DELETE
FROM math_center_subproblem_solutions
WHERE subproblem_id = $1
`

// Used when unmarking a coffin that carries no разбор content (clean up the row).
func (q *Queries) DeleteSubproblemSolution(ctx context.Context, subproblemID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSubproblemSolution, subproblemID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSubproblemSolution = `-- name: GetSubproblemSolution :one
SELECT id, subproblem_id, is_coffin, released_at, solution_tex_source, solution_pdf_object_key, solution_link, created_at, updated_at, solution_group_id
FROM math_center_subproblem_solutions
WHERE subproblem_id = $1
`

func (q *Queries) GetSubproblemSolution(ctx context.Context, subproblemID int64) (MathCenterSubproblemSolution, error) {
	row := q.db.QueryRow(ctx, getSubproblemSolution, subproblemID)
	var i MathCenterSubproblemSolution
	err := row.Scan(
		&i.ID,
		&i.SubproblemID,
		&i.IsCoffin,
		&i.ReleasedAt,
		&i.SolutionTexSource,
		&i.SolutionPdfObjectKey,
		&i.SolutionLink,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SolutionGroupID,
	)
	return i, err
}

const getSubproblemSolutionCenter = `-- name: GetSubproblemSolutionCenter :one
SELECT sp.id            AS subproblem_id,
       sp.label         AS subproblem_label,
       p.id             AS problem_id,
       p.number         AS problem_number,
       s.id             AS series_id,
       s.math_center_id AS math_center_id,
       s.due_at         AS series_due_at
FROM math_center_subproblems sp
         JOIN math_center_problems p ON p.id = sp.problem_id
         JOIN math_center_series s ON s.id = p.series_id
WHERE sp.id = $1
`

type GetSubproblemSolutionCenterRow struct {
	SubproblemID    int64     `json:"subproblem_id"`
	SubproblemLabel string    `json:"subproblem_label"`
	ProblemID       int64     `json:"problem_id"`
	ProblemNumber   int32     `json:"problem_number"`
	SeriesID        int64     `json:"series_id"`
	MathCenterID    int64     `json:"math_center_id"`
	SeriesDueAt     time.Time `json:"series_due_at"`
}

// Resolve a subproblem to its problem + series + center (+ the series deadline),
// for authorizing coffin/разбор actions and gating student visibility. Returns
// the row even when no solution row exists yet.
func (q *Queries) GetSubproblemSolutionCenter(ctx context.Context, id int64) (GetSubproblemSolutionCenterRow, error) {
	row := q.db.QueryRow(ctx, getSubproblemSolutionCenter, id)
	var i GetSubproblemSolutionCenterRow
	err := row.Scan(
		&i.SubproblemID,
		&i.SubproblemLabel,
		&i.ProblemID,
		&i.ProblemNumber,
		&i.SeriesID,
		&i.MathCenterID,
		&i.SeriesDueAt,
	)
	return i, err
}

const listCenterCoffins = `-- name: ListCenterCoffins :many
SELECT ss.subproblem_id           AS subproblem_id,
       ss.is_coffin               AS is_coffin,
       ss.released_at             AS released_at,
       ss.solution_tex_source     AS solution_tex_source,
       ss.solution_pdf_object_key AS solution_pdf_object_key,
       ss.solution_link           AS solution_link,
       ss.created_at              AS created_at,
       sp.label                   AS subproblem_label,
       p.id                       AS problem_id,
       p.number                   AS problem_number,
       s.id                       AS series_id,
       s.number                   AS series_number,
       s.name                     AS series_name,
       s.due_at                   AS series_due_at,
       s.math_center_id           AS math_center_id
FROM math_center_subproblem_solutions ss
         JOIN math_center_subproblems sp ON sp.id = ss.subproblem_id
         JOIN math_center_problems p ON p.id = sp.problem_id
         JOIN math_center_series s ON s.id = p.series_id
WHERE s.math_center_id = $1
  AND ss.is_coffin = true
ORDER BY s.number DESC, p.number ASC, sp.label ASC
`

type ListCenterCoffinsRow struct {
	SubproblemID         int64      `json:"subproblem_id"`
	IsCoffin             bool       `json:"is_coffin"`
	ReleasedAt           *time.Time `json:"released_at"`
	SolutionTexSource    *string    `json:"solution_tex_source"`
	SolutionPdfObjectKey *string    `json:"solution_pdf_object_key"`
	SolutionLink         *string    `json:"solution_link"`
	CreatedAt            time.Time  `json:"created_at"`
	SubproblemLabel      string     `json:"subproblem_label"`
	ProblemID            int64      `json:"problem_id"`
	ProblemNumber        int32      `json:"problem_number"`
	SeriesID             int64      `json:"series_id"`
	SeriesNumber         int32      `json:"series_number"`
	SeriesName           string     `json:"series_name"`
	SeriesDueAt          time.Time  `json:"series_due_at"`
	MathCenterID         int64      `json:"math_center_id"`
}

// Every coffin subproblem in a center with the labels the Гробы tab needs,
// newest series first. Used by the center-wide "Гробы" tab.
func (q *Queries) ListCenterCoffins(ctx context.Context, mathCenterID int64) ([]ListCenterCoffinsRow, error) {
	rows, err := q.db.Query(ctx, listCenterCoffins, mathCenterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCenterCoffinsRow{}
	for rows.Next() {
		var i ListCenterCoffinsRow
		if err := rows.Scan(
			&i.SubproblemID,
			&i.IsCoffin,
			&i.ReleasedAt,
			&i.SolutionTexSource,
			&i.SolutionPdfObjectKey,
			&i.SolutionLink,
			&i.CreatedAt,
			&i.SubproblemLabel,
			&i.ProblemID,
			&i.ProblemNumber,
			&i.SeriesID,
			&i.SeriesNumber,
			&i.SeriesName,
			&i.SeriesDueAt,
			&i.MathCenterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoffinSubproblemsForStudent = `-- name: ListCoffinSubproblemsForStudent :many
SELECT ss.subproblem_id                              AS subproblem_id,
       ss.released_at                                AS released_at,
       sp.label                                      AS subproblem_label,
       p.number                                      AS problem_number,
       COALESCE(t.id, 0)::bigint                     AS thread_id,
       COALESCE(t.current_status, 'ungraded')        AS current_status,
       (t.claim_holder_user_id IS NOT NULL
           AND t.claim_expires_at > now())::boolean  AS being_graded
FROM math_center_subproblem_solutions ss
         JOIN math_center_subproblems sp ON sp.id = ss.subproblem_id
         JOIN math_center_problems p ON p.id = sp.problem_id
         JOIN math_center_series s ON s.id = p.series_id
         LEFT JOIN homework_thread t
                   ON t.subproblem_id = sp.id
                       AND t.student_user_id = $2::bigint
WHERE s.math_center_id = $1
  AND ss.is_coffin = true
ORDER BY s.number DESC, p.number ASC, sp.label ASC
`

type ListCoffinSubproblemsForStudentParams struct {
	MathCenterID  int64 `json:"math_center_id"`
	StudentUserID int64 `json:"student_user_id"`
}

type ListCoffinSubproblemsForStudentRow struct {
	SubproblemID    int64      `json:"subproblem_id"`
	ReleasedAt      *time.Time `json:"released_at"`
	SubproblemLabel string     `json:"subproblem_label"`
	ProblemNumber   int32      `json:"problem_number"`
	ThreadID        int64      `json:"thread_id"`
	CurrentStatus   string     `json:"current_status"`
	BeingGraded     bool       `json:"being_graded"`
}

// Each coffin subproblem in a center with the calling student's thread status,
// so the Гробы tab can render a tile + a "Сдать" link.
func (q *Queries) ListCoffinSubproblemsForStudent(ctx context.Context, arg ListCoffinSubproblemsForStudentParams) ([]ListCoffinSubproblemsForStudentRow, error) {
	rows, err := q.db.Query(ctx, listCoffinSubproblemsForStudent, arg.MathCenterID, arg.StudentUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoffinSubproblemsForStudentRow{}
	for rows.Next() {
		var i ListCoffinSubproblemsForStudentRow
		if err := rows.Scan(
			&i.SubproblemID,
			&i.ReleasedAt,
			&i.SubproblemLabel,
			&i.ProblemNumber,
			&i.ThreadID,
			&i.CurrentStatus,
			&i.BeingGraded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubproblemSolutionsForSeries = `-- name: ListSubproblemSolutionsForSeries :many
SELECT ss.subproblem_id                                   AS subproblem_id,
       sp.problem_id                                      AS problem_id,
       ss.is_coffin                                       AS is_coffin,
       ss.released_at                                     AS released_at,
       (ss.solution_tex_source IS NOT NULL)::boolean      AS has_solution_tex,
       (ss.solution_pdf_object_key IS NOT NULL)::boolean  AS has_solution_pdf,
       ss.solution_link                                   AS solution_link,
       ss.solution_group_id                               AS solution_group_id
FROM math_center_subproblem_solutions ss
         JOIN math_center_subproblems sp ON sp.id = ss.subproblem_id
         JOIN math_center_problems p ON p.id = sp.problem_id
WHERE p.series_id = $1
ORDER BY p.number ASC, sp.label ASC
`

type ListSubproblemSolutionsForSeriesRow struct {
	SubproblemID    int64      `json:"subproblem_id"`
	ProblemID       int64      `json:"problem_id"`
	IsCoffin        bool       `json:"is_coffin"`
	ReleasedAt      *time.Time `json:"released_at"`
	HasSolutionTex  bool       `json:"has_solution_tex"`
	HasSolutionPdf  bool       `json:"has_solution_pdf"`
	SolutionLink    *string    `json:"solution_link"`
	SolutionGroupID *int64     `json:"solution_group_id"`
}

// Per-subproblem разбор/coffin metadata for one series, so the teacher Разбор
// tab and student views can show "has разбор / released / is coffin" per
// subproblem without N+1 fetches. Only subproblems with a row appear.
func (q *Queries) ListSubproblemSolutionsForSeries(ctx context.Context, seriesID int64) ([]ListSubproblemSolutionsForSeriesRow, error) {
	rows, err := q.db.Query(ctx, listSubproblemSolutionsForSeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubproblemSolutionsForSeriesRow{}
	for rows.Next() {
		var i ListSubproblemSolutionsForSeriesRow
		if err := rows.Scan(
			&i.SubproblemID,
			&i.ProblemID,
			&i.IsCoffin,
			&i.ReleasedAt,
			&i.HasSolutionTex,
			&i.HasSolutionPdf,
			&i.SolutionLink,
			&i.SolutionGroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubproblemSolutionsForSeriesIDs = `-- name: ListSubproblemSolutionsForSeriesIDs :many
SELECT ss.subproblem_id                                   AS subproblem_id,
       sp.problem_id                                      AS problem_id,
       ss.is_coffin                                       AS is_coffin,
       ss.released_at                                     AS released_at,
       (ss.solution_tex_source IS NOT NULL)::boolean      AS has_solution_tex,
       (ss.solution_pdf_object_key IS NOT NULL)::boolean  AS has_solution_pdf,
       ss.solution_link                                   AS solution_link,
       ss.solution_group_id                               AS solution_group_id
FROM math_center_subproblem_solutions ss
         JOIN math_center_subproblems sp ON sp.id = ss.subproblem_id
         JOIN math_center_problems p ON p.id = sp.problem_id
WHERE p.series_id = ANY ($1::bigint[])
ORDER BY p.number ASC, sp.label ASC
`

type ListSubproblemSolutionsForSeriesIDsRow struct {
	SubproblemID    int64      `json:"subproblem_id"`
	ProblemID       int64      `json:"problem_id"`
	IsCoffin        bool       `json:"is_coffin"`
	ReleasedAt      *time.Time `json:"released_at"`
	HasSolutionTex  bool       `json:"has_solution_tex"`
	HasSolutionPdf  bool       `json:"has_solution_pdf"`
	SolutionLink    *string    `json:"solution_link"`
	SolutionGroupID *int64     `json:"solution_group_id"`
}

// Batched variant of the above for the series-LIST endpoint, so the list also
// carries per-subproblem разбор/coffin metadata (one query for all series).
func (q *Queries) ListSubproblemSolutionsForSeriesIDs(ctx context.Context, seriesIds []int64) ([]ListSubproblemSolutionsForSeriesIDsRow, error) {
	rows, err := q.db.Query(ctx, listSubproblemSolutionsForSeriesIDs, seriesIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubproblemSolutionsForSeriesIDsRow{}
	for rows.Next() {
		var i ListSubproblemSolutionsForSeriesIDsRow
		if err := rows.Scan(
			&i.SubproblemID,
			&i.ProblemID,
			&i.IsCoffin,
			&i.ReleasedAt,
			&i.HasSolutionTex,
			&i.HasSolutionPdf,
			&i.SolutionLink,
			&i.SolutionGroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseSubproblemSolution = `-- name: ReleaseSubproblemSolution :one
UPDATE math_center_subproblem_solutions
SET released_at = COALESCE(released_at, NOW()),
    updated_at  = NOW()
WHERE subproblem_id = $1
RETURNING id, subproblem_id, is_coffin, released_at, solution_tex_source, solution_pdf_object_key, solution_link, created_at, updated_at, solution_group_id
`

// Stamp released_at (first release wins) — closes a coffin's submission window
// and makes its разбор available.
func (q *Queries) ReleaseSubproblemSolution(ctx context.Context, subproblemID int64) (MathCenterSubproblemSolution, error) {
	row := q.db.QueryRow(ctx, releaseSubproblemSolution, subproblemID)
	var i MathCenterSubproblemSolution
	err := row.Scan(
		&i.ID,
		&i.SubproblemID,
		&i.IsCoffin,
		&i.ReleasedAt,
		&i.SolutionTexSource,
		&i.SolutionPdfObjectKey,
		&i.SolutionLink,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SolutionGroupID,
	)
	return i, err
}

const setSubproblemSolutionGroup = `-- name: SetSubproblemSolutionGroup :exec
UPDATE math_center_subproblem_solutions
SET solution_group_id = $1::bigint,
    updated_at        = NOW()
WHERE subproblem_id = ANY ($2::bigint[])
`

type SetSubproblemSolutionGroupParams struct {
	GroupID       int64   `json:"group_id"`
	SubproblemIds []int64 `json:"subproblem_ids"`
}

// Assign a (just-minted) group to every subproblem in the set. The solution
// rows must already exist (content was set first); only existing rows update.
func (q *Queries) SetSubproblemSolutionGroup(ctx context.Context, arg SetSubproblemSolutionGroupParams) error {
	_, err := q.db.Exec(ctx, setSubproblemSolutionGroup, arg.GroupID, arg.SubproblemIds)
	return err
}

const setSubproblemSolutionLink = `-- name: SetSubproblemSolutionLink :one
INSERT INTO math_center_subproblem_solutions (subproblem_id, solution_link)
VALUES ($1, $2)
ON CONFLICT (subproblem_id)
    DO UPDATE SET solution_link = EXCLUDED.solution_link, updated_at = NOW()
RETURNING id, subproblem_id, is_coffin, released_at, solution_tex_source, solution_pdf_object_key, solution_link, created_at, updated_at, solution_group_id
`

type SetSubproblemSolutionLinkParams struct {
	SubproblemID int64   `json:"subproblem_id"`
	SolutionLink *string `json:"solution_link"`
}

func (q *Queries) SetSubproblemSolutionLink(ctx context.Context, arg SetSubproblemSolutionLinkParams) (MathCenterSubproblemSolution, error) {
	row := q.db.QueryRow(ctx, setSubproblemSolutionLink, arg.SubproblemID, arg.SolutionLink)
	var i MathCenterSubproblemSolution
	err := row.Scan(
		&i.ID,
		&i.SubproblemID,
		&i.IsCoffin,
		&i.ReleasedAt,
		&i.SolutionTexSource,
		&i.SolutionPdfObjectKey,
		&i.SolutionLink,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SolutionGroupID,
	)
	return i, err
}

const setSubproblemSolutionPdf = `-- name: SetSubproblemSolutionPdf :one
INSERT INTO math_center_subproblem_solutions (subproblem_id, solution_pdf_object_key)
VALUES ($1, $2)
ON CONFLICT (subproblem_id)
    DO UPDATE SET solution_pdf_object_key = EXCLUDED.solution_pdf_object_key, updated_at = NOW()
RETURNING id, subproblem_id, is_coffin, released_at, solution_tex_source, solution_pdf_object_key, solution_link, created_at, updated_at, solution_group_id
`

type SetSubproblemSolutionPdfParams struct {
	SubproblemID         int64   `json:"subproblem_id"`
	SolutionPdfObjectKey *string `json:"solution_pdf_object_key"`
}

func (q *Queries) SetSubproblemSolutionPdf(ctx context.Context, arg SetSubproblemSolutionPdfParams) (MathCenterSubproblemSolution, error) {
	row := q.db.QueryRow(ctx, setSubproblemSolutionPdf, arg.SubproblemID, arg.SolutionPdfObjectKey)
	var i MathCenterSubproblemSolution
	err := row.Scan(
		&i.ID,
		&i.SubproblemID,
		&i.IsCoffin,
		&i.ReleasedAt,
		&i.SolutionTexSource,
		&i.SolutionPdfObjectKey,
		&i.SolutionLink,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SolutionGroupID,
	)
	return i, err
}

const setSubproblemSolutionTex = `-- name: SetSubproblemSolutionTex :one
INSERT INTO math_center_subproblem_solutions (subproblem_id, solution_tex_source)
VALUES ($1, $2)
ON CONFLICT (subproblem_id)
    DO UPDATE SET solution_tex_source = EXCLUDED.solution_tex_source, updated_at = NOW()
RETURNING id, subproblem_id, is_coffin, released_at, solution_tex_source, solution_pdf_object_key, solution_link, created_at, updated_at, solution_group_id
`

type SetSubproblemSolutionTexParams struct {
	SubproblemID      int64   `json:"subproblem_id"`
	SolutionTexSource *string `json:"solution_tex_source"`
}

// Upsert: authoring разбор on a non-coffin subproblem creates the row.
func (q *Queries) SetSubproblemSolutionTex(ctx context.Context, arg SetSubproblemSolutionTexParams) (MathCenterSubproblemSolution, error) {
	row := q.db.QueryRow(ctx, setSubproblemSolutionTex, arg.SubproblemID, arg.SolutionTexSource)
	var i MathCenterSubproblemSolution
	err := row.Scan(
		&i.ID,
		&i.SubproblemID,
		&i.IsCoffin,
		&i.ReleasedAt,
		&i.SolutionTexSource,
		&i.SolutionPdfObjectKey,
		&i.SolutionLink,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SolutionGroupID,
	)
	return i, err
}

const upsertCoffinFlag = `-- name: UpsertCoffinFlag :one

INSERT INTO math_center_subproblem_solutions (subproblem_id, is_coffin)
VALUES ($1, $2)
ON CONFLICT (subproblem_id)
    DO UPDATE SET is_coffin = EXCLUDED.is_coffin, updated_at = NOW()
RETURNING id, subproblem_id, is_coffin, released_at, solution_tex_source, solution_pdf_object_key, solution_link, created_at, updated_at, solution_group_id
`

type UpsertCoffinFlagParams struct {
	SubproblemID int64 `json:"subproblem_id"`
	IsCoffin     bool  `json:"is_coffin"`
}

// Per-subproblem official solutions ("Разбор") + coffin state. A row exists iff
// the subproblem is a coffin OR carries a разбор. See migration 000011.
// A "coffin" (гроб) is a subproblem kept open for submission past the series
// deadline until its разбор is released (released_at).
// Mark/unmark a subproblem as a coffin without disturbing разбор fields.
func (q *Queries) UpsertCoffinFlag(ctx context.Context, arg UpsertCoffinFlagParams) (MathCenterSubproblemSolution, error) {
	row := q.db.QueryRow(ctx, upsertCoffinFlag, arg.SubproblemID, arg.IsCoffin)
	var i MathCenterSubproblemSolution
	err := row.Scan(
		&i.ID,
		&i.SubproblemID,
		&i.IsCoffin,
		&i.ReleasedAt,
		&i.SolutionTexSource,
		&i.SolutionPdfObjectKey,
		&i.SolutionLink,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SolutionGroupID,
	)
	return i, err
}
