// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telegram_alerts.sql

package store

import (
	"context"
	"time"
)

const consumeTelegramAlertEnrollmentSession = `-- name: ConsumeTelegramAlertEnrollmentSession :one
DELETE FROM telegram_alert_enrollment_sessions
WHERE telegram_user_id = $1
  AND request_id = $2
  AND expires_at > NOW()
RETURNING telegram_user_id
`

type ConsumeTelegramAlertEnrollmentSessionParams struct {
	TelegramUserID int64 `json:"telegram_user_id"`
	RequestID      int64 `json:"request_id"`
}

func (q *Queries) ConsumeTelegramAlertEnrollmentSession(ctx context.Context, arg ConsumeTelegramAlertEnrollmentSessionParams) (int64, error) {
	row := q.db.QueryRow(ctx, consumeTelegramAlertEnrollmentSession, arg.TelegramUserID, arg.RequestID)
	var telegram_user_id int64
	err := row.Scan(&telegram_user_id)
	return telegram_user_id, err
}

const createTelegramAlertEnrollmentSession = `-- name: CreateTelegramAlertEnrollmentSession :exec
INSERT INTO telegram_alert_enrollment_sessions
    (telegram_user_id, request_id, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (telegram_user_id) DO UPDATE SET
    request_id = EXCLUDED.request_id,
    expires_at = EXCLUDED.expires_at,
    created_at = NOW()
`

type CreateTelegramAlertEnrollmentSessionParams struct {
	TelegramUserID int64     `json:"telegram_user_id"`
	RequestID      int64     `json:"request_id"`
	ExpiresAt      time.Time `json:"expires_at"`
}

func (q *Queries) CreateTelegramAlertEnrollmentSession(ctx context.Context, arg CreateTelegramAlertEnrollmentSessionParams) error {
	_, err := q.db.Exec(ctx, createTelegramAlertEnrollmentSession, arg.TelegramUserID, arg.RequestID, arg.ExpiresAt)
	return err
}

const deleteTelegramAlertSubscription = `-- name: DeleteTelegramAlertSubscription :exec
DELETE FROM telegram_alert_subscriptions WHERE chat_id = $1
`

func (q *Queries) DeleteTelegramAlertSubscription(ctx context.Context, chatID int64) error {
	_, err := q.db.Exec(ctx, deleteTelegramAlertSubscription, chatID)
	return err
}

const disableTelegramAlertSubscription = `-- name: DisableTelegramAlertSubscription :exec
UPDATE telegram_alert_subscriptions
SET disabled_at = COALESCE(disabled_at, NOW()), updated_at = NOW()
WHERE chat_id = $1
`

func (q *Queries) DisableTelegramAlertSubscription(ctx context.Context, chatID int64) error {
	_, err := q.db.Exec(ctx, disableTelegramAlertSubscription, chatID)
	return err
}

const getTelegramAlertSubscription = `-- name: GetTelegramAlertSubscription :one
SELECT chat_id, chat_type, subscribed_by_user_id, created_at, updated_at, disabled_at
FROM telegram_alert_subscriptions
WHERE chat_id = $1
`

func (q *Queries) GetTelegramAlertSubscription(ctx context.Context, chatID int64) (TelegramAlertSubscription, error) {
	row := q.db.QueryRow(ctx, getTelegramAlertSubscription, chatID)
	var i TelegramAlertSubscription
	err := row.Scan(
		&i.ChatID,
		&i.ChatType,
		&i.SubscribedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const listActiveTelegramAlertSubscriptions = `-- name: ListActiveTelegramAlertSubscriptions :many

SELECT chat_id, chat_type, subscribed_by_user_id, created_at, updated_at, disabled_at
FROM telegram_alert_subscriptions
WHERE disabled_at IS NULL
ORDER BY chat_id
`

// Persistent Telegram alert destinations and one-use group enrollment state.
func (q *Queries) ListActiveTelegramAlertSubscriptions(ctx context.Context) ([]TelegramAlertSubscription, error) {
	rows, err := q.db.Query(ctx, listActiveTelegramAlertSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TelegramAlertSubscription{}
	for rows.Next() {
		var i TelegramAlertSubscription
		if err := rows.Scan(
			&i.ChatID,
			&i.ChatType,
			&i.SubscribedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeExpiredTelegramAlertEnrollmentSessions = `-- name: PurgeExpiredTelegramAlertEnrollmentSessions :exec
DELETE FROM telegram_alert_enrollment_sessions WHERE expires_at <= NOW()
`

func (q *Queries) PurgeExpiredTelegramAlertEnrollmentSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeExpiredTelegramAlertEnrollmentSessions)
	return err
}

const upsertTelegramAlertSubscription = `-- name: UpsertTelegramAlertSubscription :exec
INSERT INTO telegram_alert_subscriptions
    (chat_id, chat_type, subscribed_by_user_id)
VALUES ($1, $2, $3)
ON CONFLICT (chat_id) DO UPDATE SET
    chat_type = EXCLUDED.chat_type,
    subscribed_by_user_id = EXCLUDED.subscribed_by_user_id,
    updated_at = NOW(),
    disabled_at = NULL
`

type UpsertTelegramAlertSubscriptionParams struct {
	ChatID             int64  `json:"chat_id"`
	ChatType           string `json:"chat_type"`
	SubscribedByUserID int64  `json:"subscribed_by_user_id"`
}

func (q *Queries) UpsertTelegramAlertSubscription(ctx context.Context, arg UpsertTelegramAlertSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertTelegramAlertSubscription, arg.ChatID, arg.ChatType, arg.SubscribedByUserID)
	return err
}
