// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
)

const countUsesOfInvitationToken = `-- name: CountUsesOfInvitationToken :one
SELECT COUNT(*) FROM users WHERE invitation_token_id = $1
`

func (q *Queries) CountUsesOfInvitationToken(ctx context.Context, invitationTokenID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUsesOfInvitationToken, invitationTokenID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, first_name, middle_name, last_name, invitation_token_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, password_hash, first_name, middle_name, last_name, invitation_token_id, created_at, updated_at
`

type CreateUserParams struct {
	Username          string  `json:"username"`
	PasswordHash      string  `json:"-"`
	FirstName         string  `json:"first_name"`
	MiddleName        *string `json:"middle_name"`
	LastName          string  `json:"last_name"`
	InvitationTokenID int64   `json:"invitation_token_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.InvitationTokenID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.InvitationTokenID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, first_name, middle_name, last_name, invitation_token_id, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.InvitationTokenID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, first_name, middle_name, last_name, invitation_token_id, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.InvitationTokenID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
