// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
)

const countUsesOfInvitationToken = `-- name: CountUsesOfInvitationToken :one
SELECT COUNT(*)
FROM users
WHERE invitation_token_id = $1
`

func (q *Queries) CountUsesOfInvitationToken(ctx context.Context, invitationTokenID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUsesOfInvitationToken, invitationTokenID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, first_name, middle_name, last_name, invitation_token_id)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, username, password_hash, first_name, middle_name, last_name, invitation_token_id, created_at, updated_at, is_admin
`

type CreateUserParams struct {
	Username          string  `json:"username"`
	PasswordHash      string  `json:"-"`
	FirstName         string  `json:"first_name"`
	MiddleName        *string `json:"middle_name"`
	LastName          string  `json:"last_name"`
	InvitationTokenID int64   `json:"invitation_token_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.InvitationTokenID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.InvitationTokenID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, first_name, middle_name, last_name, invitation_token_id, created_at, updated_at, is_admin
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.InvitationTokenID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, first_name, middle_name, last_name, invitation_token_id, created_at, updated_at, is_admin
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.InvitationTokenID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, first_name, middle_name, last_name
FROM users
WHERE id = ANY ($1::bigint[])
`

type GetUsersByIDsRow struct {
	ID         int64   `json:"id"`
	FirstName  string  `json:"first_name"`
	MiddleName *string `json:"middle_name"`
	LastName   string  `json:"last_name"`
}

// Bulk lookup used by the homework thread view: it needs to translate
// every user_id on the page (student, last grader, claim holder, every
// event's actor) into a display name. ANY(array) is one round-trip vs
// N+1 GetUserByID calls.
func (q *Queries) GetUsersByIDs(ctx context.Context, ids []int64) ([]GetUsersByIDsRow, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersByIDsRow{}
	for rows.Next() {
		var i GetUsersByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, first_name, middle_name, last_name, invitation_token_id, created_at, updated_at, is_admin
FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
			&i.InvitationTokenID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserAdmin = `-- name: SetUserAdmin :exec
UPDATE users
SET is_admin   = $2,
    updated_at = NOW()
WHERE id = $1
`

type SetUserAdminParams struct {
	ID      int64 `json:"id"`
	IsAdmin bool  `json:"is_admin"`
}

func (q *Queries) SetUserAdmin(ctx context.Context, arg SetUserAdminParams) error {
	_, err := q.db.Exec(ctx, setUserAdmin, arg.ID, arg.IsAdmin)
	return err
}
